package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"
)

// ConversationAnalytics holds the schema definition for the ConversationAnalytics entity.
// This tracks analytics for each chat session to improve AI responses.
type ConversationAnalytics struct {
	ent.Schema
}

// Fields of the ConversationAnalytics.
func (ConversationAnalytics) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).
			Default(uuid.New).
			Immutable(),
		field.UUID("user_id", uuid.UUID{}).
			Optional(), // Optional for anonymous sessions
		field.UUID("session_id", uuid.UUID{}),

		// Session metrics
		field.Int("message_count").
			Default(0),
		field.Int("user_message_count").
			Default(0),
		field.Int("assistant_message_count").
			Default(0),
		field.Int("search_count").
			Default(0),
		field.Int("products_shown").
			Default(0),
		field.Int("products_clicked").
			Default(0),

		// Duration in seconds
		field.Int("session_duration").
			Default(0),

		// Key topics extracted from conversation (using embeddings)
		field.JSON("key_topics", []string{}).
			SchemaType(map[string]string{
				dialect.Postgres: "jsonb",
			}).
			Default([]string{}),

		// Categories explored during session
		field.JSON("categories_explored", []string{}).
			SchemaType(map[string]string{
				dialect.Postgres: "jsonb",
			}).
			Default([]string{}),

		// Sentiment analysis: "positive", "neutral", "negative", "mixed"
		field.String("overall_sentiment").
			Default("neutral"),

		// Sentiment score (-1.0 to 1.0)
		field.Float("sentiment_score").
			Default(0),

		// Intent classification: "exploration", "purchase", "comparison", "information"
		field.String("primary_intent").
			Optional(),

		// Success indicators
		field.Bool("found_product").
			Default(false),
		field.Bool("session_completed").
			Default(false),
		field.Bool("user_satisfied").
			Optional(), // Can be inferred from behavior

		// Average response time from AI (milliseconds)
		field.Int("avg_response_time").
			Default(0),

		// Number of clarification questions asked by AI
		field.Int("clarification_count").
			Default(0),

		// Number of search refinements
		field.Int("search_refinement_count").
			Default(0),

		// Conversation flow quality (0-1 scale)
		field.Float("flow_quality_score").
			Default(0),

		// Extracted user preferences from this session
		field.JSON("extracted_preferences", map[string]interface{}{}).
			SchemaType(map[string]string{
				dialect.Postgres: "jsonb",
			}).
			Default(map[string]interface{}{}),

		// Price sensitivity indicators
		field.JSON("price_mentions", []float64{}).
			SchemaType(map[string]string{
				dialect.Postgres: "jsonb",
			}).
			Default([]float64{}),

		// Brand mentions during conversation
		field.JSON("brand_mentions", []string{}).
			SchemaType(map[string]string{
				dialect.Postgres: "jsonb",
			}).
			Default([]string{}),

		// Conversation summary (generated by AI)
		field.Text("summary").
			Optional(),

		// Session start and end times
		field.Time("session_started_at").
			Default(time.Now),
		field.Time("session_ended_at").
			Optional(),

		field.Time("created_at").
			Immutable().
			Default(time.Now),
		field.Time("updated_at").
			Default(time.Now).
			UpdateDefault(time.Now),
	}
}

// Edges of the ConversationAnalytics.
func (ConversationAnalytics) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("user", User.Type).
			Ref("conversation_analytics").
			Field("user_id").
			Unique(),
		edge.From("session", ChatSession.Type).
			Ref("analytics").
			Field("session_id").
			Required().
			Unique(),
	}
}

// Indexes of the ConversationAnalytics.
func (ConversationAnalytics) Indexes() []ent.Index {
	return []ent.Index{
		// Index for user analytics queries
		index.Fields("user_id", "created_at"),
		// Index for session lookup
		index.Fields("session_id").
			Unique(),
		// Index for finding successful sessions
		index.Fields("user_id", "found_product", "user_satisfied"),
		// Index for intent-based queries
		index.Fields("primary_intent", "created_at"),
	}
}
