// Code generated by ent, DO NOT EDIT.

package conversationanalytics

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the conversationanalytics type in the database.
	Label = "conversation_analytics"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldMessageCount holds the string denoting the message_count field in the database.
	FieldMessageCount = "message_count"
	// FieldUserMessageCount holds the string denoting the user_message_count field in the database.
	FieldUserMessageCount = "user_message_count"
	// FieldAssistantMessageCount holds the string denoting the assistant_message_count field in the database.
	FieldAssistantMessageCount = "assistant_message_count"
	// FieldSearchCount holds the string denoting the search_count field in the database.
	FieldSearchCount = "search_count"
	// FieldProductsShown holds the string denoting the products_shown field in the database.
	FieldProductsShown = "products_shown"
	// FieldProductsClicked holds the string denoting the products_clicked field in the database.
	FieldProductsClicked = "products_clicked"
	// FieldSessionDuration holds the string denoting the session_duration field in the database.
	FieldSessionDuration = "session_duration"
	// FieldKeyTopics holds the string denoting the key_topics field in the database.
	FieldKeyTopics = "key_topics"
	// FieldCategoriesExplored holds the string denoting the categories_explored field in the database.
	FieldCategoriesExplored = "categories_explored"
	// FieldOverallSentiment holds the string denoting the overall_sentiment field in the database.
	FieldOverallSentiment = "overall_sentiment"
	// FieldSentimentScore holds the string denoting the sentiment_score field in the database.
	FieldSentimentScore = "sentiment_score"
	// FieldPrimaryIntent holds the string denoting the primary_intent field in the database.
	FieldPrimaryIntent = "primary_intent"
	// FieldFoundProduct holds the string denoting the found_product field in the database.
	FieldFoundProduct = "found_product"
	// FieldSessionCompleted holds the string denoting the session_completed field in the database.
	FieldSessionCompleted = "session_completed"
	// FieldUserSatisfied holds the string denoting the user_satisfied field in the database.
	FieldUserSatisfied = "user_satisfied"
	// FieldAvgResponseTime holds the string denoting the avg_response_time field in the database.
	FieldAvgResponseTime = "avg_response_time"
	// FieldClarificationCount holds the string denoting the clarification_count field in the database.
	FieldClarificationCount = "clarification_count"
	// FieldSearchRefinementCount holds the string denoting the search_refinement_count field in the database.
	FieldSearchRefinementCount = "search_refinement_count"
	// FieldFlowQualityScore holds the string denoting the flow_quality_score field in the database.
	FieldFlowQualityScore = "flow_quality_score"
	// FieldExtractedPreferences holds the string denoting the extracted_preferences field in the database.
	FieldExtractedPreferences = "extracted_preferences"
	// FieldPriceMentions holds the string denoting the price_mentions field in the database.
	FieldPriceMentions = "price_mentions"
	// FieldBrandMentions holds the string denoting the brand_mentions field in the database.
	FieldBrandMentions = "brand_mentions"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldSessionStartedAt holds the string denoting the session_started_at field in the database.
	FieldSessionStartedAt = "session_started_at"
	// FieldSessionEndedAt holds the string denoting the session_ended_at field in the database.
	FieldSessionEndedAt = "session_ended_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeSession holds the string denoting the session edge name in mutations.
	EdgeSession = "session"
	// Table holds the table name of the conversationanalytics in the database.
	Table = "conversation_analytics"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "conversation_analytics"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// SessionTable is the table that holds the session relation/edge.
	SessionTable = "conversation_analytics"
	// SessionInverseTable is the table name for the ChatSession entity.
	// It exists in this package in order to avoid circular dependency with the "chatsession" package.
	SessionInverseTable = "chat_sessions"
	// SessionColumn is the table column denoting the session relation/edge.
	SessionColumn = "session_id"
)

// Columns holds all SQL columns for conversationanalytics fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldSessionID,
	FieldMessageCount,
	FieldUserMessageCount,
	FieldAssistantMessageCount,
	FieldSearchCount,
	FieldProductsShown,
	FieldProductsClicked,
	FieldSessionDuration,
	FieldKeyTopics,
	FieldCategoriesExplored,
	FieldOverallSentiment,
	FieldSentimentScore,
	FieldPrimaryIntent,
	FieldFoundProduct,
	FieldSessionCompleted,
	FieldUserSatisfied,
	FieldAvgResponseTime,
	FieldClarificationCount,
	FieldSearchRefinementCount,
	FieldFlowQualityScore,
	FieldExtractedPreferences,
	FieldPriceMentions,
	FieldBrandMentions,
	FieldSummary,
	FieldSessionStartedAt,
	FieldSessionEndedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultMessageCount holds the default value on creation for the "message_count" field.
	DefaultMessageCount int
	// DefaultUserMessageCount holds the default value on creation for the "user_message_count" field.
	DefaultUserMessageCount int
	// DefaultAssistantMessageCount holds the default value on creation for the "assistant_message_count" field.
	DefaultAssistantMessageCount int
	// DefaultSearchCount holds the default value on creation for the "search_count" field.
	DefaultSearchCount int
	// DefaultProductsShown holds the default value on creation for the "products_shown" field.
	DefaultProductsShown int
	// DefaultProductsClicked holds the default value on creation for the "products_clicked" field.
	DefaultProductsClicked int
	// DefaultSessionDuration holds the default value on creation for the "session_duration" field.
	DefaultSessionDuration int
	// DefaultKeyTopics holds the default value on creation for the "key_topics" field.
	DefaultKeyTopics []string
	// DefaultCategoriesExplored holds the default value on creation for the "categories_explored" field.
	DefaultCategoriesExplored []string
	// DefaultOverallSentiment holds the default value on creation for the "overall_sentiment" field.
	DefaultOverallSentiment string
	// DefaultSentimentScore holds the default value on creation for the "sentiment_score" field.
	DefaultSentimentScore float64
	// DefaultFoundProduct holds the default value on creation for the "found_product" field.
	DefaultFoundProduct bool
	// DefaultSessionCompleted holds the default value on creation for the "session_completed" field.
	DefaultSessionCompleted bool
	// DefaultAvgResponseTime holds the default value on creation for the "avg_response_time" field.
	DefaultAvgResponseTime int
	// DefaultClarificationCount holds the default value on creation for the "clarification_count" field.
	DefaultClarificationCount int
	// DefaultSearchRefinementCount holds the default value on creation for the "search_refinement_count" field.
	DefaultSearchRefinementCount int
	// DefaultFlowQualityScore holds the default value on creation for the "flow_quality_score" field.
	DefaultFlowQualityScore float64
	// DefaultExtractedPreferences holds the default value on creation for the "extracted_preferences" field.
	DefaultExtractedPreferences map[string]interface{}
	// DefaultPriceMentions holds the default value on creation for the "price_mentions" field.
	DefaultPriceMentions []float64
	// DefaultBrandMentions holds the default value on creation for the "brand_mentions" field.
	DefaultBrandMentions []string
	// DefaultSessionStartedAt holds the default value on creation for the "session_started_at" field.
	DefaultSessionStartedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ConversationAnalytics queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByMessageCount orders the results by the message_count field.
func ByMessageCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessageCount, opts...).ToFunc()
}

// ByUserMessageCount orders the results by the user_message_count field.
func ByUserMessageCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserMessageCount, opts...).ToFunc()
}

// ByAssistantMessageCount orders the results by the assistant_message_count field.
func ByAssistantMessageCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssistantMessageCount, opts...).ToFunc()
}

// BySearchCount orders the results by the search_count field.
func BySearchCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSearchCount, opts...).ToFunc()
}

// ByProductsShown orders the results by the products_shown field.
func ByProductsShown(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductsShown, opts...).ToFunc()
}

// ByProductsClicked orders the results by the products_clicked field.
func ByProductsClicked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductsClicked, opts...).ToFunc()
}

// BySessionDuration orders the results by the session_duration field.
func BySessionDuration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionDuration, opts...).ToFunc()
}

// ByOverallSentiment orders the results by the overall_sentiment field.
func ByOverallSentiment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOverallSentiment, opts...).ToFunc()
}

// BySentimentScore orders the results by the sentiment_score field.
func BySentimentScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSentimentScore, opts...).ToFunc()
}

// ByPrimaryIntent orders the results by the primary_intent field.
func ByPrimaryIntent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrimaryIntent, opts...).ToFunc()
}

// ByFoundProduct orders the results by the found_product field.
func ByFoundProduct(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFoundProduct, opts...).ToFunc()
}

// BySessionCompleted orders the results by the session_completed field.
func BySessionCompleted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionCompleted, opts...).ToFunc()
}

// ByUserSatisfied orders the results by the user_satisfied field.
func ByUserSatisfied(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserSatisfied, opts...).ToFunc()
}

// ByAvgResponseTime orders the results by the avg_response_time field.
func ByAvgResponseTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvgResponseTime, opts...).ToFunc()
}

// ByClarificationCount orders the results by the clarification_count field.
func ByClarificationCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClarificationCount, opts...).ToFunc()
}

// BySearchRefinementCount orders the results by the search_refinement_count field.
func BySearchRefinementCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSearchRefinementCount, opts...).ToFunc()
}

// ByFlowQualityScore orders the results by the flow_quality_score field.
func ByFlowQualityScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFlowQualityScore, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// BySessionStartedAt orders the results by the session_started_at field.
func BySessionStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionStartedAt, opts...).ToFunc()
}

// BySessionEndedAt orders the results by the session_ended_at field.
func BySessionEndedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionEndedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// BySessionField orders the results by session field.
func BySessionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newSessionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, SessionTable, SessionColumn),
	)
}
