// Code generated by ent, DO NOT EDIT.

package conversationanalytics

import (
	"mylittleprice/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldUserID, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v uuid.UUID) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldSessionID, v))
}

// MessageCount applies equality check predicate on the "message_count" field. It's identical to MessageCountEQ.
func MessageCount(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldMessageCount, v))
}

// UserMessageCount applies equality check predicate on the "user_message_count" field. It's identical to UserMessageCountEQ.
func UserMessageCount(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldUserMessageCount, v))
}

// AssistantMessageCount applies equality check predicate on the "assistant_message_count" field. It's identical to AssistantMessageCountEQ.
func AssistantMessageCount(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldAssistantMessageCount, v))
}

// SearchCount applies equality check predicate on the "search_count" field. It's identical to SearchCountEQ.
func SearchCount(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldSearchCount, v))
}

// ProductsShown applies equality check predicate on the "products_shown" field. It's identical to ProductsShownEQ.
func ProductsShown(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldProductsShown, v))
}

// ProductsClicked applies equality check predicate on the "products_clicked" field. It's identical to ProductsClickedEQ.
func ProductsClicked(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldProductsClicked, v))
}

// SessionDuration applies equality check predicate on the "session_duration" field. It's identical to SessionDurationEQ.
func SessionDuration(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldSessionDuration, v))
}

// OverallSentiment applies equality check predicate on the "overall_sentiment" field. It's identical to OverallSentimentEQ.
func OverallSentiment(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldOverallSentiment, v))
}

// SentimentScore applies equality check predicate on the "sentiment_score" field. It's identical to SentimentScoreEQ.
func SentimentScore(v float64) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldSentimentScore, v))
}

// PrimaryIntent applies equality check predicate on the "primary_intent" field. It's identical to PrimaryIntentEQ.
func PrimaryIntent(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldPrimaryIntent, v))
}

// FoundProduct applies equality check predicate on the "found_product" field. It's identical to FoundProductEQ.
func FoundProduct(v bool) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldFoundProduct, v))
}

// SessionCompleted applies equality check predicate on the "session_completed" field. It's identical to SessionCompletedEQ.
func SessionCompleted(v bool) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldSessionCompleted, v))
}

// UserSatisfied applies equality check predicate on the "user_satisfied" field. It's identical to UserSatisfiedEQ.
func UserSatisfied(v bool) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldUserSatisfied, v))
}

// AvgResponseTime applies equality check predicate on the "avg_response_time" field. It's identical to AvgResponseTimeEQ.
func AvgResponseTime(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldAvgResponseTime, v))
}

// ClarificationCount applies equality check predicate on the "clarification_count" field. It's identical to ClarificationCountEQ.
func ClarificationCount(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldClarificationCount, v))
}

// SearchRefinementCount applies equality check predicate on the "search_refinement_count" field. It's identical to SearchRefinementCountEQ.
func SearchRefinementCount(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldSearchRefinementCount, v))
}

// FlowQualityScore applies equality check predicate on the "flow_quality_score" field. It's identical to FlowQualityScoreEQ.
func FlowQualityScore(v float64) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldFlowQualityScore, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldSummary, v))
}

// SessionStartedAt applies equality check predicate on the "session_started_at" field. It's identical to SessionStartedAtEQ.
func SessionStartedAt(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldSessionStartedAt, v))
}

// SessionEndedAt applies equality check predicate on the "session_ended_at" field. It's identical to SessionEndedAtEQ.
func SessionEndedAt(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldSessionEndedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotNull(FieldUserID))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v uuid.UUID) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v uuid.UUID) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...uuid.UUID) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...uuid.UUID) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldSessionID, vs...))
}

// MessageCountEQ applies the EQ predicate on the "message_count" field.
func MessageCountEQ(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldMessageCount, v))
}

// MessageCountNEQ applies the NEQ predicate on the "message_count" field.
func MessageCountNEQ(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldMessageCount, v))
}

// MessageCountIn applies the In predicate on the "message_count" field.
func MessageCountIn(vs ...int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldMessageCount, vs...))
}

// MessageCountNotIn applies the NotIn predicate on the "message_count" field.
func MessageCountNotIn(vs ...int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldMessageCount, vs...))
}

// MessageCountGT applies the GT predicate on the "message_count" field.
func MessageCountGT(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGT(FieldMessageCount, v))
}

// MessageCountGTE applies the GTE predicate on the "message_count" field.
func MessageCountGTE(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGTE(FieldMessageCount, v))
}

// MessageCountLT applies the LT predicate on the "message_count" field.
func MessageCountLT(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLT(FieldMessageCount, v))
}

// MessageCountLTE applies the LTE predicate on the "message_count" field.
func MessageCountLTE(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLTE(FieldMessageCount, v))
}

// UserMessageCountEQ applies the EQ predicate on the "user_message_count" field.
func UserMessageCountEQ(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldUserMessageCount, v))
}

// UserMessageCountNEQ applies the NEQ predicate on the "user_message_count" field.
func UserMessageCountNEQ(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldUserMessageCount, v))
}

// UserMessageCountIn applies the In predicate on the "user_message_count" field.
func UserMessageCountIn(vs ...int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldUserMessageCount, vs...))
}

// UserMessageCountNotIn applies the NotIn predicate on the "user_message_count" field.
func UserMessageCountNotIn(vs ...int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldUserMessageCount, vs...))
}

// UserMessageCountGT applies the GT predicate on the "user_message_count" field.
func UserMessageCountGT(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGT(FieldUserMessageCount, v))
}

// UserMessageCountGTE applies the GTE predicate on the "user_message_count" field.
func UserMessageCountGTE(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGTE(FieldUserMessageCount, v))
}

// UserMessageCountLT applies the LT predicate on the "user_message_count" field.
func UserMessageCountLT(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLT(FieldUserMessageCount, v))
}

// UserMessageCountLTE applies the LTE predicate on the "user_message_count" field.
func UserMessageCountLTE(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLTE(FieldUserMessageCount, v))
}

// AssistantMessageCountEQ applies the EQ predicate on the "assistant_message_count" field.
func AssistantMessageCountEQ(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldAssistantMessageCount, v))
}

// AssistantMessageCountNEQ applies the NEQ predicate on the "assistant_message_count" field.
func AssistantMessageCountNEQ(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldAssistantMessageCount, v))
}

// AssistantMessageCountIn applies the In predicate on the "assistant_message_count" field.
func AssistantMessageCountIn(vs ...int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldAssistantMessageCount, vs...))
}

// AssistantMessageCountNotIn applies the NotIn predicate on the "assistant_message_count" field.
func AssistantMessageCountNotIn(vs ...int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldAssistantMessageCount, vs...))
}

// AssistantMessageCountGT applies the GT predicate on the "assistant_message_count" field.
func AssistantMessageCountGT(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGT(FieldAssistantMessageCount, v))
}

// AssistantMessageCountGTE applies the GTE predicate on the "assistant_message_count" field.
func AssistantMessageCountGTE(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGTE(FieldAssistantMessageCount, v))
}

// AssistantMessageCountLT applies the LT predicate on the "assistant_message_count" field.
func AssistantMessageCountLT(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLT(FieldAssistantMessageCount, v))
}

// AssistantMessageCountLTE applies the LTE predicate on the "assistant_message_count" field.
func AssistantMessageCountLTE(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLTE(FieldAssistantMessageCount, v))
}

// SearchCountEQ applies the EQ predicate on the "search_count" field.
func SearchCountEQ(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldSearchCount, v))
}

// SearchCountNEQ applies the NEQ predicate on the "search_count" field.
func SearchCountNEQ(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldSearchCount, v))
}

// SearchCountIn applies the In predicate on the "search_count" field.
func SearchCountIn(vs ...int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldSearchCount, vs...))
}

// SearchCountNotIn applies the NotIn predicate on the "search_count" field.
func SearchCountNotIn(vs ...int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldSearchCount, vs...))
}

// SearchCountGT applies the GT predicate on the "search_count" field.
func SearchCountGT(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGT(FieldSearchCount, v))
}

// SearchCountGTE applies the GTE predicate on the "search_count" field.
func SearchCountGTE(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGTE(FieldSearchCount, v))
}

// SearchCountLT applies the LT predicate on the "search_count" field.
func SearchCountLT(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLT(FieldSearchCount, v))
}

// SearchCountLTE applies the LTE predicate on the "search_count" field.
func SearchCountLTE(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLTE(FieldSearchCount, v))
}

// ProductsShownEQ applies the EQ predicate on the "products_shown" field.
func ProductsShownEQ(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldProductsShown, v))
}

// ProductsShownNEQ applies the NEQ predicate on the "products_shown" field.
func ProductsShownNEQ(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldProductsShown, v))
}

// ProductsShownIn applies the In predicate on the "products_shown" field.
func ProductsShownIn(vs ...int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldProductsShown, vs...))
}

// ProductsShownNotIn applies the NotIn predicate on the "products_shown" field.
func ProductsShownNotIn(vs ...int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldProductsShown, vs...))
}

// ProductsShownGT applies the GT predicate on the "products_shown" field.
func ProductsShownGT(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGT(FieldProductsShown, v))
}

// ProductsShownGTE applies the GTE predicate on the "products_shown" field.
func ProductsShownGTE(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGTE(FieldProductsShown, v))
}

// ProductsShownLT applies the LT predicate on the "products_shown" field.
func ProductsShownLT(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLT(FieldProductsShown, v))
}

// ProductsShownLTE applies the LTE predicate on the "products_shown" field.
func ProductsShownLTE(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLTE(FieldProductsShown, v))
}

// ProductsClickedEQ applies the EQ predicate on the "products_clicked" field.
func ProductsClickedEQ(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldProductsClicked, v))
}

// ProductsClickedNEQ applies the NEQ predicate on the "products_clicked" field.
func ProductsClickedNEQ(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldProductsClicked, v))
}

// ProductsClickedIn applies the In predicate on the "products_clicked" field.
func ProductsClickedIn(vs ...int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldProductsClicked, vs...))
}

// ProductsClickedNotIn applies the NotIn predicate on the "products_clicked" field.
func ProductsClickedNotIn(vs ...int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldProductsClicked, vs...))
}

// ProductsClickedGT applies the GT predicate on the "products_clicked" field.
func ProductsClickedGT(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGT(FieldProductsClicked, v))
}

// ProductsClickedGTE applies the GTE predicate on the "products_clicked" field.
func ProductsClickedGTE(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGTE(FieldProductsClicked, v))
}

// ProductsClickedLT applies the LT predicate on the "products_clicked" field.
func ProductsClickedLT(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLT(FieldProductsClicked, v))
}

// ProductsClickedLTE applies the LTE predicate on the "products_clicked" field.
func ProductsClickedLTE(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLTE(FieldProductsClicked, v))
}

// SessionDurationEQ applies the EQ predicate on the "session_duration" field.
func SessionDurationEQ(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldSessionDuration, v))
}

// SessionDurationNEQ applies the NEQ predicate on the "session_duration" field.
func SessionDurationNEQ(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldSessionDuration, v))
}

// SessionDurationIn applies the In predicate on the "session_duration" field.
func SessionDurationIn(vs ...int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldSessionDuration, vs...))
}

// SessionDurationNotIn applies the NotIn predicate on the "session_duration" field.
func SessionDurationNotIn(vs ...int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldSessionDuration, vs...))
}

// SessionDurationGT applies the GT predicate on the "session_duration" field.
func SessionDurationGT(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGT(FieldSessionDuration, v))
}

// SessionDurationGTE applies the GTE predicate on the "session_duration" field.
func SessionDurationGTE(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGTE(FieldSessionDuration, v))
}

// SessionDurationLT applies the LT predicate on the "session_duration" field.
func SessionDurationLT(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLT(FieldSessionDuration, v))
}

// SessionDurationLTE applies the LTE predicate on the "session_duration" field.
func SessionDurationLTE(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLTE(FieldSessionDuration, v))
}

// OverallSentimentEQ applies the EQ predicate on the "overall_sentiment" field.
func OverallSentimentEQ(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldOverallSentiment, v))
}

// OverallSentimentNEQ applies the NEQ predicate on the "overall_sentiment" field.
func OverallSentimentNEQ(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldOverallSentiment, v))
}

// OverallSentimentIn applies the In predicate on the "overall_sentiment" field.
func OverallSentimentIn(vs ...string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldOverallSentiment, vs...))
}

// OverallSentimentNotIn applies the NotIn predicate on the "overall_sentiment" field.
func OverallSentimentNotIn(vs ...string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldOverallSentiment, vs...))
}

// OverallSentimentGT applies the GT predicate on the "overall_sentiment" field.
func OverallSentimentGT(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGT(FieldOverallSentiment, v))
}

// OverallSentimentGTE applies the GTE predicate on the "overall_sentiment" field.
func OverallSentimentGTE(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGTE(FieldOverallSentiment, v))
}

// OverallSentimentLT applies the LT predicate on the "overall_sentiment" field.
func OverallSentimentLT(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLT(FieldOverallSentiment, v))
}

// OverallSentimentLTE applies the LTE predicate on the "overall_sentiment" field.
func OverallSentimentLTE(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLTE(FieldOverallSentiment, v))
}

// OverallSentimentContains applies the Contains predicate on the "overall_sentiment" field.
func OverallSentimentContains(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldContains(FieldOverallSentiment, v))
}

// OverallSentimentHasPrefix applies the HasPrefix predicate on the "overall_sentiment" field.
func OverallSentimentHasPrefix(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldHasPrefix(FieldOverallSentiment, v))
}

// OverallSentimentHasSuffix applies the HasSuffix predicate on the "overall_sentiment" field.
func OverallSentimentHasSuffix(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldHasSuffix(FieldOverallSentiment, v))
}

// OverallSentimentEqualFold applies the EqualFold predicate on the "overall_sentiment" field.
func OverallSentimentEqualFold(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEqualFold(FieldOverallSentiment, v))
}

// OverallSentimentContainsFold applies the ContainsFold predicate on the "overall_sentiment" field.
func OverallSentimentContainsFold(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldContainsFold(FieldOverallSentiment, v))
}

// SentimentScoreEQ applies the EQ predicate on the "sentiment_score" field.
func SentimentScoreEQ(v float64) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldSentimentScore, v))
}

// SentimentScoreNEQ applies the NEQ predicate on the "sentiment_score" field.
func SentimentScoreNEQ(v float64) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldSentimentScore, v))
}

// SentimentScoreIn applies the In predicate on the "sentiment_score" field.
func SentimentScoreIn(vs ...float64) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldSentimentScore, vs...))
}

// SentimentScoreNotIn applies the NotIn predicate on the "sentiment_score" field.
func SentimentScoreNotIn(vs ...float64) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldSentimentScore, vs...))
}

// SentimentScoreGT applies the GT predicate on the "sentiment_score" field.
func SentimentScoreGT(v float64) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGT(FieldSentimentScore, v))
}

// SentimentScoreGTE applies the GTE predicate on the "sentiment_score" field.
func SentimentScoreGTE(v float64) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGTE(FieldSentimentScore, v))
}

// SentimentScoreLT applies the LT predicate on the "sentiment_score" field.
func SentimentScoreLT(v float64) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLT(FieldSentimentScore, v))
}

// SentimentScoreLTE applies the LTE predicate on the "sentiment_score" field.
func SentimentScoreLTE(v float64) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLTE(FieldSentimentScore, v))
}

// PrimaryIntentEQ applies the EQ predicate on the "primary_intent" field.
func PrimaryIntentEQ(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldPrimaryIntent, v))
}

// PrimaryIntentNEQ applies the NEQ predicate on the "primary_intent" field.
func PrimaryIntentNEQ(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldPrimaryIntent, v))
}

// PrimaryIntentIn applies the In predicate on the "primary_intent" field.
func PrimaryIntentIn(vs ...string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldPrimaryIntent, vs...))
}

// PrimaryIntentNotIn applies the NotIn predicate on the "primary_intent" field.
func PrimaryIntentNotIn(vs ...string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldPrimaryIntent, vs...))
}

// PrimaryIntentGT applies the GT predicate on the "primary_intent" field.
func PrimaryIntentGT(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGT(FieldPrimaryIntent, v))
}

// PrimaryIntentGTE applies the GTE predicate on the "primary_intent" field.
func PrimaryIntentGTE(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGTE(FieldPrimaryIntent, v))
}

// PrimaryIntentLT applies the LT predicate on the "primary_intent" field.
func PrimaryIntentLT(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLT(FieldPrimaryIntent, v))
}

// PrimaryIntentLTE applies the LTE predicate on the "primary_intent" field.
func PrimaryIntentLTE(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLTE(FieldPrimaryIntent, v))
}

// PrimaryIntentContains applies the Contains predicate on the "primary_intent" field.
func PrimaryIntentContains(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldContains(FieldPrimaryIntent, v))
}

// PrimaryIntentHasPrefix applies the HasPrefix predicate on the "primary_intent" field.
func PrimaryIntentHasPrefix(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldHasPrefix(FieldPrimaryIntent, v))
}

// PrimaryIntentHasSuffix applies the HasSuffix predicate on the "primary_intent" field.
func PrimaryIntentHasSuffix(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldHasSuffix(FieldPrimaryIntent, v))
}

// PrimaryIntentIsNil applies the IsNil predicate on the "primary_intent" field.
func PrimaryIntentIsNil() predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIsNull(FieldPrimaryIntent))
}

// PrimaryIntentNotNil applies the NotNil predicate on the "primary_intent" field.
func PrimaryIntentNotNil() predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotNull(FieldPrimaryIntent))
}

// PrimaryIntentEqualFold applies the EqualFold predicate on the "primary_intent" field.
func PrimaryIntentEqualFold(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEqualFold(FieldPrimaryIntent, v))
}

// PrimaryIntentContainsFold applies the ContainsFold predicate on the "primary_intent" field.
func PrimaryIntentContainsFold(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldContainsFold(FieldPrimaryIntent, v))
}

// FoundProductEQ applies the EQ predicate on the "found_product" field.
func FoundProductEQ(v bool) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldFoundProduct, v))
}

// FoundProductNEQ applies the NEQ predicate on the "found_product" field.
func FoundProductNEQ(v bool) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldFoundProduct, v))
}

// SessionCompletedEQ applies the EQ predicate on the "session_completed" field.
func SessionCompletedEQ(v bool) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldSessionCompleted, v))
}

// SessionCompletedNEQ applies the NEQ predicate on the "session_completed" field.
func SessionCompletedNEQ(v bool) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldSessionCompleted, v))
}

// UserSatisfiedEQ applies the EQ predicate on the "user_satisfied" field.
func UserSatisfiedEQ(v bool) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldUserSatisfied, v))
}

// UserSatisfiedNEQ applies the NEQ predicate on the "user_satisfied" field.
func UserSatisfiedNEQ(v bool) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldUserSatisfied, v))
}

// UserSatisfiedIsNil applies the IsNil predicate on the "user_satisfied" field.
func UserSatisfiedIsNil() predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIsNull(FieldUserSatisfied))
}

// UserSatisfiedNotNil applies the NotNil predicate on the "user_satisfied" field.
func UserSatisfiedNotNil() predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotNull(FieldUserSatisfied))
}

// AvgResponseTimeEQ applies the EQ predicate on the "avg_response_time" field.
func AvgResponseTimeEQ(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldAvgResponseTime, v))
}

// AvgResponseTimeNEQ applies the NEQ predicate on the "avg_response_time" field.
func AvgResponseTimeNEQ(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldAvgResponseTime, v))
}

// AvgResponseTimeIn applies the In predicate on the "avg_response_time" field.
func AvgResponseTimeIn(vs ...int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldAvgResponseTime, vs...))
}

// AvgResponseTimeNotIn applies the NotIn predicate on the "avg_response_time" field.
func AvgResponseTimeNotIn(vs ...int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldAvgResponseTime, vs...))
}

// AvgResponseTimeGT applies the GT predicate on the "avg_response_time" field.
func AvgResponseTimeGT(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGT(FieldAvgResponseTime, v))
}

// AvgResponseTimeGTE applies the GTE predicate on the "avg_response_time" field.
func AvgResponseTimeGTE(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGTE(FieldAvgResponseTime, v))
}

// AvgResponseTimeLT applies the LT predicate on the "avg_response_time" field.
func AvgResponseTimeLT(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLT(FieldAvgResponseTime, v))
}

// AvgResponseTimeLTE applies the LTE predicate on the "avg_response_time" field.
func AvgResponseTimeLTE(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLTE(FieldAvgResponseTime, v))
}

// ClarificationCountEQ applies the EQ predicate on the "clarification_count" field.
func ClarificationCountEQ(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldClarificationCount, v))
}

// ClarificationCountNEQ applies the NEQ predicate on the "clarification_count" field.
func ClarificationCountNEQ(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldClarificationCount, v))
}

// ClarificationCountIn applies the In predicate on the "clarification_count" field.
func ClarificationCountIn(vs ...int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldClarificationCount, vs...))
}

// ClarificationCountNotIn applies the NotIn predicate on the "clarification_count" field.
func ClarificationCountNotIn(vs ...int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldClarificationCount, vs...))
}

// ClarificationCountGT applies the GT predicate on the "clarification_count" field.
func ClarificationCountGT(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGT(FieldClarificationCount, v))
}

// ClarificationCountGTE applies the GTE predicate on the "clarification_count" field.
func ClarificationCountGTE(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGTE(FieldClarificationCount, v))
}

// ClarificationCountLT applies the LT predicate on the "clarification_count" field.
func ClarificationCountLT(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLT(FieldClarificationCount, v))
}

// ClarificationCountLTE applies the LTE predicate on the "clarification_count" field.
func ClarificationCountLTE(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLTE(FieldClarificationCount, v))
}

// SearchRefinementCountEQ applies the EQ predicate on the "search_refinement_count" field.
func SearchRefinementCountEQ(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldSearchRefinementCount, v))
}

// SearchRefinementCountNEQ applies the NEQ predicate on the "search_refinement_count" field.
func SearchRefinementCountNEQ(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldSearchRefinementCount, v))
}

// SearchRefinementCountIn applies the In predicate on the "search_refinement_count" field.
func SearchRefinementCountIn(vs ...int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldSearchRefinementCount, vs...))
}

// SearchRefinementCountNotIn applies the NotIn predicate on the "search_refinement_count" field.
func SearchRefinementCountNotIn(vs ...int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldSearchRefinementCount, vs...))
}

// SearchRefinementCountGT applies the GT predicate on the "search_refinement_count" field.
func SearchRefinementCountGT(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGT(FieldSearchRefinementCount, v))
}

// SearchRefinementCountGTE applies the GTE predicate on the "search_refinement_count" field.
func SearchRefinementCountGTE(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGTE(FieldSearchRefinementCount, v))
}

// SearchRefinementCountLT applies the LT predicate on the "search_refinement_count" field.
func SearchRefinementCountLT(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLT(FieldSearchRefinementCount, v))
}

// SearchRefinementCountLTE applies the LTE predicate on the "search_refinement_count" field.
func SearchRefinementCountLTE(v int) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLTE(FieldSearchRefinementCount, v))
}

// FlowQualityScoreEQ applies the EQ predicate on the "flow_quality_score" field.
func FlowQualityScoreEQ(v float64) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldFlowQualityScore, v))
}

// FlowQualityScoreNEQ applies the NEQ predicate on the "flow_quality_score" field.
func FlowQualityScoreNEQ(v float64) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldFlowQualityScore, v))
}

// FlowQualityScoreIn applies the In predicate on the "flow_quality_score" field.
func FlowQualityScoreIn(vs ...float64) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldFlowQualityScore, vs...))
}

// FlowQualityScoreNotIn applies the NotIn predicate on the "flow_quality_score" field.
func FlowQualityScoreNotIn(vs ...float64) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldFlowQualityScore, vs...))
}

// FlowQualityScoreGT applies the GT predicate on the "flow_quality_score" field.
func FlowQualityScoreGT(v float64) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGT(FieldFlowQualityScore, v))
}

// FlowQualityScoreGTE applies the GTE predicate on the "flow_quality_score" field.
func FlowQualityScoreGTE(v float64) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGTE(FieldFlowQualityScore, v))
}

// FlowQualityScoreLT applies the LT predicate on the "flow_quality_score" field.
func FlowQualityScoreLT(v float64) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLT(FieldFlowQualityScore, v))
}

// FlowQualityScoreLTE applies the LTE predicate on the "flow_quality_score" field.
func FlowQualityScoreLTE(v float64) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLTE(FieldFlowQualityScore, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryIsNil applies the IsNil predicate on the "summary" field.
func SummaryIsNil() predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIsNull(FieldSummary))
}

// SummaryNotNil applies the NotNil predicate on the "summary" field.
func SummaryNotNil() predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotNull(FieldSummary))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldContainsFold(FieldSummary, v))
}

// SessionStartedAtEQ applies the EQ predicate on the "session_started_at" field.
func SessionStartedAtEQ(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldSessionStartedAt, v))
}

// SessionStartedAtNEQ applies the NEQ predicate on the "session_started_at" field.
func SessionStartedAtNEQ(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldSessionStartedAt, v))
}

// SessionStartedAtIn applies the In predicate on the "session_started_at" field.
func SessionStartedAtIn(vs ...time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldSessionStartedAt, vs...))
}

// SessionStartedAtNotIn applies the NotIn predicate on the "session_started_at" field.
func SessionStartedAtNotIn(vs ...time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldSessionStartedAt, vs...))
}

// SessionStartedAtGT applies the GT predicate on the "session_started_at" field.
func SessionStartedAtGT(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGT(FieldSessionStartedAt, v))
}

// SessionStartedAtGTE applies the GTE predicate on the "session_started_at" field.
func SessionStartedAtGTE(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGTE(FieldSessionStartedAt, v))
}

// SessionStartedAtLT applies the LT predicate on the "session_started_at" field.
func SessionStartedAtLT(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLT(FieldSessionStartedAt, v))
}

// SessionStartedAtLTE applies the LTE predicate on the "session_started_at" field.
func SessionStartedAtLTE(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLTE(FieldSessionStartedAt, v))
}

// SessionEndedAtEQ applies the EQ predicate on the "session_ended_at" field.
func SessionEndedAtEQ(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldSessionEndedAt, v))
}

// SessionEndedAtNEQ applies the NEQ predicate on the "session_ended_at" field.
func SessionEndedAtNEQ(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldSessionEndedAt, v))
}

// SessionEndedAtIn applies the In predicate on the "session_ended_at" field.
func SessionEndedAtIn(vs ...time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldSessionEndedAt, vs...))
}

// SessionEndedAtNotIn applies the NotIn predicate on the "session_ended_at" field.
func SessionEndedAtNotIn(vs ...time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldSessionEndedAt, vs...))
}

// SessionEndedAtGT applies the GT predicate on the "session_ended_at" field.
func SessionEndedAtGT(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGT(FieldSessionEndedAt, v))
}

// SessionEndedAtGTE applies the GTE predicate on the "session_ended_at" field.
func SessionEndedAtGTE(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGTE(FieldSessionEndedAt, v))
}

// SessionEndedAtLT applies the LT predicate on the "session_ended_at" field.
func SessionEndedAtLT(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLT(FieldSessionEndedAt, v))
}

// SessionEndedAtLTE applies the LTE predicate on the "session_ended_at" field.
func SessionEndedAtLTE(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLTE(FieldSessionEndedAt, v))
}

// SessionEndedAtIsNil applies the IsNil predicate on the "session_ended_at" field.
func SessionEndedAtIsNil() predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIsNull(FieldSessionEndedAt))
}

// SessionEndedAtNotNil applies the NotNil predicate on the "session_ended_at" field.
func SessionEndedAtNotNil() predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotNull(FieldSessionEndedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSession applies the HasEdge predicate on the "session" edge.
func HasSession() predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, SessionTable, SessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionWith applies the HasEdge predicate on the "session" edge with a given conditions (other predicates).
func HasSessionWith(preds ...predicate.ChatSession) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(func(s *sql.Selector) {
		step := newSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ConversationAnalytics) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ConversationAnalytics) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ConversationAnalytics) predicate.ConversationAnalytics {
	return predicate.ConversationAnalytics(sql.NotPredicates(p))
}
