// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldGoogleID holds the string denoting the google_id field in the database.
	FieldGoogleID = "google_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAvatarURL holds the string denoting the avatar_url field in the database.
	FieldAvatarURL = "avatar_url"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldLastLogin holds the string denoting the last_login field in the database.
	FieldLastLogin = "last_login"
	// EdgeSessions holds the string denoting the sessions edge name in mutations.
	EdgeSessions = "sessions"
	// EdgeSearchHistory holds the string denoting the search_history edge name in mutations.
	EdgeSearchHistory = "search_history"
	// EdgePreferences holds the string denoting the preferences edge name in mutations.
	EdgePreferences = "preferences"
	// EdgeBehaviorProfile holds the string denoting the behavior_profile edge name in mutations.
	EdgeBehaviorProfile = "behavior_profile"
	// EdgeConversationAnalytics holds the string denoting the conversation_analytics edge name in mutations.
	EdgeConversationAnalytics = "conversation_analytics"
	// EdgeProductInteractions holds the string denoting the product_interactions edge name in mutations.
	EdgeProductInteractions = "product_interactions"
	// Table holds the table name of the user in the database.
	Table = "users"
	// SessionsTable is the table that holds the sessions relation/edge.
	SessionsTable = "chat_sessions"
	// SessionsInverseTable is the table name for the ChatSession entity.
	// It exists in this package in order to avoid circular dependency with the "chatsession" package.
	SessionsInverseTable = "chat_sessions"
	// SessionsColumn is the table column denoting the sessions relation/edge.
	SessionsColumn = "user_id"
	// SearchHistoryTable is the table that holds the search_history relation/edge.
	SearchHistoryTable = "search_histories"
	// SearchHistoryInverseTable is the table name for the SearchHistory entity.
	// It exists in this package in order to avoid circular dependency with the "searchhistory" package.
	SearchHistoryInverseTable = "search_histories"
	// SearchHistoryColumn is the table column denoting the search_history relation/edge.
	SearchHistoryColumn = "user_id"
	// PreferencesTable is the table that holds the preferences relation/edge.
	PreferencesTable = "user_preferences"
	// PreferencesInverseTable is the table name for the UserPreference entity.
	// It exists in this package in order to avoid circular dependency with the "userpreference" package.
	PreferencesInverseTable = "user_preferences"
	// PreferencesColumn is the table column denoting the preferences relation/edge.
	PreferencesColumn = "user_id"
	// BehaviorProfileTable is the table that holds the behavior_profile relation/edge.
	BehaviorProfileTable = "user_behavior_profiles"
	// BehaviorProfileInverseTable is the table name for the UserBehaviorProfile entity.
	// It exists in this package in order to avoid circular dependency with the "userbehaviorprofile" package.
	BehaviorProfileInverseTable = "user_behavior_profiles"
	// BehaviorProfileColumn is the table column denoting the behavior_profile relation/edge.
	BehaviorProfileColumn = "user_id"
	// ConversationAnalyticsTable is the table that holds the conversation_analytics relation/edge.
	ConversationAnalyticsTable = "conversation_analytics"
	// ConversationAnalyticsInverseTable is the table name for the ConversationAnalytics entity.
	// It exists in this package in order to avoid circular dependency with the "conversationanalytics" package.
	ConversationAnalyticsInverseTable = "conversation_analytics"
	// ConversationAnalyticsColumn is the table column denoting the conversation_analytics relation/edge.
	ConversationAnalyticsColumn = "user_id"
	// ProductInteractionsTable is the table that holds the product_interactions relation/edge.
	ProductInteractionsTable = "product_interactions"
	// ProductInteractionsInverseTable is the table name for the ProductInteraction entity.
	// It exists in this package in order to avoid circular dependency with the "productinteraction" package.
	ProductInteractionsInverseTable = "product_interactions"
	// ProductInteractionsColumn is the table column denoting the product_interactions relation/edge.
	ProductInteractionsColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldPasswordHash,
	FieldGoogleID,
	FieldName,
	FieldAvatarURL,
	FieldProvider,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldLastLogin,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// DefaultProvider holds the default value on creation for the "provider" field.
	DefaultProvider string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByGoogleID orders the results by the google_id field.
func ByGoogleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGoogleID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAvatarURL orders the results by the avatar_url field.
func ByAvatarURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatarURL, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByLastLogin orders the results by the last_login field.
func ByLastLogin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastLogin, opts...).ToFunc()
}

// BySessionsCount orders the results by sessions count.
func BySessionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSessionsStep(), opts...)
	}
}

// BySessions orders the results by sessions terms.
func BySessions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySearchHistoryCount orders the results by search_history count.
func BySearchHistoryCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSearchHistoryStep(), opts...)
	}
}

// BySearchHistory orders the results by search_history terms.
func BySearchHistory(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSearchHistoryStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPreferencesField orders the results by preferences field.
func ByPreferencesField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPreferencesStep(), sql.OrderByField(field, opts...))
	}
}

// ByBehaviorProfileField orders the results by behavior_profile field.
func ByBehaviorProfileField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBehaviorProfileStep(), sql.OrderByField(field, opts...))
	}
}

// ByConversationAnalyticsCount orders the results by conversation_analytics count.
func ByConversationAnalyticsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newConversationAnalyticsStep(), opts...)
	}
}

// ByConversationAnalytics orders the results by conversation_analytics terms.
func ByConversationAnalytics(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConversationAnalyticsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProductInteractionsCount orders the results by product_interactions count.
func ByProductInteractionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProductInteractionsStep(), opts...)
	}
}

// ByProductInteractions orders the results by product_interactions terms.
func ByProductInteractions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProductInteractionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSessionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
	)
}
func newSearchHistoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SearchHistoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SearchHistoryTable, SearchHistoryColumn),
	)
}
func newPreferencesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PreferencesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, PreferencesTable, PreferencesColumn),
	)
}
func newBehaviorProfileStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BehaviorProfileInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, BehaviorProfileTable, BehaviorProfileColumn),
	)
}
func newConversationAnalyticsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConversationAnalyticsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ConversationAnalyticsTable, ConversationAnalyticsColumn),
	)
}
func newProductInteractionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProductInteractionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProductInteractionsTable, ProductInteractionsColumn),
	)
}
