// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ChatSession is the predicate function for chatsession builders.
type ChatSession func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// SearchHistory is the predicate function for searchhistory builders.
type SearchHistory func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserPreference is the predicate function for userpreference builders.
type UserPreference func(*sql.Selector)
