-- migrations/012_add_conversation_analytics.sql
-- Analytics for each chat session to improve AI responses and track user satisfaction

-- Conversation analytics table
CREATE TABLE IF NOT EXISTS conversation_analytics (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    session_id UUID UNIQUE NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,

    -- Session metrics
    message_count INTEGER DEFAULT 0,
    user_message_count INTEGER DEFAULT 0,
    assistant_message_count INTEGER DEFAULT 0,
    search_count INTEGER DEFAULT 0,
    products_shown INTEGER DEFAULT 0,
    products_clicked INTEGER DEFAULT 0,

    -- Duration in seconds
    session_duration INTEGER DEFAULT 0,

    -- Key topics extracted from conversation (JSONB array: ["laptops", "gaming", "budget"])
    key_topics JSONB DEFAULT '[]'::jsonb,

    -- Categories explored during session (JSONB array: ["electronics", "computers"])
    categories_explored JSONB DEFAULT '[]'::jsonb,

    -- Sentiment analysis: "positive", "neutral", "negative", "mixed"
    overall_sentiment VARCHAR(20) DEFAULT 'neutral',

    -- Sentiment score (-1.0 to 1.0)
    sentiment_score DOUBLE PRECISION DEFAULT 0,

    -- Intent classification: "exploration", "purchase", "comparison", "information"
    primary_intent VARCHAR(50),

    -- Success indicators
    found_product BOOLEAN DEFAULT false,
    session_completed BOOLEAN DEFAULT false,
    user_satisfied BOOLEAN,

    -- Performance metrics
    avg_response_time INTEGER DEFAULT 0,
    clarification_count INTEGER DEFAULT 0,
    search_refinement_count INTEGER DEFAULT 0,

    -- Conversation flow quality (0-1 scale)
    flow_quality_score DOUBLE PRECISION DEFAULT 0,

    -- Extracted user preferences from this session
    extracted_preferences JSONB DEFAULT '{}'::jsonb,

    -- Price sensitivity indicators (JSONB array of mentioned prices)
    price_mentions JSONB DEFAULT '[]'::jsonb,

    -- Brand mentions during conversation
    brand_mentions JSONB DEFAULT '[]'::jsonb,

    -- Conversation summary (generated by AI)
    summary TEXT,

    -- Session timing
    session_started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    session_ended_at TIMESTAMP,

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE UNIQUE INDEX IF NOT EXISTS idx_conversation_analytics_session_id
    ON conversation_analytics(session_id);

CREATE INDEX IF NOT EXISTS idx_conversation_analytics_user_created
    ON conversation_analytics(user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_conversation_analytics_success
    ON conversation_analytics(user_id, found_product, user_satisfied);

CREATE INDEX IF NOT EXISTS idx_conversation_analytics_intent
    ON conversation_analytics(primary_intent, created_at);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_conversation_analytics_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update updated_at
CREATE TRIGGER trigger_conversation_analytics_updated_at
    BEFORE UPDATE ON conversation_analytics
    FOR EACH ROW
    EXECUTE FUNCTION update_conversation_analytics_updated_at();
