// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mylittleprice/ent/chatsession"
	"mylittleprice/ent/message"
	"mylittleprice/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ChatSessionCreate is the builder for creating a ChatSession entity.
type ChatSessionCreate struct {
	config
	mutation *ChatSessionMutation
	hooks    []Hook
}

// SetSessionID sets the "session_id" field.
func (_c *ChatSessionCreate) SetSessionID(v string) *ChatSessionCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ChatSessionCreate) SetUserID(v uuid.UUID) *ChatSessionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *ChatSessionCreate) SetNillableUserID(v *uuid.UUID) *ChatSessionCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetCountryCode sets the "country_code" field.
func (_c *ChatSessionCreate) SetCountryCode(v string) *ChatSessionCreate {
	_c.mutation.SetCountryCode(v)
	return _c
}

// SetNillableCountryCode sets the "country_code" field if the given value is not nil.
func (_c *ChatSessionCreate) SetNillableCountryCode(v *string) *ChatSessionCreate {
	if v != nil {
		_c.SetCountryCode(*v)
	}
	return _c
}

// SetLanguageCode sets the "language_code" field.
func (_c *ChatSessionCreate) SetLanguageCode(v string) *ChatSessionCreate {
	_c.mutation.SetLanguageCode(v)
	return _c
}

// SetNillableLanguageCode sets the "language_code" field if the given value is not nil.
func (_c *ChatSessionCreate) SetNillableLanguageCode(v *string) *ChatSessionCreate {
	if v != nil {
		_c.SetLanguageCode(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *ChatSessionCreate) SetCurrency(v string) *ChatSessionCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *ChatSessionCreate) SetNillableCurrency(v *string) *ChatSessionCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetMessageCount sets the "message_count" field.
func (_c *ChatSessionCreate) SetMessageCount(v int) *ChatSessionCreate {
	_c.mutation.SetMessageCount(v)
	return _c
}

// SetNillableMessageCount sets the "message_count" field if the given value is not nil.
func (_c *ChatSessionCreate) SetNillableMessageCount(v *int) *ChatSessionCreate {
	if v != nil {
		_c.SetMessageCount(*v)
	}
	return _c
}

// SetSearchState sets the "search_state" field.
func (_c *ChatSessionCreate) SetSearchState(v map[string]interface{}) *ChatSessionCreate {
	_c.mutation.SetSearchState(v)
	return _c
}

// SetCycleState sets the "cycle_state" field.
func (_c *ChatSessionCreate) SetCycleState(v map[string]interface{}) *ChatSessionCreate {
	_c.mutation.SetCycleState(v)
	return _c
}

// SetConversationContext sets the "conversation_context" field.
func (_c *ChatSessionCreate) SetConversationContext(v map[string]interface{}) *ChatSessionCreate {
	_c.mutation.SetConversationContext(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChatSessionCreate) SetCreatedAt(v time.Time) *ChatSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChatSessionCreate) SetNillableCreatedAt(v *time.Time) *ChatSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChatSessionCreate) SetUpdatedAt(v time.Time) *ChatSessionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChatSessionCreate) SetNillableUpdatedAt(v *time.Time) *ChatSessionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ChatSessionCreate) SetExpiresAt(v time.Time) *ChatSessionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *ChatSessionCreate) SetNillableExpiresAt(v *time.Time) *ChatSessionCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ChatSessionCreate) SetID(v uuid.UUID) *ChatSessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ChatSessionCreate) SetNillableID(v *uuid.UUID) *ChatSessionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ChatSessionCreate) SetUser(v *User) *ChatSessionCreate {
	return _c.SetUserID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_c *ChatSessionCreate) AddMessageIDs(ids ...uuid.UUID) *ChatSessionCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the Message entity.
func (_c *ChatSessionCreate) AddMessages(v ...*Message) *ChatSessionCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// Mutation returns the ChatSessionMutation object of the builder.
func (_c *ChatSessionCreate) Mutation() *ChatSessionMutation {
	return _c.mutation
}

// Save creates the ChatSession in the database.
func (_c *ChatSessionCreate) Save(ctx context.Context) (*ChatSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatSessionCreate) SaveX(ctx context.Context) *ChatSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatSessionCreate) defaults() {
	if _, ok := _c.mutation.CountryCode(); !ok {
		v := chatsession.DefaultCountryCode
		_c.mutation.SetCountryCode(v)
	}
	if _, ok := _c.mutation.LanguageCode(); !ok {
		v := chatsession.DefaultLanguageCode
		_c.mutation.SetLanguageCode(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := chatsession.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.MessageCount(); !ok {
		v := chatsession.DefaultMessageCount
		_c.mutation.SetMessageCount(v)
	}
	if _, ok := _c.mutation.SearchState(); !ok {
		v := chatsession.DefaultSearchState
		_c.mutation.SetSearchState(v)
	}
	if _, ok := _c.mutation.CycleState(); !ok {
		v := chatsession.DefaultCycleState
		_c.mutation.SetCycleState(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chatsession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := chatsession.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		v := chatsession.DefaultExpiresAt()
		_c.mutation.SetExpiresAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := chatsession.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatSessionCreate) check() error {
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "ChatSession.session_id"`)}
	}
	if v, ok := _c.mutation.SessionID(); ok {
		if err := chatsession.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "ChatSession.session_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CountryCode(); !ok {
		return &ValidationError{Name: "country_code", err: errors.New(`ent: missing required field "ChatSession.country_code"`)}
	}
	if _, ok := _c.mutation.LanguageCode(); !ok {
		return &ValidationError{Name: "language_code", err: errors.New(`ent: missing required field "ChatSession.language_code"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "ChatSession.currency"`)}
	}
	if _, ok := _c.mutation.MessageCount(); !ok {
		return &ValidationError{Name: "message_count", err: errors.New(`ent: missing required field "ChatSession.message_count"`)}
	}
	if _, ok := _c.mutation.SearchState(); !ok {
		return &ValidationError{Name: "search_state", err: errors.New(`ent: missing required field "ChatSession.search_state"`)}
	}
	if _, ok := _c.mutation.CycleState(); !ok {
		return &ValidationError{Name: "cycle_state", err: errors.New(`ent: missing required field "ChatSession.cycle_state"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChatSession.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ChatSession.updated_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "ChatSession.expires_at"`)}
	}
	return nil
}

func (_c *ChatSessionCreate) sqlSave(ctx context.Context) (*ChatSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatSessionCreate) createSpec() (*ChatSession, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chatsession.Table, sqlgraph.NewFieldSpec(chatsession.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(chatsession.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.CountryCode(); ok {
		_spec.SetField(chatsession.FieldCountryCode, field.TypeString, value)
		_node.CountryCode = value
	}
	if value, ok := _c.mutation.LanguageCode(); ok {
		_spec.SetField(chatsession.FieldLanguageCode, field.TypeString, value)
		_node.LanguageCode = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(chatsession.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.MessageCount(); ok {
		_spec.SetField(chatsession.FieldMessageCount, field.TypeInt, value)
		_node.MessageCount = value
	}
	if value, ok := _c.mutation.SearchState(); ok {
		_spec.SetField(chatsession.FieldSearchState, field.TypeJSON, value)
		_node.SearchState = value
	}
	if value, ok := _c.mutation.CycleState(); ok {
		_spec.SetField(chatsession.FieldCycleState, field.TypeJSON, value)
		_node.CycleState = value
	}
	if value, ok := _c.mutation.ConversationContext(); ok {
		_spec.SetField(chatsession.FieldConversationContext, field.TypeJSON, value)
		_node.ConversationContext = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chatsession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(chatsession.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(chatsession.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatsession.UserTable,
			Columns: []string{chatsession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatsession.MessagesTable,
			Columns: []string{chatsession.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChatSessionCreateBulk is the builder for creating many ChatSession entities in bulk.
type ChatSessionCreateBulk struct {
	config
	err      error
	builders []*ChatSessionCreate
}

// Save creates the ChatSession entities in the database.
func (_c *ChatSessionCreateBulk) Save(ctx context.Context) ([]*ChatSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChatSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatSessionCreateBulk) SaveX(ctx context.Context) []*ChatSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
