// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mylittleprice/ent/chatsession"
	"mylittleprice/ent/message"
	"mylittleprice/ent/predicate"
	"mylittleprice/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ChatSessionUpdate is the builder for updating ChatSession entities.
type ChatSessionUpdate struct {
	config
	hooks    []Hook
	mutation *ChatSessionMutation
}

// Where appends a list predicates to the ChatSessionUpdate builder.
func (_u *ChatSessionUpdate) Where(ps ...predicate.ChatSession) *ChatSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *ChatSessionUpdate) SetSessionID(v string) *ChatSessionUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *ChatSessionUpdate) SetNillableSessionID(v *string) *ChatSessionUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChatSessionUpdate) SetUserID(v uuid.UUID) *ChatSessionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChatSessionUpdate) SetNillableUserID(v *uuid.UUID) *ChatSessionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ChatSessionUpdate) ClearUserID() *ChatSessionUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetCountryCode sets the "country_code" field.
func (_u *ChatSessionUpdate) SetCountryCode(v string) *ChatSessionUpdate {
	_u.mutation.SetCountryCode(v)
	return _u
}

// SetNillableCountryCode sets the "country_code" field if the given value is not nil.
func (_u *ChatSessionUpdate) SetNillableCountryCode(v *string) *ChatSessionUpdate {
	if v != nil {
		_u.SetCountryCode(*v)
	}
	return _u
}

// SetLanguageCode sets the "language_code" field.
func (_u *ChatSessionUpdate) SetLanguageCode(v string) *ChatSessionUpdate {
	_u.mutation.SetLanguageCode(v)
	return _u
}

// SetNillableLanguageCode sets the "language_code" field if the given value is not nil.
func (_u *ChatSessionUpdate) SetNillableLanguageCode(v *string) *ChatSessionUpdate {
	if v != nil {
		_u.SetLanguageCode(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *ChatSessionUpdate) SetCurrency(v string) *ChatSessionUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *ChatSessionUpdate) SetNillableCurrency(v *string) *ChatSessionUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetMessageCount sets the "message_count" field.
func (_u *ChatSessionUpdate) SetMessageCount(v int) *ChatSessionUpdate {
	_u.mutation.ResetMessageCount()
	_u.mutation.SetMessageCount(v)
	return _u
}

// SetNillableMessageCount sets the "message_count" field if the given value is not nil.
func (_u *ChatSessionUpdate) SetNillableMessageCount(v *int) *ChatSessionUpdate {
	if v != nil {
		_u.SetMessageCount(*v)
	}
	return _u
}

// AddMessageCount adds value to the "message_count" field.
func (_u *ChatSessionUpdate) AddMessageCount(v int) *ChatSessionUpdate {
	_u.mutation.AddMessageCount(v)
	return _u
}

// SetSearchState sets the "search_state" field.
func (_u *ChatSessionUpdate) SetSearchState(v map[string]interface{}) *ChatSessionUpdate {
	_u.mutation.SetSearchState(v)
	return _u
}

// SetCycleState sets the "cycle_state" field.
func (_u *ChatSessionUpdate) SetCycleState(v map[string]interface{}) *ChatSessionUpdate {
	_u.mutation.SetCycleState(v)
	return _u
}

// SetConversationContext sets the "conversation_context" field.
func (_u *ChatSessionUpdate) SetConversationContext(v map[string]interface{}) *ChatSessionUpdate {
	_u.mutation.SetConversationContext(v)
	return _u
}

// ClearConversationContext clears the value of the "conversation_context" field.
func (_u *ChatSessionUpdate) ClearConversationContext() *ChatSessionUpdate {
	_u.mutation.ClearConversationContext()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChatSessionUpdate) SetUpdatedAt(v time.Time) *ChatSessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ChatSessionUpdate) SetExpiresAt(v time.Time) *ChatSessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ChatSessionUpdate) SetNillableExpiresAt(v *time.Time) *ChatSessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ChatSessionUpdate) SetUser(v *User) *ChatSessionUpdate {
	return _u.SetUserID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_u *ChatSessionUpdate) AddMessageIDs(ids ...uuid.UUID) *ChatSessionUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the Message entity.
func (_u *ChatSessionUpdate) AddMessages(v ...*Message) *ChatSessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the ChatSessionMutation object of the builder.
func (_u *ChatSessionUpdate) Mutation() *ChatSessionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ChatSessionUpdate) ClearUser() *ChatSessionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearMessages clears all "messages" edges to the Message entity.
func (_u *ChatSessionUpdate) ClearMessages() *ChatSessionUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (_u *ChatSessionUpdate) RemoveMessageIDs(ids ...uuid.UUID) *ChatSessionUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to Message entities.
func (_u *ChatSessionUpdate) RemoveMessages(v ...*Message) *ChatSessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChatSessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChatSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatSessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chatsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatSessionUpdate) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := chatsession.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "ChatSession.session_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ChatSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatsession.Table, chatsession.Columns, sqlgraph.NewFieldSpec(chatsession.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(chatsession.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CountryCode(); ok {
		_spec.SetField(chatsession.FieldCountryCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.LanguageCode(); ok {
		_spec.SetField(chatsession.FieldLanguageCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(chatsession.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageCount(); ok {
		_spec.SetField(chatsession.FieldMessageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessageCount(); ok {
		_spec.AddField(chatsession.FieldMessageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SearchState(); ok {
		_spec.SetField(chatsession.FieldSearchState, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CycleState(); ok {
		_spec.SetField(chatsession.FieldCycleState, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ConversationContext(); ok {
		_spec.SetField(chatsession.FieldConversationContext, field.TypeJSON, value)
	}
	if _u.mutation.ConversationContextCleared() {
		_spec.ClearField(chatsession.FieldConversationContext, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chatsession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(chatsession.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatsession.UserTable,
			Columns: []string{chatsession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatsession.UserTable,
			Columns: []string{chatsession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatsession.MessagesTable,
			Columns: []string{chatsession.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatsession.MessagesTable,
			Columns: []string{chatsession.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatsession.MessagesTable,
			Columns: []string{chatsession.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChatSessionUpdateOne is the builder for updating a single ChatSession entity.
type ChatSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatSessionMutation
}

// SetSessionID sets the "session_id" field.
func (_u *ChatSessionUpdateOne) SetSessionID(v string) *ChatSessionUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *ChatSessionUpdateOne) SetNillableSessionID(v *string) *ChatSessionUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChatSessionUpdateOne) SetUserID(v uuid.UUID) *ChatSessionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChatSessionUpdateOne) SetNillableUserID(v *uuid.UUID) *ChatSessionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ChatSessionUpdateOne) ClearUserID() *ChatSessionUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetCountryCode sets the "country_code" field.
func (_u *ChatSessionUpdateOne) SetCountryCode(v string) *ChatSessionUpdateOne {
	_u.mutation.SetCountryCode(v)
	return _u
}

// SetNillableCountryCode sets the "country_code" field if the given value is not nil.
func (_u *ChatSessionUpdateOne) SetNillableCountryCode(v *string) *ChatSessionUpdateOne {
	if v != nil {
		_u.SetCountryCode(*v)
	}
	return _u
}

// SetLanguageCode sets the "language_code" field.
func (_u *ChatSessionUpdateOne) SetLanguageCode(v string) *ChatSessionUpdateOne {
	_u.mutation.SetLanguageCode(v)
	return _u
}

// SetNillableLanguageCode sets the "language_code" field if the given value is not nil.
func (_u *ChatSessionUpdateOne) SetNillableLanguageCode(v *string) *ChatSessionUpdateOne {
	if v != nil {
		_u.SetLanguageCode(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *ChatSessionUpdateOne) SetCurrency(v string) *ChatSessionUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *ChatSessionUpdateOne) SetNillableCurrency(v *string) *ChatSessionUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetMessageCount sets the "message_count" field.
func (_u *ChatSessionUpdateOne) SetMessageCount(v int) *ChatSessionUpdateOne {
	_u.mutation.ResetMessageCount()
	_u.mutation.SetMessageCount(v)
	return _u
}

// SetNillableMessageCount sets the "message_count" field if the given value is not nil.
func (_u *ChatSessionUpdateOne) SetNillableMessageCount(v *int) *ChatSessionUpdateOne {
	if v != nil {
		_u.SetMessageCount(*v)
	}
	return _u
}

// AddMessageCount adds value to the "message_count" field.
func (_u *ChatSessionUpdateOne) AddMessageCount(v int) *ChatSessionUpdateOne {
	_u.mutation.AddMessageCount(v)
	return _u
}

// SetSearchState sets the "search_state" field.
func (_u *ChatSessionUpdateOne) SetSearchState(v map[string]interface{}) *ChatSessionUpdateOne {
	_u.mutation.SetSearchState(v)
	return _u
}

// SetCycleState sets the "cycle_state" field.
func (_u *ChatSessionUpdateOne) SetCycleState(v map[string]interface{}) *ChatSessionUpdateOne {
	_u.mutation.SetCycleState(v)
	return _u
}

// SetConversationContext sets the "conversation_context" field.
func (_u *ChatSessionUpdateOne) SetConversationContext(v map[string]interface{}) *ChatSessionUpdateOne {
	_u.mutation.SetConversationContext(v)
	return _u
}

// ClearConversationContext clears the value of the "conversation_context" field.
func (_u *ChatSessionUpdateOne) ClearConversationContext() *ChatSessionUpdateOne {
	_u.mutation.ClearConversationContext()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChatSessionUpdateOne) SetUpdatedAt(v time.Time) *ChatSessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ChatSessionUpdateOne) SetExpiresAt(v time.Time) *ChatSessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ChatSessionUpdateOne) SetNillableExpiresAt(v *time.Time) *ChatSessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ChatSessionUpdateOne) SetUser(v *User) *ChatSessionUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_u *ChatSessionUpdateOne) AddMessageIDs(ids ...uuid.UUID) *ChatSessionUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the Message entity.
func (_u *ChatSessionUpdateOne) AddMessages(v ...*Message) *ChatSessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the ChatSessionMutation object of the builder.
func (_u *ChatSessionUpdateOne) Mutation() *ChatSessionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ChatSessionUpdateOne) ClearUser() *ChatSessionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearMessages clears all "messages" edges to the Message entity.
func (_u *ChatSessionUpdateOne) ClearMessages() *ChatSessionUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (_u *ChatSessionUpdateOne) RemoveMessageIDs(ids ...uuid.UUID) *ChatSessionUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to Message entities.
func (_u *ChatSessionUpdateOne) RemoveMessages(v ...*Message) *ChatSessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the ChatSessionUpdate builder.
func (_u *ChatSessionUpdateOne) Where(ps ...predicate.ChatSession) *ChatSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChatSessionUpdateOne) Select(field string, fields ...string) *ChatSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChatSession entity.
func (_u *ChatSessionUpdateOne) Save(ctx context.Context) (*ChatSession, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatSessionUpdateOne) SaveX(ctx context.Context) *ChatSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChatSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatSessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chatsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatSessionUpdateOne) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := chatsession.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "ChatSession.session_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ChatSessionUpdateOne) sqlSave(ctx context.Context) (_node *ChatSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatsession.Table, chatsession.Columns, sqlgraph.NewFieldSpec(chatsession.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChatSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatsession.FieldID)
		for _, f := range fields {
			if !chatsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chatsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(chatsession.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CountryCode(); ok {
		_spec.SetField(chatsession.FieldCountryCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.LanguageCode(); ok {
		_spec.SetField(chatsession.FieldLanguageCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(chatsession.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageCount(); ok {
		_spec.SetField(chatsession.FieldMessageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessageCount(); ok {
		_spec.AddField(chatsession.FieldMessageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SearchState(); ok {
		_spec.SetField(chatsession.FieldSearchState, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CycleState(); ok {
		_spec.SetField(chatsession.FieldCycleState, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ConversationContext(); ok {
		_spec.SetField(chatsession.FieldConversationContext, field.TypeJSON, value)
	}
	if _u.mutation.ConversationContextCleared() {
		_spec.ClearField(chatsession.FieldConversationContext, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chatsession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(chatsession.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatsession.UserTable,
			Columns: []string{chatsession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatsession.UserTable,
			Columns: []string{chatsession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatsession.MessagesTable,
			Columns: []string{chatsession.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatsession.MessagesTable,
			Columns: []string{chatsession.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatsession.MessagesTable,
			Columns: []string{chatsession.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChatSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
