// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"mylittleprice/ent/chatsession"
	"mylittleprice/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ChatSession is the model entity for the ChatSession schema.
type ChatSession struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// CountryCode holds the value of the "country_code" field.
	CountryCode string `json:"country_code,omitempty"`
	// LanguageCode holds the value of the "language_code" field.
	LanguageCode string `json:"language_code,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// MessageCount holds the value of the "message_count" field.
	MessageCount int `json:"message_count,omitempty"`
	// SearchState holds the value of the "search_state" field.
	SearchState map[string]interface{} `json:"search_state,omitempty"`
	// CycleState holds the value of the "cycle_state" field.
	CycleState map[string]interface{} `json:"cycle_state,omitempty"`
	// ConversationContext holds the value of the "conversation_context" field.
	ConversationContext map[string]interface{} `json:"conversation_context,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChatSessionQuery when eager-loading is set.
	Edges        ChatSessionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChatSessionEdges holds the relations/edges for other nodes in the graph.
type ChatSessionEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Messages holds the value of the messages edge.
	Messages []*Message `json:"messages,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChatSessionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// MessagesOrErr returns the Messages value or an error if the edge
// was not loaded in eager-loading.
func (e ChatSessionEdges) MessagesOrErr() ([]*Message, error) {
	if e.loadedTypes[1] {
		return e.Messages, nil
	}
	return nil, &NotLoadedError{edge: "messages"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChatSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chatsession.FieldSearchState, chatsession.FieldCycleState, chatsession.FieldConversationContext:
			values[i] = new([]byte)
		case chatsession.FieldMessageCount:
			values[i] = new(sql.NullInt64)
		case chatsession.FieldSessionID, chatsession.FieldCountryCode, chatsession.FieldLanguageCode, chatsession.FieldCurrency:
			values[i] = new(sql.NullString)
		case chatsession.FieldCreatedAt, chatsession.FieldUpdatedAt, chatsession.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		case chatsession.FieldID, chatsession.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChatSession fields.
func (_m *ChatSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chatsession.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case chatsession.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case chatsession.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case chatsession.FieldCountryCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country_code", values[i])
			} else if value.Valid {
				_m.CountryCode = value.String
			}
		case chatsession.FieldLanguageCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language_code", values[i])
			} else if value.Valid {
				_m.LanguageCode = value.String
			}
		case chatsession.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case chatsession.FieldMessageCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field message_count", values[i])
			} else if value.Valid {
				_m.MessageCount = int(value.Int64)
			}
		case chatsession.FieldSearchState:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field search_state", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SearchState); err != nil {
					return fmt.Errorf("unmarshal field search_state: %w", err)
				}
			}
		case chatsession.FieldCycleState:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field cycle_state", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.CycleState); err != nil {
					return fmt.Errorf("unmarshal field cycle_state: %w", err)
				}
			}
		case chatsession.FieldConversationContext:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field conversation_context", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ConversationContext); err != nil {
					return fmt.Errorf("unmarshal field conversation_context: %w", err)
				}
			}
		case chatsession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case chatsession.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case chatsession.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChatSession.
// This includes values selected through modifiers, order, etc.
func (_m *ChatSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ChatSession entity.
func (_m *ChatSession) QueryUser() *UserQuery {
	return NewChatSessionClient(_m.config).QueryUser(_m)
}

// QueryMessages queries the "messages" edge of the ChatSession entity.
func (_m *ChatSession) QueryMessages() *MessageQuery {
	return NewChatSessionClient(_m.config).QueryMessages(_m)
}

// Update returns a builder for updating this ChatSession.
// Note that you need to call ChatSession.Unwrap() before calling this method if this ChatSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChatSession) Update() *ChatSessionUpdateOne {
	return NewChatSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChatSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChatSession) Unwrap() *ChatSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChatSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChatSession) String() string {
	var builder strings.Builder
	builder.WriteString("ChatSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("country_code=")
	builder.WriteString(_m.CountryCode)
	builder.WriteString(", ")
	builder.WriteString("language_code=")
	builder.WriteString(_m.LanguageCode)
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("message_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.MessageCount))
	builder.WriteString(", ")
	builder.WriteString("search_state=")
	builder.WriteString(fmt.Sprintf("%v", _m.SearchState))
	builder.WriteString(", ")
	builder.WriteString("cycle_state=")
	builder.WriteString(fmt.Sprintf("%v", _m.CycleState))
	builder.WriteString(", ")
	builder.WriteString("conversation_context=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConversationContext))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChatSessions is a parsable slice of ChatSession.
type ChatSessions []*ChatSession
