// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mylittleprice/ent/chatsession"
	"mylittleprice/ent/conversationanalytics"
	"mylittleprice/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ConversationAnalyticsCreate is the builder for creating a ConversationAnalytics entity.
type ConversationAnalyticsCreate struct {
	config
	mutation *ConversationAnalyticsMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *ConversationAnalyticsCreate) SetUserID(v uuid.UUID) *ConversationAnalyticsCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableUserID(v *uuid.UUID) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *ConversationAnalyticsCreate) SetSessionID(v uuid.UUID) *ConversationAnalyticsCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetMessageCount sets the "message_count" field.
func (_c *ConversationAnalyticsCreate) SetMessageCount(v int) *ConversationAnalyticsCreate {
	_c.mutation.SetMessageCount(v)
	return _c
}

// SetNillableMessageCount sets the "message_count" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableMessageCount(v *int) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetMessageCount(*v)
	}
	return _c
}

// SetUserMessageCount sets the "user_message_count" field.
func (_c *ConversationAnalyticsCreate) SetUserMessageCount(v int) *ConversationAnalyticsCreate {
	_c.mutation.SetUserMessageCount(v)
	return _c
}

// SetNillableUserMessageCount sets the "user_message_count" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableUserMessageCount(v *int) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetUserMessageCount(*v)
	}
	return _c
}

// SetAssistantMessageCount sets the "assistant_message_count" field.
func (_c *ConversationAnalyticsCreate) SetAssistantMessageCount(v int) *ConversationAnalyticsCreate {
	_c.mutation.SetAssistantMessageCount(v)
	return _c
}

// SetNillableAssistantMessageCount sets the "assistant_message_count" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableAssistantMessageCount(v *int) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetAssistantMessageCount(*v)
	}
	return _c
}

// SetSearchCount sets the "search_count" field.
func (_c *ConversationAnalyticsCreate) SetSearchCount(v int) *ConversationAnalyticsCreate {
	_c.mutation.SetSearchCount(v)
	return _c
}

// SetNillableSearchCount sets the "search_count" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableSearchCount(v *int) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetSearchCount(*v)
	}
	return _c
}

// SetProductsShown sets the "products_shown" field.
func (_c *ConversationAnalyticsCreate) SetProductsShown(v int) *ConversationAnalyticsCreate {
	_c.mutation.SetProductsShown(v)
	return _c
}

// SetNillableProductsShown sets the "products_shown" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableProductsShown(v *int) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetProductsShown(*v)
	}
	return _c
}

// SetProductsClicked sets the "products_clicked" field.
func (_c *ConversationAnalyticsCreate) SetProductsClicked(v int) *ConversationAnalyticsCreate {
	_c.mutation.SetProductsClicked(v)
	return _c
}

// SetNillableProductsClicked sets the "products_clicked" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableProductsClicked(v *int) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetProductsClicked(*v)
	}
	return _c
}

// SetSessionDuration sets the "session_duration" field.
func (_c *ConversationAnalyticsCreate) SetSessionDuration(v int) *ConversationAnalyticsCreate {
	_c.mutation.SetSessionDuration(v)
	return _c
}

// SetNillableSessionDuration sets the "session_duration" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableSessionDuration(v *int) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetSessionDuration(*v)
	}
	return _c
}

// SetKeyTopics sets the "key_topics" field.
func (_c *ConversationAnalyticsCreate) SetKeyTopics(v []string) *ConversationAnalyticsCreate {
	_c.mutation.SetKeyTopics(v)
	return _c
}

// SetCategoriesExplored sets the "categories_explored" field.
func (_c *ConversationAnalyticsCreate) SetCategoriesExplored(v []string) *ConversationAnalyticsCreate {
	_c.mutation.SetCategoriesExplored(v)
	return _c
}

// SetOverallSentiment sets the "overall_sentiment" field.
func (_c *ConversationAnalyticsCreate) SetOverallSentiment(v string) *ConversationAnalyticsCreate {
	_c.mutation.SetOverallSentiment(v)
	return _c
}

// SetNillableOverallSentiment sets the "overall_sentiment" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableOverallSentiment(v *string) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetOverallSentiment(*v)
	}
	return _c
}

// SetSentimentScore sets the "sentiment_score" field.
func (_c *ConversationAnalyticsCreate) SetSentimentScore(v float64) *ConversationAnalyticsCreate {
	_c.mutation.SetSentimentScore(v)
	return _c
}

// SetNillableSentimentScore sets the "sentiment_score" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableSentimentScore(v *float64) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetSentimentScore(*v)
	}
	return _c
}

// SetPrimaryIntent sets the "primary_intent" field.
func (_c *ConversationAnalyticsCreate) SetPrimaryIntent(v string) *ConversationAnalyticsCreate {
	_c.mutation.SetPrimaryIntent(v)
	return _c
}

// SetNillablePrimaryIntent sets the "primary_intent" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillablePrimaryIntent(v *string) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetPrimaryIntent(*v)
	}
	return _c
}

// SetFoundProduct sets the "found_product" field.
func (_c *ConversationAnalyticsCreate) SetFoundProduct(v bool) *ConversationAnalyticsCreate {
	_c.mutation.SetFoundProduct(v)
	return _c
}

// SetNillableFoundProduct sets the "found_product" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableFoundProduct(v *bool) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetFoundProduct(*v)
	}
	return _c
}

// SetSessionCompleted sets the "session_completed" field.
func (_c *ConversationAnalyticsCreate) SetSessionCompleted(v bool) *ConversationAnalyticsCreate {
	_c.mutation.SetSessionCompleted(v)
	return _c
}

// SetNillableSessionCompleted sets the "session_completed" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableSessionCompleted(v *bool) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetSessionCompleted(*v)
	}
	return _c
}

// SetUserSatisfied sets the "user_satisfied" field.
func (_c *ConversationAnalyticsCreate) SetUserSatisfied(v bool) *ConversationAnalyticsCreate {
	_c.mutation.SetUserSatisfied(v)
	return _c
}

// SetNillableUserSatisfied sets the "user_satisfied" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableUserSatisfied(v *bool) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetUserSatisfied(*v)
	}
	return _c
}

// SetAvgResponseTime sets the "avg_response_time" field.
func (_c *ConversationAnalyticsCreate) SetAvgResponseTime(v int) *ConversationAnalyticsCreate {
	_c.mutation.SetAvgResponseTime(v)
	return _c
}

// SetNillableAvgResponseTime sets the "avg_response_time" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableAvgResponseTime(v *int) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetAvgResponseTime(*v)
	}
	return _c
}

// SetClarificationCount sets the "clarification_count" field.
func (_c *ConversationAnalyticsCreate) SetClarificationCount(v int) *ConversationAnalyticsCreate {
	_c.mutation.SetClarificationCount(v)
	return _c
}

// SetNillableClarificationCount sets the "clarification_count" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableClarificationCount(v *int) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetClarificationCount(*v)
	}
	return _c
}

// SetSearchRefinementCount sets the "search_refinement_count" field.
func (_c *ConversationAnalyticsCreate) SetSearchRefinementCount(v int) *ConversationAnalyticsCreate {
	_c.mutation.SetSearchRefinementCount(v)
	return _c
}

// SetNillableSearchRefinementCount sets the "search_refinement_count" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableSearchRefinementCount(v *int) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetSearchRefinementCount(*v)
	}
	return _c
}

// SetFlowQualityScore sets the "flow_quality_score" field.
func (_c *ConversationAnalyticsCreate) SetFlowQualityScore(v float64) *ConversationAnalyticsCreate {
	_c.mutation.SetFlowQualityScore(v)
	return _c
}

// SetNillableFlowQualityScore sets the "flow_quality_score" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableFlowQualityScore(v *float64) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetFlowQualityScore(*v)
	}
	return _c
}

// SetExtractedPreferences sets the "extracted_preferences" field.
func (_c *ConversationAnalyticsCreate) SetExtractedPreferences(v map[string]interface{}) *ConversationAnalyticsCreate {
	_c.mutation.SetExtractedPreferences(v)
	return _c
}

// SetPriceMentions sets the "price_mentions" field.
func (_c *ConversationAnalyticsCreate) SetPriceMentions(v []float64) *ConversationAnalyticsCreate {
	_c.mutation.SetPriceMentions(v)
	return _c
}

// SetBrandMentions sets the "brand_mentions" field.
func (_c *ConversationAnalyticsCreate) SetBrandMentions(v []string) *ConversationAnalyticsCreate {
	_c.mutation.SetBrandMentions(v)
	return _c
}

// SetSummary sets the "summary" field.
func (_c *ConversationAnalyticsCreate) SetSummary(v string) *ConversationAnalyticsCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableSummary(v *string) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetSessionStartedAt sets the "session_started_at" field.
func (_c *ConversationAnalyticsCreate) SetSessionStartedAt(v time.Time) *ConversationAnalyticsCreate {
	_c.mutation.SetSessionStartedAt(v)
	return _c
}

// SetNillableSessionStartedAt sets the "session_started_at" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableSessionStartedAt(v *time.Time) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetSessionStartedAt(*v)
	}
	return _c
}

// SetSessionEndedAt sets the "session_ended_at" field.
func (_c *ConversationAnalyticsCreate) SetSessionEndedAt(v time.Time) *ConversationAnalyticsCreate {
	_c.mutation.SetSessionEndedAt(v)
	return _c
}

// SetNillableSessionEndedAt sets the "session_ended_at" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableSessionEndedAt(v *time.Time) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetSessionEndedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ConversationAnalyticsCreate) SetCreatedAt(v time.Time) *ConversationAnalyticsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableCreatedAt(v *time.Time) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ConversationAnalyticsCreate) SetUpdatedAt(v time.Time) *ConversationAnalyticsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableUpdatedAt(v *time.Time) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ConversationAnalyticsCreate) SetID(v uuid.UUID) *ConversationAnalyticsCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ConversationAnalyticsCreate) SetNillableID(v *uuid.UUID) *ConversationAnalyticsCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ConversationAnalyticsCreate) SetUser(v *User) *ConversationAnalyticsCreate {
	return _c.SetUserID(v.ID)
}

// SetSession sets the "session" edge to the ChatSession entity.
func (_c *ConversationAnalyticsCreate) SetSession(v *ChatSession) *ConversationAnalyticsCreate {
	return _c.SetSessionID(v.ID)
}

// Mutation returns the ConversationAnalyticsMutation object of the builder.
func (_c *ConversationAnalyticsCreate) Mutation() *ConversationAnalyticsMutation {
	return _c.mutation
}

// Save creates the ConversationAnalytics in the database.
func (_c *ConversationAnalyticsCreate) Save(ctx context.Context) (*ConversationAnalytics, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConversationAnalyticsCreate) SaveX(ctx context.Context) *ConversationAnalytics {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationAnalyticsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationAnalyticsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConversationAnalyticsCreate) defaults() {
	if _, ok := _c.mutation.MessageCount(); !ok {
		v := conversationanalytics.DefaultMessageCount
		_c.mutation.SetMessageCount(v)
	}
	if _, ok := _c.mutation.UserMessageCount(); !ok {
		v := conversationanalytics.DefaultUserMessageCount
		_c.mutation.SetUserMessageCount(v)
	}
	if _, ok := _c.mutation.AssistantMessageCount(); !ok {
		v := conversationanalytics.DefaultAssistantMessageCount
		_c.mutation.SetAssistantMessageCount(v)
	}
	if _, ok := _c.mutation.SearchCount(); !ok {
		v := conversationanalytics.DefaultSearchCount
		_c.mutation.SetSearchCount(v)
	}
	if _, ok := _c.mutation.ProductsShown(); !ok {
		v := conversationanalytics.DefaultProductsShown
		_c.mutation.SetProductsShown(v)
	}
	if _, ok := _c.mutation.ProductsClicked(); !ok {
		v := conversationanalytics.DefaultProductsClicked
		_c.mutation.SetProductsClicked(v)
	}
	if _, ok := _c.mutation.SessionDuration(); !ok {
		v := conversationanalytics.DefaultSessionDuration
		_c.mutation.SetSessionDuration(v)
	}
	if _, ok := _c.mutation.KeyTopics(); !ok {
		v := conversationanalytics.DefaultKeyTopics
		_c.mutation.SetKeyTopics(v)
	}
	if _, ok := _c.mutation.CategoriesExplored(); !ok {
		v := conversationanalytics.DefaultCategoriesExplored
		_c.mutation.SetCategoriesExplored(v)
	}
	if _, ok := _c.mutation.OverallSentiment(); !ok {
		v := conversationanalytics.DefaultOverallSentiment
		_c.mutation.SetOverallSentiment(v)
	}
	if _, ok := _c.mutation.SentimentScore(); !ok {
		v := conversationanalytics.DefaultSentimentScore
		_c.mutation.SetSentimentScore(v)
	}
	if _, ok := _c.mutation.FoundProduct(); !ok {
		v := conversationanalytics.DefaultFoundProduct
		_c.mutation.SetFoundProduct(v)
	}
	if _, ok := _c.mutation.SessionCompleted(); !ok {
		v := conversationanalytics.DefaultSessionCompleted
		_c.mutation.SetSessionCompleted(v)
	}
	if _, ok := _c.mutation.AvgResponseTime(); !ok {
		v := conversationanalytics.DefaultAvgResponseTime
		_c.mutation.SetAvgResponseTime(v)
	}
	if _, ok := _c.mutation.ClarificationCount(); !ok {
		v := conversationanalytics.DefaultClarificationCount
		_c.mutation.SetClarificationCount(v)
	}
	if _, ok := _c.mutation.SearchRefinementCount(); !ok {
		v := conversationanalytics.DefaultSearchRefinementCount
		_c.mutation.SetSearchRefinementCount(v)
	}
	if _, ok := _c.mutation.FlowQualityScore(); !ok {
		v := conversationanalytics.DefaultFlowQualityScore
		_c.mutation.SetFlowQualityScore(v)
	}
	if _, ok := _c.mutation.ExtractedPreferences(); !ok {
		v := conversationanalytics.DefaultExtractedPreferences
		_c.mutation.SetExtractedPreferences(v)
	}
	if _, ok := _c.mutation.PriceMentions(); !ok {
		v := conversationanalytics.DefaultPriceMentions
		_c.mutation.SetPriceMentions(v)
	}
	if _, ok := _c.mutation.BrandMentions(); !ok {
		v := conversationanalytics.DefaultBrandMentions
		_c.mutation.SetBrandMentions(v)
	}
	if _, ok := _c.mutation.SessionStartedAt(); !ok {
		v := conversationanalytics.DefaultSessionStartedAt()
		_c.mutation.SetSessionStartedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := conversationanalytics.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := conversationanalytics.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := conversationanalytics.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConversationAnalyticsCreate) check() error {
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "ConversationAnalytics.session_id"`)}
	}
	if _, ok := _c.mutation.MessageCount(); !ok {
		return &ValidationError{Name: "message_count", err: errors.New(`ent: missing required field "ConversationAnalytics.message_count"`)}
	}
	if _, ok := _c.mutation.UserMessageCount(); !ok {
		return &ValidationError{Name: "user_message_count", err: errors.New(`ent: missing required field "ConversationAnalytics.user_message_count"`)}
	}
	if _, ok := _c.mutation.AssistantMessageCount(); !ok {
		return &ValidationError{Name: "assistant_message_count", err: errors.New(`ent: missing required field "ConversationAnalytics.assistant_message_count"`)}
	}
	if _, ok := _c.mutation.SearchCount(); !ok {
		return &ValidationError{Name: "search_count", err: errors.New(`ent: missing required field "ConversationAnalytics.search_count"`)}
	}
	if _, ok := _c.mutation.ProductsShown(); !ok {
		return &ValidationError{Name: "products_shown", err: errors.New(`ent: missing required field "ConversationAnalytics.products_shown"`)}
	}
	if _, ok := _c.mutation.ProductsClicked(); !ok {
		return &ValidationError{Name: "products_clicked", err: errors.New(`ent: missing required field "ConversationAnalytics.products_clicked"`)}
	}
	if _, ok := _c.mutation.SessionDuration(); !ok {
		return &ValidationError{Name: "session_duration", err: errors.New(`ent: missing required field "ConversationAnalytics.session_duration"`)}
	}
	if _, ok := _c.mutation.KeyTopics(); !ok {
		return &ValidationError{Name: "key_topics", err: errors.New(`ent: missing required field "ConversationAnalytics.key_topics"`)}
	}
	if _, ok := _c.mutation.CategoriesExplored(); !ok {
		return &ValidationError{Name: "categories_explored", err: errors.New(`ent: missing required field "ConversationAnalytics.categories_explored"`)}
	}
	if _, ok := _c.mutation.OverallSentiment(); !ok {
		return &ValidationError{Name: "overall_sentiment", err: errors.New(`ent: missing required field "ConversationAnalytics.overall_sentiment"`)}
	}
	if _, ok := _c.mutation.SentimentScore(); !ok {
		return &ValidationError{Name: "sentiment_score", err: errors.New(`ent: missing required field "ConversationAnalytics.sentiment_score"`)}
	}
	if _, ok := _c.mutation.FoundProduct(); !ok {
		return &ValidationError{Name: "found_product", err: errors.New(`ent: missing required field "ConversationAnalytics.found_product"`)}
	}
	if _, ok := _c.mutation.SessionCompleted(); !ok {
		return &ValidationError{Name: "session_completed", err: errors.New(`ent: missing required field "ConversationAnalytics.session_completed"`)}
	}
	if _, ok := _c.mutation.AvgResponseTime(); !ok {
		return &ValidationError{Name: "avg_response_time", err: errors.New(`ent: missing required field "ConversationAnalytics.avg_response_time"`)}
	}
	if _, ok := _c.mutation.ClarificationCount(); !ok {
		return &ValidationError{Name: "clarification_count", err: errors.New(`ent: missing required field "ConversationAnalytics.clarification_count"`)}
	}
	if _, ok := _c.mutation.SearchRefinementCount(); !ok {
		return &ValidationError{Name: "search_refinement_count", err: errors.New(`ent: missing required field "ConversationAnalytics.search_refinement_count"`)}
	}
	if _, ok := _c.mutation.FlowQualityScore(); !ok {
		return &ValidationError{Name: "flow_quality_score", err: errors.New(`ent: missing required field "ConversationAnalytics.flow_quality_score"`)}
	}
	if _, ok := _c.mutation.ExtractedPreferences(); !ok {
		return &ValidationError{Name: "extracted_preferences", err: errors.New(`ent: missing required field "ConversationAnalytics.extracted_preferences"`)}
	}
	if _, ok := _c.mutation.PriceMentions(); !ok {
		return &ValidationError{Name: "price_mentions", err: errors.New(`ent: missing required field "ConversationAnalytics.price_mentions"`)}
	}
	if _, ok := _c.mutation.BrandMentions(); !ok {
		return &ValidationError{Name: "brand_mentions", err: errors.New(`ent: missing required field "ConversationAnalytics.brand_mentions"`)}
	}
	if _, ok := _c.mutation.SessionStartedAt(); !ok {
		return &ValidationError{Name: "session_started_at", err: errors.New(`ent: missing required field "ConversationAnalytics.session_started_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ConversationAnalytics.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ConversationAnalytics.updated_at"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "ConversationAnalytics.session"`)}
	}
	return nil
}

func (_c *ConversationAnalyticsCreate) sqlSave(ctx context.Context) (*ConversationAnalytics, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConversationAnalyticsCreate) createSpec() (*ConversationAnalytics, *sqlgraph.CreateSpec) {
	var (
		_node = &ConversationAnalytics{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(conversationanalytics.Table, sqlgraph.NewFieldSpec(conversationanalytics.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.MessageCount(); ok {
		_spec.SetField(conversationanalytics.FieldMessageCount, field.TypeInt, value)
		_node.MessageCount = value
	}
	if value, ok := _c.mutation.UserMessageCount(); ok {
		_spec.SetField(conversationanalytics.FieldUserMessageCount, field.TypeInt, value)
		_node.UserMessageCount = value
	}
	if value, ok := _c.mutation.AssistantMessageCount(); ok {
		_spec.SetField(conversationanalytics.FieldAssistantMessageCount, field.TypeInt, value)
		_node.AssistantMessageCount = value
	}
	if value, ok := _c.mutation.SearchCount(); ok {
		_spec.SetField(conversationanalytics.FieldSearchCount, field.TypeInt, value)
		_node.SearchCount = value
	}
	if value, ok := _c.mutation.ProductsShown(); ok {
		_spec.SetField(conversationanalytics.FieldProductsShown, field.TypeInt, value)
		_node.ProductsShown = value
	}
	if value, ok := _c.mutation.ProductsClicked(); ok {
		_spec.SetField(conversationanalytics.FieldProductsClicked, field.TypeInt, value)
		_node.ProductsClicked = value
	}
	if value, ok := _c.mutation.SessionDuration(); ok {
		_spec.SetField(conversationanalytics.FieldSessionDuration, field.TypeInt, value)
		_node.SessionDuration = value
	}
	if value, ok := _c.mutation.KeyTopics(); ok {
		_spec.SetField(conversationanalytics.FieldKeyTopics, field.TypeJSON, value)
		_node.KeyTopics = value
	}
	if value, ok := _c.mutation.CategoriesExplored(); ok {
		_spec.SetField(conversationanalytics.FieldCategoriesExplored, field.TypeJSON, value)
		_node.CategoriesExplored = value
	}
	if value, ok := _c.mutation.OverallSentiment(); ok {
		_spec.SetField(conversationanalytics.FieldOverallSentiment, field.TypeString, value)
		_node.OverallSentiment = value
	}
	if value, ok := _c.mutation.SentimentScore(); ok {
		_spec.SetField(conversationanalytics.FieldSentimentScore, field.TypeFloat64, value)
		_node.SentimentScore = value
	}
	if value, ok := _c.mutation.PrimaryIntent(); ok {
		_spec.SetField(conversationanalytics.FieldPrimaryIntent, field.TypeString, value)
		_node.PrimaryIntent = value
	}
	if value, ok := _c.mutation.FoundProduct(); ok {
		_spec.SetField(conversationanalytics.FieldFoundProduct, field.TypeBool, value)
		_node.FoundProduct = value
	}
	if value, ok := _c.mutation.SessionCompleted(); ok {
		_spec.SetField(conversationanalytics.FieldSessionCompleted, field.TypeBool, value)
		_node.SessionCompleted = value
	}
	if value, ok := _c.mutation.UserSatisfied(); ok {
		_spec.SetField(conversationanalytics.FieldUserSatisfied, field.TypeBool, value)
		_node.UserSatisfied = value
	}
	if value, ok := _c.mutation.AvgResponseTime(); ok {
		_spec.SetField(conversationanalytics.FieldAvgResponseTime, field.TypeInt, value)
		_node.AvgResponseTime = value
	}
	if value, ok := _c.mutation.ClarificationCount(); ok {
		_spec.SetField(conversationanalytics.FieldClarificationCount, field.TypeInt, value)
		_node.ClarificationCount = value
	}
	if value, ok := _c.mutation.SearchRefinementCount(); ok {
		_spec.SetField(conversationanalytics.FieldSearchRefinementCount, field.TypeInt, value)
		_node.SearchRefinementCount = value
	}
	if value, ok := _c.mutation.FlowQualityScore(); ok {
		_spec.SetField(conversationanalytics.FieldFlowQualityScore, field.TypeFloat64, value)
		_node.FlowQualityScore = value
	}
	if value, ok := _c.mutation.ExtractedPreferences(); ok {
		_spec.SetField(conversationanalytics.FieldExtractedPreferences, field.TypeJSON, value)
		_node.ExtractedPreferences = value
	}
	if value, ok := _c.mutation.PriceMentions(); ok {
		_spec.SetField(conversationanalytics.FieldPriceMentions, field.TypeJSON, value)
		_node.PriceMentions = value
	}
	if value, ok := _c.mutation.BrandMentions(); ok {
		_spec.SetField(conversationanalytics.FieldBrandMentions, field.TypeJSON, value)
		_node.BrandMentions = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(conversationanalytics.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.SessionStartedAt(); ok {
		_spec.SetField(conversationanalytics.FieldSessionStartedAt, field.TypeTime, value)
		_node.SessionStartedAt = value
	}
	if value, ok := _c.mutation.SessionEndedAt(); ok {
		_spec.SetField(conversationanalytics.FieldSessionEndedAt, field.TypeTime, value)
		_node.SessionEndedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(conversationanalytics.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(conversationanalytics.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationanalytics.UserTable,
			Columns: []string{conversationanalytics.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   conversationanalytics.SessionTable,
			Columns: []string{conversationanalytics.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ConversationAnalyticsCreateBulk is the builder for creating many ConversationAnalytics entities in bulk.
type ConversationAnalyticsCreateBulk struct {
	config
	err      error
	builders []*ConversationAnalyticsCreate
}

// Save creates the ConversationAnalytics entities in the database.
func (_c *ConversationAnalyticsCreateBulk) Save(ctx context.Context) ([]*ConversationAnalytics, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ConversationAnalytics, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConversationAnalyticsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConversationAnalyticsCreateBulk) SaveX(ctx context.Context) []*ConversationAnalytics {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationAnalyticsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationAnalyticsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
