// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mylittleprice/ent/productinteraction"
	"mylittleprice/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ProductInteractionCreate is the builder for creating a ProductInteraction entity.
type ProductInteractionCreate struct {
	config
	mutation *ProductInteractionMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *ProductInteractionCreate) SetUserID(v uuid.UUID) *ProductInteractionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *ProductInteractionCreate) SetNillableUserID(v *uuid.UUID) *ProductInteractionCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *ProductInteractionCreate) SetSessionID(v string) *ProductInteractionCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *ProductInteractionCreate) SetProductID(v string) *ProductInteractionCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetProductName sets the "product_name" field.
func (_c *ProductInteractionCreate) SetProductName(v string) *ProductInteractionCreate {
	_c.mutation.SetProductName(v)
	return _c
}

// SetProductPrice sets the "product_price" field.
func (_c *ProductInteractionCreate) SetProductPrice(v float64) *ProductInteractionCreate {
	_c.mutation.SetProductPrice(v)
	return _c
}

// SetNillableProductPrice sets the "product_price" field if the given value is not nil.
func (_c *ProductInteractionCreate) SetNillableProductPrice(v *float64) *ProductInteractionCreate {
	if v != nil {
		_c.SetProductPrice(*v)
	}
	return _c
}

// SetProductCurrency sets the "product_currency" field.
func (_c *ProductInteractionCreate) SetProductCurrency(v string) *ProductInteractionCreate {
	_c.mutation.SetProductCurrency(v)
	return _c
}

// SetNillableProductCurrency sets the "product_currency" field if the given value is not nil.
func (_c *ProductInteractionCreate) SetNillableProductCurrency(v *string) *ProductInteractionCreate {
	if v != nil {
		_c.SetProductCurrency(*v)
	}
	return _c
}

// SetProductCategory sets the "product_category" field.
func (_c *ProductInteractionCreate) SetProductCategory(v string) *ProductInteractionCreate {
	_c.mutation.SetProductCategory(v)
	return _c
}

// SetNillableProductCategory sets the "product_category" field if the given value is not nil.
func (_c *ProductInteractionCreate) SetNillableProductCategory(v *string) *ProductInteractionCreate {
	if v != nil {
		_c.SetProductCategory(*v)
	}
	return _c
}

// SetProductBrand sets the "product_brand" field.
func (_c *ProductInteractionCreate) SetProductBrand(v string) *ProductInteractionCreate {
	_c.mutation.SetProductBrand(v)
	return _c
}

// SetNillableProductBrand sets the "product_brand" field if the given value is not nil.
func (_c *ProductInteractionCreate) SetNillableProductBrand(v *string) *ProductInteractionCreate {
	if v != nil {
		_c.SetProductBrand(*v)
	}
	return _c
}

// SetProductURL sets the "product_url" field.
func (_c *ProductInteractionCreate) SetProductURL(v string) *ProductInteractionCreate {
	_c.mutation.SetProductURL(v)
	return _c
}

// SetNillableProductURL sets the "product_url" field if the given value is not nil.
func (_c *ProductInteractionCreate) SetNillableProductURL(v *string) *ProductInteractionCreate {
	if v != nil {
		_c.SetProductURL(*v)
	}
	return _c
}

// SetProductData sets the "product_data" field.
func (_c *ProductInteractionCreate) SetProductData(v map[string]interface{}) *ProductInteractionCreate {
	_c.mutation.SetProductData(v)
	return _c
}

// SetInteractionType sets the "interaction_type" field.
func (_c *ProductInteractionCreate) SetInteractionType(v string) *ProductInteractionCreate {
	_c.mutation.SetInteractionType(v)
	return _c
}

// SetMessagePosition sets the "message_position" field.
func (_c *ProductInteractionCreate) SetMessagePosition(v int) *ProductInteractionCreate {
	_c.mutation.SetMessagePosition(v)
	return _c
}

// SetNillableMessagePosition sets the "message_position" field if the given value is not nil.
func (_c *ProductInteractionCreate) SetNillableMessagePosition(v *int) *ProductInteractionCreate {
	if v != nil {
		_c.SetMessagePosition(*v)
	}
	return _c
}

// SetViewDurationSeconds sets the "view_duration_seconds" field.
func (_c *ProductInteractionCreate) SetViewDurationSeconds(v int) *ProductInteractionCreate {
	_c.mutation.SetViewDurationSeconds(v)
	return _c
}

// SetNillableViewDurationSeconds sets the "view_duration_seconds" field if the given value is not nil.
func (_c *ProductInteractionCreate) SetNillableViewDurationSeconds(v *int) *ProductInteractionCreate {
	if v != nil {
		_c.SetViewDurationSeconds(*v)
	}
	return _c
}

// SetClickCount sets the "click_count" field.
func (_c *ProductInteractionCreate) SetClickCount(v int) *ProductInteractionCreate {
	_c.mutation.SetClickCount(v)
	return _c
}

// SetNillableClickCount sets the "click_count" field if the given value is not nil.
func (_c *ProductInteractionCreate) SetNillableClickCount(v *int) *ProductInteractionCreate {
	if v != nil {
		_c.SetClickCount(*v)
	}
	return _c
}

// SetOpenedDetails sets the "opened_details" field.
func (_c *ProductInteractionCreate) SetOpenedDetails(v bool) *ProductInteractionCreate {
	_c.mutation.SetOpenedDetails(v)
	return _c
}

// SetNillableOpenedDetails sets the "opened_details" field if the given value is not nil.
func (_c *ProductInteractionCreate) SetNillableOpenedDetails(v *bool) *ProductInteractionCreate {
	if v != nil {
		_c.SetOpenedDetails(*v)
	}
	return _c
}

// SetAddedToComparison sets the "added_to_comparison" field.
func (_c *ProductInteractionCreate) SetAddedToComparison(v bool) *ProductInteractionCreate {
	_c.mutation.SetAddedToComparison(v)
	return _c
}

// SetNillableAddedToComparison sets the "added_to_comparison" field if the given value is not nil.
func (_c *ProductInteractionCreate) SetNillableAddedToComparison(v *bool) *ProductInteractionCreate {
	if v != nil {
		_c.SetAddedToComparison(*v)
	}
	return _c
}

// SetFeedback sets the "feedback" field.
func (_c *ProductInteractionCreate) SetFeedback(v string) *ProductInteractionCreate {
	_c.mutation.SetFeedback(v)
	return _c
}

// SetNillableFeedback sets the "feedback" field if the given value is not nil.
func (_c *ProductInteractionCreate) SetNillableFeedback(v *string) *ProductInteractionCreate {
	if v != nil {
		_c.SetFeedback(*v)
	}
	return _c
}

// SetImplicitScore sets the "implicit_score" field.
func (_c *ProductInteractionCreate) SetImplicitScore(v float64) *ProductInteractionCreate {
	_c.mutation.SetImplicitScore(v)
	return _c
}

// SetNillableImplicitScore sets the "implicit_score" field if the given value is not nil.
func (_c *ProductInteractionCreate) SetNillableImplicitScore(v *float64) *ProductInteractionCreate {
	if v != nil {
		_c.SetImplicitScore(*v)
	}
	return _c
}

// SetSearchQuery sets the "search_query" field.
func (_c *ProductInteractionCreate) SetSearchQuery(v string) *ProductInteractionCreate {
	_c.mutation.SetSearchQuery(v)
	return _c
}

// SetNillableSearchQuery sets the "search_query" field if the given value is not nil.
func (_c *ProductInteractionCreate) SetNillableSearchQuery(v *string) *ProductInteractionCreate {
	if v != nil {
		_c.SetSearchQuery(*v)
	}
	return _c
}

// SetSearchType sets the "search_type" field.
func (_c *ProductInteractionCreate) SetSearchType(v string) *ProductInteractionCreate {
	_c.mutation.SetSearchType(v)
	return _c
}

// SetNillableSearchType sets the "search_type" field if the given value is not nil.
func (_c *ProductInteractionCreate) SetNillableSearchType(v *string) *ProductInteractionCreate {
	if v != nil {
		_c.SetSearchType(*v)
	}
	return _c
}

// SetPositionInResults sets the "position_in_results" field.
func (_c *ProductInteractionCreate) SetPositionInResults(v int) *ProductInteractionCreate {
	_c.mutation.SetPositionInResults(v)
	return _c
}

// SetNillablePositionInResults sets the "position_in_results" field if the given value is not nil.
func (_c *ProductInteractionCreate) SetNillablePositionInResults(v *int) *ProductInteractionCreate {
	if v != nil {
		_c.SetPositionInResults(*v)
	}
	return _c
}

// SetInteractionSequence sets the "interaction_sequence" field.
func (_c *ProductInteractionCreate) SetInteractionSequence(v int) *ProductInteractionCreate {
	_c.mutation.SetInteractionSequence(v)
	return _c
}

// SetNillableInteractionSequence sets the "interaction_sequence" field if the given value is not nil.
func (_c *ProductInteractionCreate) SetNillableInteractionSequence(v *int) *ProductInteractionCreate {
	if v != nil {
		_c.SetInteractionSequence(*v)
	}
	return _c
}

// SetInteractedAt sets the "interacted_at" field.
func (_c *ProductInteractionCreate) SetInteractedAt(v time.Time) *ProductInteractionCreate {
	_c.mutation.SetInteractedAt(v)
	return _c
}

// SetNillableInteractedAt sets the "interacted_at" field if the given value is not nil.
func (_c *ProductInteractionCreate) SetNillableInteractedAt(v *time.Time) *ProductInteractionCreate {
	if v != nil {
		_c.SetInteractedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProductInteractionCreate) SetCreatedAt(v time.Time) *ProductInteractionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProductInteractionCreate) SetNillableCreatedAt(v *time.Time) *ProductInteractionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProductInteractionCreate) SetUpdatedAt(v time.Time) *ProductInteractionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProductInteractionCreate) SetNillableUpdatedAt(v *time.Time) *ProductInteractionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProductInteractionCreate) SetID(v uuid.UUID) *ProductInteractionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ProductInteractionCreate) SetNillableID(v *uuid.UUID) *ProductInteractionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ProductInteractionCreate) SetUser(v *User) *ProductInteractionCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ProductInteractionMutation object of the builder.
func (_c *ProductInteractionCreate) Mutation() *ProductInteractionMutation {
	return _c.mutation
}

// Save creates the ProductInteraction in the database.
func (_c *ProductInteractionCreate) Save(ctx context.Context) (*ProductInteraction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProductInteractionCreate) SaveX(ctx context.Context) *ProductInteraction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProductInteractionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProductInteractionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProductInteractionCreate) defaults() {
	if _, ok := _c.mutation.MessagePosition(); !ok {
		v := productinteraction.DefaultMessagePosition
		_c.mutation.SetMessagePosition(v)
	}
	if _, ok := _c.mutation.ViewDurationSeconds(); !ok {
		v := productinteraction.DefaultViewDurationSeconds
		_c.mutation.SetViewDurationSeconds(v)
	}
	if _, ok := _c.mutation.ClickCount(); !ok {
		v := productinteraction.DefaultClickCount
		_c.mutation.SetClickCount(v)
	}
	if _, ok := _c.mutation.OpenedDetails(); !ok {
		v := productinteraction.DefaultOpenedDetails
		_c.mutation.SetOpenedDetails(v)
	}
	if _, ok := _c.mutation.AddedToComparison(); !ok {
		v := productinteraction.DefaultAddedToComparison
		_c.mutation.SetAddedToComparison(v)
	}
	if _, ok := _c.mutation.ImplicitScore(); !ok {
		v := productinteraction.DefaultImplicitScore
		_c.mutation.SetImplicitScore(v)
	}
	if _, ok := _c.mutation.PositionInResults(); !ok {
		v := productinteraction.DefaultPositionInResults
		_c.mutation.SetPositionInResults(v)
	}
	if _, ok := _c.mutation.InteractionSequence(); !ok {
		v := productinteraction.DefaultInteractionSequence
		_c.mutation.SetInteractionSequence(v)
	}
	if _, ok := _c.mutation.InteractedAt(); !ok {
		v := productinteraction.DefaultInteractedAt()
		_c.mutation.SetInteractedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := productinteraction.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := productinteraction.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := productinteraction.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProductInteractionCreate) check() error {
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "ProductInteraction.session_id"`)}
	}
	if v, ok := _c.mutation.SessionID(); ok {
		if err := productinteraction.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "ProductInteraction.session_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "ProductInteraction.product_id"`)}
	}
	if v, ok := _c.mutation.ProductID(); ok {
		if err := productinteraction.ProductIDValidator(v); err != nil {
			return &ValidationError{Name: "product_id", err: fmt.Errorf(`ent: validator failed for field "ProductInteraction.product_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProductName(); !ok {
		return &ValidationError{Name: "product_name", err: errors.New(`ent: missing required field "ProductInteraction.product_name"`)}
	}
	if v, ok := _c.mutation.ProductName(); ok {
		if err := productinteraction.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "ProductInteraction.product_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InteractionType(); !ok {
		return &ValidationError{Name: "interaction_type", err: errors.New(`ent: missing required field "ProductInteraction.interaction_type"`)}
	}
	if v, ok := _c.mutation.InteractionType(); ok {
		if err := productinteraction.InteractionTypeValidator(v); err != nil {
			return &ValidationError{Name: "interaction_type", err: fmt.Errorf(`ent: validator failed for field "ProductInteraction.interaction_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MessagePosition(); !ok {
		return &ValidationError{Name: "message_position", err: errors.New(`ent: missing required field "ProductInteraction.message_position"`)}
	}
	if _, ok := _c.mutation.ViewDurationSeconds(); !ok {
		return &ValidationError{Name: "view_duration_seconds", err: errors.New(`ent: missing required field "ProductInteraction.view_duration_seconds"`)}
	}
	if _, ok := _c.mutation.ClickCount(); !ok {
		return &ValidationError{Name: "click_count", err: errors.New(`ent: missing required field "ProductInteraction.click_count"`)}
	}
	if _, ok := _c.mutation.OpenedDetails(); !ok {
		return &ValidationError{Name: "opened_details", err: errors.New(`ent: missing required field "ProductInteraction.opened_details"`)}
	}
	if _, ok := _c.mutation.AddedToComparison(); !ok {
		return &ValidationError{Name: "added_to_comparison", err: errors.New(`ent: missing required field "ProductInteraction.added_to_comparison"`)}
	}
	if _, ok := _c.mutation.ImplicitScore(); !ok {
		return &ValidationError{Name: "implicit_score", err: errors.New(`ent: missing required field "ProductInteraction.implicit_score"`)}
	}
	if _, ok := _c.mutation.PositionInResults(); !ok {
		return &ValidationError{Name: "position_in_results", err: errors.New(`ent: missing required field "ProductInteraction.position_in_results"`)}
	}
	if _, ok := _c.mutation.InteractionSequence(); !ok {
		return &ValidationError{Name: "interaction_sequence", err: errors.New(`ent: missing required field "ProductInteraction.interaction_sequence"`)}
	}
	if _, ok := _c.mutation.InteractedAt(); !ok {
		return &ValidationError{Name: "interacted_at", err: errors.New(`ent: missing required field "ProductInteraction.interacted_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProductInteraction.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProductInteraction.updated_at"`)}
	}
	return nil
}

func (_c *ProductInteractionCreate) sqlSave(ctx context.Context) (*ProductInteraction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProductInteractionCreate) createSpec() (*ProductInteraction, *sqlgraph.CreateSpec) {
	var (
		_node = &ProductInteraction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(productinteraction.Table, sqlgraph.NewFieldSpec(productinteraction.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(productinteraction.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.ProductID(); ok {
		_spec.SetField(productinteraction.FieldProductID, field.TypeString, value)
		_node.ProductID = value
	}
	if value, ok := _c.mutation.ProductName(); ok {
		_spec.SetField(productinteraction.FieldProductName, field.TypeString, value)
		_node.ProductName = value
	}
	if value, ok := _c.mutation.ProductPrice(); ok {
		_spec.SetField(productinteraction.FieldProductPrice, field.TypeFloat64, value)
		_node.ProductPrice = value
	}
	if value, ok := _c.mutation.ProductCurrency(); ok {
		_spec.SetField(productinteraction.FieldProductCurrency, field.TypeString, value)
		_node.ProductCurrency = value
	}
	if value, ok := _c.mutation.ProductCategory(); ok {
		_spec.SetField(productinteraction.FieldProductCategory, field.TypeString, value)
		_node.ProductCategory = value
	}
	if value, ok := _c.mutation.ProductBrand(); ok {
		_spec.SetField(productinteraction.FieldProductBrand, field.TypeString, value)
		_node.ProductBrand = value
	}
	if value, ok := _c.mutation.ProductURL(); ok {
		_spec.SetField(productinteraction.FieldProductURL, field.TypeString, value)
		_node.ProductURL = value
	}
	if value, ok := _c.mutation.ProductData(); ok {
		_spec.SetField(productinteraction.FieldProductData, field.TypeJSON, value)
		_node.ProductData = value
	}
	if value, ok := _c.mutation.InteractionType(); ok {
		_spec.SetField(productinteraction.FieldInteractionType, field.TypeString, value)
		_node.InteractionType = value
	}
	if value, ok := _c.mutation.MessagePosition(); ok {
		_spec.SetField(productinteraction.FieldMessagePosition, field.TypeInt, value)
		_node.MessagePosition = value
	}
	if value, ok := _c.mutation.ViewDurationSeconds(); ok {
		_spec.SetField(productinteraction.FieldViewDurationSeconds, field.TypeInt, value)
		_node.ViewDurationSeconds = value
	}
	if value, ok := _c.mutation.ClickCount(); ok {
		_spec.SetField(productinteraction.FieldClickCount, field.TypeInt, value)
		_node.ClickCount = value
	}
	if value, ok := _c.mutation.OpenedDetails(); ok {
		_spec.SetField(productinteraction.FieldOpenedDetails, field.TypeBool, value)
		_node.OpenedDetails = value
	}
	if value, ok := _c.mutation.AddedToComparison(); ok {
		_spec.SetField(productinteraction.FieldAddedToComparison, field.TypeBool, value)
		_node.AddedToComparison = value
	}
	if value, ok := _c.mutation.Feedback(); ok {
		_spec.SetField(productinteraction.FieldFeedback, field.TypeString, value)
		_node.Feedback = value
	}
	if value, ok := _c.mutation.ImplicitScore(); ok {
		_spec.SetField(productinteraction.FieldImplicitScore, field.TypeFloat64, value)
		_node.ImplicitScore = value
	}
	if value, ok := _c.mutation.SearchQuery(); ok {
		_spec.SetField(productinteraction.FieldSearchQuery, field.TypeString, value)
		_node.SearchQuery = value
	}
	if value, ok := _c.mutation.SearchType(); ok {
		_spec.SetField(productinteraction.FieldSearchType, field.TypeString, value)
		_node.SearchType = value
	}
	if value, ok := _c.mutation.PositionInResults(); ok {
		_spec.SetField(productinteraction.FieldPositionInResults, field.TypeInt, value)
		_node.PositionInResults = value
	}
	if value, ok := _c.mutation.InteractionSequence(); ok {
		_spec.SetField(productinteraction.FieldInteractionSequence, field.TypeInt, value)
		_node.InteractionSequence = value
	}
	if value, ok := _c.mutation.InteractedAt(); ok {
		_spec.SetField(productinteraction.FieldInteractedAt, field.TypeTime, value)
		_node.InteractedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(productinteraction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(productinteraction.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   productinteraction.UserTable,
			Columns: []string{productinteraction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProductInteractionCreateBulk is the builder for creating many ProductInteraction entities in bulk.
type ProductInteractionCreateBulk struct {
	config
	err      error
	builders []*ProductInteractionCreate
}

// Save creates the ProductInteraction entities in the database.
func (_c *ProductInteractionCreateBulk) Save(ctx context.Context) ([]*ProductInteraction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProductInteraction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductInteractionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProductInteractionCreateBulk) SaveX(ctx context.Context) []*ProductInteraction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProductInteractionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProductInteractionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
