// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"mylittleprice/ent/predicate"
	"mylittleprice/ent/productinteraction"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductInteractionDelete is the builder for deleting a ProductInteraction entity.
type ProductInteractionDelete struct {
	config
	hooks    []Hook
	mutation *ProductInteractionMutation
}

// Where appends a list predicates to the ProductInteractionDelete builder.
func (_d *ProductInteractionDelete) Where(ps ...predicate.ProductInteraction) *ProductInteractionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ProductInteractionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProductInteractionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ProductInteractionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(productinteraction.Table, sqlgraph.NewFieldSpec(productinteraction.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ProductInteractionDeleteOne is the builder for deleting a single ProductInteraction entity.
type ProductInteractionDeleteOne struct {
	_d *ProductInteractionDelete
}

// Where appends a list predicates to the ProductInteractionDelete builder.
func (_d *ProductInteractionDeleteOne) Where(ps ...predicate.ProductInteraction) *ProductInteractionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ProductInteractionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{productinteraction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProductInteractionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
