// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"mylittleprice/ent/productinteraction"
	"mylittleprice/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ProductInteraction is the model entity for the ProductInteraction schema.
type ProductInteraction struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// ProductID holds the value of the "product_id" field.
	ProductID string `json:"product_id,omitempty"`
	// ProductName holds the value of the "product_name" field.
	ProductName string `json:"product_name,omitempty"`
	// ProductPrice holds the value of the "product_price" field.
	ProductPrice float64 `json:"product_price,omitempty"`
	// ProductCurrency holds the value of the "product_currency" field.
	ProductCurrency string `json:"product_currency,omitempty"`
	// ProductCategory holds the value of the "product_category" field.
	ProductCategory string `json:"product_category,omitempty"`
	// ProductBrand holds the value of the "product_brand" field.
	ProductBrand string `json:"product_brand,omitempty"`
	// ProductURL holds the value of the "product_url" field.
	ProductURL string `json:"product_url,omitempty"`
	// ProductData holds the value of the "product_data" field.
	ProductData map[string]interface{} `json:"product_data,omitempty"`
	// InteractionType holds the value of the "interaction_type" field.
	InteractionType string `json:"interaction_type,omitempty"`
	// MessagePosition holds the value of the "message_position" field.
	MessagePosition int `json:"message_position,omitempty"`
	// ViewDurationSeconds holds the value of the "view_duration_seconds" field.
	ViewDurationSeconds int `json:"view_duration_seconds,omitempty"`
	// ClickCount holds the value of the "click_count" field.
	ClickCount int `json:"click_count,omitempty"`
	// OpenedDetails holds the value of the "opened_details" field.
	OpenedDetails bool `json:"opened_details,omitempty"`
	// AddedToComparison holds the value of the "added_to_comparison" field.
	AddedToComparison bool `json:"added_to_comparison,omitempty"`
	// Feedback holds the value of the "feedback" field.
	Feedback string `json:"feedback,omitempty"`
	// ImplicitScore holds the value of the "implicit_score" field.
	ImplicitScore float64 `json:"implicit_score,omitempty"`
	// SearchQuery holds the value of the "search_query" field.
	SearchQuery string `json:"search_query,omitempty"`
	// SearchType holds the value of the "search_type" field.
	SearchType string `json:"search_type,omitempty"`
	// PositionInResults holds the value of the "position_in_results" field.
	PositionInResults int `json:"position_in_results,omitempty"`
	// InteractionSequence holds the value of the "interaction_sequence" field.
	InteractionSequence int `json:"interaction_sequence,omitempty"`
	// InteractedAt holds the value of the "interacted_at" field.
	InteractedAt time.Time `json:"interacted_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProductInteractionQuery when eager-loading is set.
	Edges        ProductInteractionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProductInteractionEdges holds the relations/edges for other nodes in the graph.
type ProductInteractionEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProductInteractionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProductInteraction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case productinteraction.FieldProductData:
			values[i] = new([]byte)
		case productinteraction.FieldOpenedDetails, productinteraction.FieldAddedToComparison:
			values[i] = new(sql.NullBool)
		case productinteraction.FieldProductPrice, productinteraction.FieldImplicitScore:
			values[i] = new(sql.NullFloat64)
		case productinteraction.FieldMessagePosition, productinteraction.FieldViewDurationSeconds, productinteraction.FieldClickCount, productinteraction.FieldPositionInResults, productinteraction.FieldInteractionSequence:
			values[i] = new(sql.NullInt64)
		case productinteraction.FieldSessionID, productinteraction.FieldProductID, productinteraction.FieldProductName, productinteraction.FieldProductCurrency, productinteraction.FieldProductCategory, productinteraction.FieldProductBrand, productinteraction.FieldProductURL, productinteraction.FieldInteractionType, productinteraction.FieldFeedback, productinteraction.FieldSearchQuery, productinteraction.FieldSearchType:
			values[i] = new(sql.NullString)
		case productinteraction.FieldInteractedAt, productinteraction.FieldCreatedAt, productinteraction.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case productinteraction.FieldID, productinteraction.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProductInteraction fields.
func (_m *ProductInteraction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case productinteraction.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case productinteraction.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case productinteraction.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case productinteraction.FieldProductID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				_m.ProductID = value.String
			}
		case productinteraction.FieldProductName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_name", values[i])
			} else if value.Valid {
				_m.ProductName = value.String
			}
		case productinteraction.FieldProductPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field product_price", values[i])
			} else if value.Valid {
				_m.ProductPrice = value.Float64
			}
		case productinteraction.FieldProductCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_currency", values[i])
			} else if value.Valid {
				_m.ProductCurrency = value.String
			}
		case productinteraction.FieldProductCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_category", values[i])
			} else if value.Valid {
				_m.ProductCategory = value.String
			}
		case productinteraction.FieldProductBrand:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_brand", values[i])
			} else if value.Valid {
				_m.ProductBrand = value.String
			}
		case productinteraction.FieldProductURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_url", values[i])
			} else if value.Valid {
				_m.ProductURL = value.String
			}
		case productinteraction.FieldProductData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field product_data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ProductData); err != nil {
					return fmt.Errorf("unmarshal field product_data: %w", err)
				}
			}
		case productinteraction.FieldInteractionType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field interaction_type", values[i])
			} else if value.Valid {
				_m.InteractionType = value.String
			}
		case productinteraction.FieldMessagePosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field message_position", values[i])
			} else if value.Valid {
				_m.MessagePosition = int(value.Int64)
			}
		case productinteraction.FieldViewDurationSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field view_duration_seconds", values[i])
			} else if value.Valid {
				_m.ViewDurationSeconds = int(value.Int64)
			}
		case productinteraction.FieldClickCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field click_count", values[i])
			} else if value.Valid {
				_m.ClickCount = int(value.Int64)
			}
		case productinteraction.FieldOpenedDetails:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field opened_details", values[i])
			} else if value.Valid {
				_m.OpenedDetails = value.Bool
			}
		case productinteraction.FieldAddedToComparison:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field added_to_comparison", values[i])
			} else if value.Valid {
				_m.AddedToComparison = value.Bool
			}
		case productinteraction.FieldFeedback:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field feedback", values[i])
			} else if value.Valid {
				_m.Feedback = value.String
			}
		case productinteraction.FieldImplicitScore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field implicit_score", values[i])
			} else if value.Valid {
				_m.ImplicitScore = value.Float64
			}
		case productinteraction.FieldSearchQuery:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field search_query", values[i])
			} else if value.Valid {
				_m.SearchQuery = value.String
			}
		case productinteraction.FieldSearchType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field search_type", values[i])
			} else if value.Valid {
				_m.SearchType = value.String
			}
		case productinteraction.FieldPositionInResults:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position_in_results", values[i])
			} else if value.Valid {
				_m.PositionInResults = int(value.Int64)
			}
		case productinteraction.FieldInteractionSequence:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field interaction_sequence", values[i])
			} else if value.Valid {
				_m.InteractionSequence = int(value.Int64)
			}
		case productinteraction.FieldInteractedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field interacted_at", values[i])
			} else if value.Valid {
				_m.InteractedAt = value.Time
			}
		case productinteraction.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case productinteraction.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProductInteraction.
// This includes values selected through modifiers, order, etc.
func (_m *ProductInteraction) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ProductInteraction entity.
func (_m *ProductInteraction) QueryUser() *UserQuery {
	return NewProductInteractionClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this ProductInteraction.
// Note that you need to call ProductInteraction.Unwrap() before calling this method if this ProductInteraction
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProductInteraction) Update() *ProductInteractionUpdateOne {
	return NewProductInteractionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProductInteraction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProductInteraction) Unwrap() *ProductInteraction {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProductInteraction is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProductInteraction) String() string {
	var builder strings.Builder
	builder.WriteString("ProductInteraction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("product_id=")
	builder.WriteString(_m.ProductID)
	builder.WriteString(", ")
	builder.WriteString("product_name=")
	builder.WriteString(_m.ProductName)
	builder.WriteString(", ")
	builder.WriteString("product_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProductPrice))
	builder.WriteString(", ")
	builder.WriteString("product_currency=")
	builder.WriteString(_m.ProductCurrency)
	builder.WriteString(", ")
	builder.WriteString("product_category=")
	builder.WriteString(_m.ProductCategory)
	builder.WriteString(", ")
	builder.WriteString("product_brand=")
	builder.WriteString(_m.ProductBrand)
	builder.WriteString(", ")
	builder.WriteString("product_url=")
	builder.WriteString(_m.ProductURL)
	builder.WriteString(", ")
	builder.WriteString("product_data=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProductData))
	builder.WriteString(", ")
	builder.WriteString("interaction_type=")
	builder.WriteString(_m.InteractionType)
	builder.WriteString(", ")
	builder.WriteString("message_position=")
	builder.WriteString(fmt.Sprintf("%v", _m.MessagePosition))
	builder.WriteString(", ")
	builder.WriteString("view_duration_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.ViewDurationSeconds))
	builder.WriteString(", ")
	builder.WriteString("click_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClickCount))
	builder.WriteString(", ")
	builder.WriteString("opened_details=")
	builder.WriteString(fmt.Sprintf("%v", _m.OpenedDetails))
	builder.WriteString(", ")
	builder.WriteString("added_to_comparison=")
	builder.WriteString(fmt.Sprintf("%v", _m.AddedToComparison))
	builder.WriteString(", ")
	builder.WriteString("feedback=")
	builder.WriteString(_m.Feedback)
	builder.WriteString(", ")
	builder.WriteString("implicit_score=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImplicitScore))
	builder.WriteString(", ")
	builder.WriteString("search_query=")
	builder.WriteString(_m.SearchQuery)
	builder.WriteString(", ")
	builder.WriteString("search_type=")
	builder.WriteString(_m.SearchType)
	builder.WriteString(", ")
	builder.WriteString("position_in_results=")
	builder.WriteString(fmt.Sprintf("%v", _m.PositionInResults))
	builder.WriteString(", ")
	builder.WriteString("interaction_sequence=")
	builder.WriteString(fmt.Sprintf("%v", _m.InteractionSequence))
	builder.WriteString(", ")
	builder.WriteString("interacted_at=")
	builder.WriteString(_m.InteractedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProductInteractions is a parsable slice of ProductInteraction.
type ProductInteractions []*ProductInteraction
