// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mylittleprice/ent/predicate"
	"mylittleprice/ent/productinteraction"
	"mylittleprice/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ProductInteractionUpdate is the builder for updating ProductInteraction entities.
type ProductInteractionUpdate struct {
	config
	hooks    []Hook
	mutation *ProductInteractionMutation
}

// Where appends a list predicates to the ProductInteractionUpdate builder.
func (_u *ProductInteractionUpdate) Where(ps ...predicate.ProductInteraction) *ProductInteractionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ProductInteractionUpdate) SetUserID(v uuid.UUID) *ProductInteractionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillableUserID(v *uuid.UUID) *ProductInteractionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ProductInteractionUpdate) ClearUserID() *ProductInteractionUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *ProductInteractionUpdate) SetSessionID(v string) *ProductInteractionUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillableSessionID(v *string) *ProductInteractionUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *ProductInteractionUpdate) SetProductID(v string) *ProductInteractionUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillableProductID(v *string) *ProductInteractionUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *ProductInteractionUpdate) SetProductName(v string) *ProductInteractionUpdate {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillableProductName(v *string) *ProductInteractionUpdate {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetProductPrice sets the "product_price" field.
func (_u *ProductInteractionUpdate) SetProductPrice(v float64) *ProductInteractionUpdate {
	_u.mutation.ResetProductPrice()
	_u.mutation.SetProductPrice(v)
	return _u
}

// SetNillableProductPrice sets the "product_price" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillableProductPrice(v *float64) *ProductInteractionUpdate {
	if v != nil {
		_u.SetProductPrice(*v)
	}
	return _u
}

// AddProductPrice adds value to the "product_price" field.
func (_u *ProductInteractionUpdate) AddProductPrice(v float64) *ProductInteractionUpdate {
	_u.mutation.AddProductPrice(v)
	return _u
}

// ClearProductPrice clears the value of the "product_price" field.
func (_u *ProductInteractionUpdate) ClearProductPrice() *ProductInteractionUpdate {
	_u.mutation.ClearProductPrice()
	return _u
}

// SetProductCurrency sets the "product_currency" field.
func (_u *ProductInteractionUpdate) SetProductCurrency(v string) *ProductInteractionUpdate {
	_u.mutation.SetProductCurrency(v)
	return _u
}

// SetNillableProductCurrency sets the "product_currency" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillableProductCurrency(v *string) *ProductInteractionUpdate {
	if v != nil {
		_u.SetProductCurrency(*v)
	}
	return _u
}

// ClearProductCurrency clears the value of the "product_currency" field.
func (_u *ProductInteractionUpdate) ClearProductCurrency() *ProductInteractionUpdate {
	_u.mutation.ClearProductCurrency()
	return _u
}

// SetProductCategory sets the "product_category" field.
func (_u *ProductInteractionUpdate) SetProductCategory(v string) *ProductInteractionUpdate {
	_u.mutation.SetProductCategory(v)
	return _u
}

// SetNillableProductCategory sets the "product_category" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillableProductCategory(v *string) *ProductInteractionUpdate {
	if v != nil {
		_u.SetProductCategory(*v)
	}
	return _u
}

// ClearProductCategory clears the value of the "product_category" field.
func (_u *ProductInteractionUpdate) ClearProductCategory() *ProductInteractionUpdate {
	_u.mutation.ClearProductCategory()
	return _u
}

// SetProductBrand sets the "product_brand" field.
func (_u *ProductInteractionUpdate) SetProductBrand(v string) *ProductInteractionUpdate {
	_u.mutation.SetProductBrand(v)
	return _u
}

// SetNillableProductBrand sets the "product_brand" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillableProductBrand(v *string) *ProductInteractionUpdate {
	if v != nil {
		_u.SetProductBrand(*v)
	}
	return _u
}

// ClearProductBrand clears the value of the "product_brand" field.
func (_u *ProductInteractionUpdate) ClearProductBrand() *ProductInteractionUpdate {
	_u.mutation.ClearProductBrand()
	return _u
}

// SetProductURL sets the "product_url" field.
func (_u *ProductInteractionUpdate) SetProductURL(v string) *ProductInteractionUpdate {
	_u.mutation.SetProductURL(v)
	return _u
}

// SetNillableProductURL sets the "product_url" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillableProductURL(v *string) *ProductInteractionUpdate {
	if v != nil {
		_u.SetProductURL(*v)
	}
	return _u
}

// ClearProductURL clears the value of the "product_url" field.
func (_u *ProductInteractionUpdate) ClearProductURL() *ProductInteractionUpdate {
	_u.mutation.ClearProductURL()
	return _u
}

// SetProductData sets the "product_data" field.
func (_u *ProductInteractionUpdate) SetProductData(v map[string]interface{}) *ProductInteractionUpdate {
	_u.mutation.SetProductData(v)
	return _u
}

// ClearProductData clears the value of the "product_data" field.
func (_u *ProductInteractionUpdate) ClearProductData() *ProductInteractionUpdate {
	_u.mutation.ClearProductData()
	return _u
}

// SetInteractionType sets the "interaction_type" field.
func (_u *ProductInteractionUpdate) SetInteractionType(v string) *ProductInteractionUpdate {
	_u.mutation.SetInteractionType(v)
	return _u
}

// SetNillableInteractionType sets the "interaction_type" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillableInteractionType(v *string) *ProductInteractionUpdate {
	if v != nil {
		_u.SetInteractionType(*v)
	}
	return _u
}

// SetMessagePosition sets the "message_position" field.
func (_u *ProductInteractionUpdate) SetMessagePosition(v int) *ProductInteractionUpdate {
	_u.mutation.ResetMessagePosition()
	_u.mutation.SetMessagePosition(v)
	return _u
}

// SetNillableMessagePosition sets the "message_position" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillableMessagePosition(v *int) *ProductInteractionUpdate {
	if v != nil {
		_u.SetMessagePosition(*v)
	}
	return _u
}

// AddMessagePosition adds value to the "message_position" field.
func (_u *ProductInteractionUpdate) AddMessagePosition(v int) *ProductInteractionUpdate {
	_u.mutation.AddMessagePosition(v)
	return _u
}

// SetViewDurationSeconds sets the "view_duration_seconds" field.
func (_u *ProductInteractionUpdate) SetViewDurationSeconds(v int) *ProductInteractionUpdate {
	_u.mutation.ResetViewDurationSeconds()
	_u.mutation.SetViewDurationSeconds(v)
	return _u
}

// SetNillableViewDurationSeconds sets the "view_duration_seconds" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillableViewDurationSeconds(v *int) *ProductInteractionUpdate {
	if v != nil {
		_u.SetViewDurationSeconds(*v)
	}
	return _u
}

// AddViewDurationSeconds adds value to the "view_duration_seconds" field.
func (_u *ProductInteractionUpdate) AddViewDurationSeconds(v int) *ProductInteractionUpdate {
	_u.mutation.AddViewDurationSeconds(v)
	return _u
}

// SetClickCount sets the "click_count" field.
func (_u *ProductInteractionUpdate) SetClickCount(v int) *ProductInteractionUpdate {
	_u.mutation.ResetClickCount()
	_u.mutation.SetClickCount(v)
	return _u
}

// SetNillableClickCount sets the "click_count" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillableClickCount(v *int) *ProductInteractionUpdate {
	if v != nil {
		_u.SetClickCount(*v)
	}
	return _u
}

// AddClickCount adds value to the "click_count" field.
func (_u *ProductInteractionUpdate) AddClickCount(v int) *ProductInteractionUpdate {
	_u.mutation.AddClickCount(v)
	return _u
}

// SetOpenedDetails sets the "opened_details" field.
func (_u *ProductInteractionUpdate) SetOpenedDetails(v bool) *ProductInteractionUpdate {
	_u.mutation.SetOpenedDetails(v)
	return _u
}

// SetNillableOpenedDetails sets the "opened_details" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillableOpenedDetails(v *bool) *ProductInteractionUpdate {
	if v != nil {
		_u.SetOpenedDetails(*v)
	}
	return _u
}

// SetAddedToComparison sets the "added_to_comparison" field.
func (_u *ProductInteractionUpdate) SetAddedToComparison(v bool) *ProductInteractionUpdate {
	_u.mutation.SetAddedToComparison(v)
	return _u
}

// SetNillableAddedToComparison sets the "added_to_comparison" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillableAddedToComparison(v *bool) *ProductInteractionUpdate {
	if v != nil {
		_u.SetAddedToComparison(*v)
	}
	return _u
}

// SetFeedback sets the "feedback" field.
func (_u *ProductInteractionUpdate) SetFeedback(v string) *ProductInteractionUpdate {
	_u.mutation.SetFeedback(v)
	return _u
}

// SetNillableFeedback sets the "feedback" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillableFeedback(v *string) *ProductInteractionUpdate {
	if v != nil {
		_u.SetFeedback(*v)
	}
	return _u
}

// ClearFeedback clears the value of the "feedback" field.
func (_u *ProductInteractionUpdate) ClearFeedback() *ProductInteractionUpdate {
	_u.mutation.ClearFeedback()
	return _u
}

// SetImplicitScore sets the "implicit_score" field.
func (_u *ProductInteractionUpdate) SetImplicitScore(v float64) *ProductInteractionUpdate {
	_u.mutation.ResetImplicitScore()
	_u.mutation.SetImplicitScore(v)
	return _u
}

// SetNillableImplicitScore sets the "implicit_score" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillableImplicitScore(v *float64) *ProductInteractionUpdate {
	if v != nil {
		_u.SetImplicitScore(*v)
	}
	return _u
}

// AddImplicitScore adds value to the "implicit_score" field.
func (_u *ProductInteractionUpdate) AddImplicitScore(v float64) *ProductInteractionUpdate {
	_u.mutation.AddImplicitScore(v)
	return _u
}

// SetSearchQuery sets the "search_query" field.
func (_u *ProductInteractionUpdate) SetSearchQuery(v string) *ProductInteractionUpdate {
	_u.mutation.SetSearchQuery(v)
	return _u
}

// SetNillableSearchQuery sets the "search_query" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillableSearchQuery(v *string) *ProductInteractionUpdate {
	if v != nil {
		_u.SetSearchQuery(*v)
	}
	return _u
}

// ClearSearchQuery clears the value of the "search_query" field.
func (_u *ProductInteractionUpdate) ClearSearchQuery() *ProductInteractionUpdate {
	_u.mutation.ClearSearchQuery()
	return _u
}

// SetSearchType sets the "search_type" field.
func (_u *ProductInteractionUpdate) SetSearchType(v string) *ProductInteractionUpdate {
	_u.mutation.SetSearchType(v)
	return _u
}

// SetNillableSearchType sets the "search_type" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillableSearchType(v *string) *ProductInteractionUpdate {
	if v != nil {
		_u.SetSearchType(*v)
	}
	return _u
}

// ClearSearchType clears the value of the "search_type" field.
func (_u *ProductInteractionUpdate) ClearSearchType() *ProductInteractionUpdate {
	_u.mutation.ClearSearchType()
	return _u
}

// SetPositionInResults sets the "position_in_results" field.
func (_u *ProductInteractionUpdate) SetPositionInResults(v int) *ProductInteractionUpdate {
	_u.mutation.ResetPositionInResults()
	_u.mutation.SetPositionInResults(v)
	return _u
}

// SetNillablePositionInResults sets the "position_in_results" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillablePositionInResults(v *int) *ProductInteractionUpdate {
	if v != nil {
		_u.SetPositionInResults(*v)
	}
	return _u
}

// AddPositionInResults adds value to the "position_in_results" field.
func (_u *ProductInteractionUpdate) AddPositionInResults(v int) *ProductInteractionUpdate {
	_u.mutation.AddPositionInResults(v)
	return _u
}

// SetInteractionSequence sets the "interaction_sequence" field.
func (_u *ProductInteractionUpdate) SetInteractionSequence(v int) *ProductInteractionUpdate {
	_u.mutation.ResetInteractionSequence()
	_u.mutation.SetInteractionSequence(v)
	return _u
}

// SetNillableInteractionSequence sets the "interaction_sequence" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillableInteractionSequence(v *int) *ProductInteractionUpdate {
	if v != nil {
		_u.SetInteractionSequence(*v)
	}
	return _u
}

// AddInteractionSequence adds value to the "interaction_sequence" field.
func (_u *ProductInteractionUpdate) AddInteractionSequence(v int) *ProductInteractionUpdate {
	_u.mutation.AddInteractionSequence(v)
	return _u
}

// SetInteractedAt sets the "interacted_at" field.
func (_u *ProductInteractionUpdate) SetInteractedAt(v time.Time) *ProductInteractionUpdate {
	_u.mutation.SetInteractedAt(v)
	return _u
}

// SetNillableInteractedAt sets the "interacted_at" field if the given value is not nil.
func (_u *ProductInteractionUpdate) SetNillableInteractedAt(v *time.Time) *ProductInteractionUpdate {
	if v != nil {
		_u.SetInteractedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProductInteractionUpdate) SetUpdatedAt(v time.Time) *ProductInteractionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ProductInteractionUpdate) SetUser(v *User) *ProductInteractionUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ProductInteractionMutation object of the builder.
func (_u *ProductInteractionUpdate) Mutation() *ProductInteractionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ProductInteractionUpdate) ClearUser() *ProductInteractionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProductInteractionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductInteractionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProductInteractionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductInteractionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProductInteractionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := productinteraction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductInteractionUpdate) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := productinteraction.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "ProductInteraction.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductID(); ok {
		if err := productinteraction.ProductIDValidator(v); err != nil {
			return &ValidationError{Name: "product_id", err: fmt.Errorf(`ent: validator failed for field "ProductInteraction.product_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductName(); ok {
		if err := productinteraction.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "ProductInteraction.product_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InteractionType(); ok {
		if err := productinteraction.InteractionTypeValidator(v); err != nil {
			return &ValidationError{Name: "interaction_type", err: fmt.Errorf(`ent: validator failed for field "ProductInteraction.interaction_type": %w`, err)}
		}
	}
	return nil
}

func (_u *ProductInteractionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(productinteraction.Table, productinteraction.Columns, sqlgraph.NewFieldSpec(productinteraction.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(productinteraction.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(productinteraction.FieldProductID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(productinteraction.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductPrice(); ok {
		_spec.SetField(productinteraction.FieldProductPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProductPrice(); ok {
		_spec.AddField(productinteraction.FieldProductPrice, field.TypeFloat64, value)
	}
	if _u.mutation.ProductPriceCleared() {
		_spec.ClearField(productinteraction.FieldProductPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ProductCurrency(); ok {
		_spec.SetField(productinteraction.FieldProductCurrency, field.TypeString, value)
	}
	if _u.mutation.ProductCurrencyCleared() {
		_spec.ClearField(productinteraction.FieldProductCurrency, field.TypeString)
	}
	if value, ok := _u.mutation.ProductCategory(); ok {
		_spec.SetField(productinteraction.FieldProductCategory, field.TypeString, value)
	}
	if _u.mutation.ProductCategoryCleared() {
		_spec.ClearField(productinteraction.FieldProductCategory, field.TypeString)
	}
	if value, ok := _u.mutation.ProductBrand(); ok {
		_spec.SetField(productinteraction.FieldProductBrand, field.TypeString, value)
	}
	if _u.mutation.ProductBrandCleared() {
		_spec.ClearField(productinteraction.FieldProductBrand, field.TypeString)
	}
	if value, ok := _u.mutation.ProductURL(); ok {
		_spec.SetField(productinteraction.FieldProductURL, field.TypeString, value)
	}
	if _u.mutation.ProductURLCleared() {
		_spec.ClearField(productinteraction.FieldProductURL, field.TypeString)
	}
	if value, ok := _u.mutation.ProductData(); ok {
		_spec.SetField(productinteraction.FieldProductData, field.TypeJSON, value)
	}
	if _u.mutation.ProductDataCleared() {
		_spec.ClearField(productinteraction.FieldProductData, field.TypeJSON)
	}
	if value, ok := _u.mutation.InteractionType(); ok {
		_spec.SetField(productinteraction.FieldInteractionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessagePosition(); ok {
		_spec.SetField(productinteraction.FieldMessagePosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessagePosition(); ok {
		_spec.AddField(productinteraction.FieldMessagePosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ViewDurationSeconds(); ok {
		_spec.SetField(productinteraction.FieldViewDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewDurationSeconds(); ok {
		_spec.AddField(productinteraction.FieldViewDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ClickCount(); ok {
		_spec.SetField(productinteraction.FieldClickCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedClickCount(); ok {
		_spec.AddField(productinteraction.FieldClickCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OpenedDetails(); ok {
		_spec.SetField(productinteraction.FieldOpenedDetails, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AddedToComparison(); ok {
		_spec.SetField(productinteraction.FieldAddedToComparison, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Feedback(); ok {
		_spec.SetField(productinteraction.FieldFeedback, field.TypeString, value)
	}
	if _u.mutation.FeedbackCleared() {
		_spec.ClearField(productinteraction.FieldFeedback, field.TypeString)
	}
	if value, ok := _u.mutation.ImplicitScore(); ok {
		_spec.SetField(productinteraction.FieldImplicitScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImplicitScore(); ok {
		_spec.AddField(productinteraction.FieldImplicitScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SearchQuery(); ok {
		_spec.SetField(productinteraction.FieldSearchQuery, field.TypeString, value)
	}
	if _u.mutation.SearchQueryCleared() {
		_spec.ClearField(productinteraction.FieldSearchQuery, field.TypeString)
	}
	if value, ok := _u.mutation.SearchType(); ok {
		_spec.SetField(productinteraction.FieldSearchType, field.TypeString, value)
	}
	if _u.mutation.SearchTypeCleared() {
		_spec.ClearField(productinteraction.FieldSearchType, field.TypeString)
	}
	if value, ok := _u.mutation.PositionInResults(); ok {
		_spec.SetField(productinteraction.FieldPositionInResults, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPositionInResults(); ok {
		_spec.AddField(productinteraction.FieldPositionInResults, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InteractionSequence(); ok {
		_spec.SetField(productinteraction.FieldInteractionSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInteractionSequence(); ok {
		_spec.AddField(productinteraction.FieldInteractionSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InteractedAt(); ok {
		_spec.SetField(productinteraction.FieldInteractedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(productinteraction.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   productinteraction.UserTable,
			Columns: []string{productinteraction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   productinteraction.UserTable,
			Columns: []string{productinteraction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productinteraction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProductInteractionUpdateOne is the builder for updating a single ProductInteraction entity.
type ProductInteractionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductInteractionMutation
}

// SetUserID sets the "user_id" field.
func (_u *ProductInteractionUpdateOne) SetUserID(v uuid.UUID) *ProductInteractionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillableUserID(v *uuid.UUID) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ProductInteractionUpdateOne) ClearUserID() *ProductInteractionUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *ProductInteractionUpdateOne) SetSessionID(v string) *ProductInteractionUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillableSessionID(v *string) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *ProductInteractionUpdateOne) SetProductID(v string) *ProductInteractionUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillableProductID(v *string) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *ProductInteractionUpdateOne) SetProductName(v string) *ProductInteractionUpdateOne {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillableProductName(v *string) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetProductPrice sets the "product_price" field.
func (_u *ProductInteractionUpdateOne) SetProductPrice(v float64) *ProductInteractionUpdateOne {
	_u.mutation.ResetProductPrice()
	_u.mutation.SetProductPrice(v)
	return _u
}

// SetNillableProductPrice sets the "product_price" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillableProductPrice(v *float64) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetProductPrice(*v)
	}
	return _u
}

// AddProductPrice adds value to the "product_price" field.
func (_u *ProductInteractionUpdateOne) AddProductPrice(v float64) *ProductInteractionUpdateOne {
	_u.mutation.AddProductPrice(v)
	return _u
}

// ClearProductPrice clears the value of the "product_price" field.
func (_u *ProductInteractionUpdateOne) ClearProductPrice() *ProductInteractionUpdateOne {
	_u.mutation.ClearProductPrice()
	return _u
}

// SetProductCurrency sets the "product_currency" field.
func (_u *ProductInteractionUpdateOne) SetProductCurrency(v string) *ProductInteractionUpdateOne {
	_u.mutation.SetProductCurrency(v)
	return _u
}

// SetNillableProductCurrency sets the "product_currency" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillableProductCurrency(v *string) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetProductCurrency(*v)
	}
	return _u
}

// ClearProductCurrency clears the value of the "product_currency" field.
func (_u *ProductInteractionUpdateOne) ClearProductCurrency() *ProductInteractionUpdateOne {
	_u.mutation.ClearProductCurrency()
	return _u
}

// SetProductCategory sets the "product_category" field.
func (_u *ProductInteractionUpdateOne) SetProductCategory(v string) *ProductInteractionUpdateOne {
	_u.mutation.SetProductCategory(v)
	return _u
}

// SetNillableProductCategory sets the "product_category" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillableProductCategory(v *string) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetProductCategory(*v)
	}
	return _u
}

// ClearProductCategory clears the value of the "product_category" field.
func (_u *ProductInteractionUpdateOne) ClearProductCategory() *ProductInteractionUpdateOne {
	_u.mutation.ClearProductCategory()
	return _u
}

// SetProductBrand sets the "product_brand" field.
func (_u *ProductInteractionUpdateOne) SetProductBrand(v string) *ProductInteractionUpdateOne {
	_u.mutation.SetProductBrand(v)
	return _u
}

// SetNillableProductBrand sets the "product_brand" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillableProductBrand(v *string) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetProductBrand(*v)
	}
	return _u
}

// ClearProductBrand clears the value of the "product_brand" field.
func (_u *ProductInteractionUpdateOne) ClearProductBrand() *ProductInteractionUpdateOne {
	_u.mutation.ClearProductBrand()
	return _u
}

// SetProductURL sets the "product_url" field.
func (_u *ProductInteractionUpdateOne) SetProductURL(v string) *ProductInteractionUpdateOne {
	_u.mutation.SetProductURL(v)
	return _u
}

// SetNillableProductURL sets the "product_url" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillableProductURL(v *string) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetProductURL(*v)
	}
	return _u
}

// ClearProductURL clears the value of the "product_url" field.
func (_u *ProductInteractionUpdateOne) ClearProductURL() *ProductInteractionUpdateOne {
	_u.mutation.ClearProductURL()
	return _u
}

// SetProductData sets the "product_data" field.
func (_u *ProductInteractionUpdateOne) SetProductData(v map[string]interface{}) *ProductInteractionUpdateOne {
	_u.mutation.SetProductData(v)
	return _u
}

// ClearProductData clears the value of the "product_data" field.
func (_u *ProductInteractionUpdateOne) ClearProductData() *ProductInteractionUpdateOne {
	_u.mutation.ClearProductData()
	return _u
}

// SetInteractionType sets the "interaction_type" field.
func (_u *ProductInteractionUpdateOne) SetInteractionType(v string) *ProductInteractionUpdateOne {
	_u.mutation.SetInteractionType(v)
	return _u
}

// SetNillableInteractionType sets the "interaction_type" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillableInteractionType(v *string) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetInteractionType(*v)
	}
	return _u
}

// SetMessagePosition sets the "message_position" field.
func (_u *ProductInteractionUpdateOne) SetMessagePosition(v int) *ProductInteractionUpdateOne {
	_u.mutation.ResetMessagePosition()
	_u.mutation.SetMessagePosition(v)
	return _u
}

// SetNillableMessagePosition sets the "message_position" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillableMessagePosition(v *int) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetMessagePosition(*v)
	}
	return _u
}

// AddMessagePosition adds value to the "message_position" field.
func (_u *ProductInteractionUpdateOne) AddMessagePosition(v int) *ProductInteractionUpdateOne {
	_u.mutation.AddMessagePosition(v)
	return _u
}

// SetViewDurationSeconds sets the "view_duration_seconds" field.
func (_u *ProductInteractionUpdateOne) SetViewDurationSeconds(v int) *ProductInteractionUpdateOne {
	_u.mutation.ResetViewDurationSeconds()
	_u.mutation.SetViewDurationSeconds(v)
	return _u
}

// SetNillableViewDurationSeconds sets the "view_duration_seconds" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillableViewDurationSeconds(v *int) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetViewDurationSeconds(*v)
	}
	return _u
}

// AddViewDurationSeconds adds value to the "view_duration_seconds" field.
func (_u *ProductInteractionUpdateOne) AddViewDurationSeconds(v int) *ProductInteractionUpdateOne {
	_u.mutation.AddViewDurationSeconds(v)
	return _u
}

// SetClickCount sets the "click_count" field.
func (_u *ProductInteractionUpdateOne) SetClickCount(v int) *ProductInteractionUpdateOne {
	_u.mutation.ResetClickCount()
	_u.mutation.SetClickCount(v)
	return _u
}

// SetNillableClickCount sets the "click_count" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillableClickCount(v *int) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetClickCount(*v)
	}
	return _u
}

// AddClickCount adds value to the "click_count" field.
func (_u *ProductInteractionUpdateOne) AddClickCount(v int) *ProductInteractionUpdateOne {
	_u.mutation.AddClickCount(v)
	return _u
}

// SetOpenedDetails sets the "opened_details" field.
func (_u *ProductInteractionUpdateOne) SetOpenedDetails(v bool) *ProductInteractionUpdateOne {
	_u.mutation.SetOpenedDetails(v)
	return _u
}

// SetNillableOpenedDetails sets the "opened_details" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillableOpenedDetails(v *bool) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetOpenedDetails(*v)
	}
	return _u
}

// SetAddedToComparison sets the "added_to_comparison" field.
func (_u *ProductInteractionUpdateOne) SetAddedToComparison(v bool) *ProductInteractionUpdateOne {
	_u.mutation.SetAddedToComparison(v)
	return _u
}

// SetNillableAddedToComparison sets the "added_to_comparison" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillableAddedToComparison(v *bool) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetAddedToComparison(*v)
	}
	return _u
}

// SetFeedback sets the "feedback" field.
func (_u *ProductInteractionUpdateOne) SetFeedback(v string) *ProductInteractionUpdateOne {
	_u.mutation.SetFeedback(v)
	return _u
}

// SetNillableFeedback sets the "feedback" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillableFeedback(v *string) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetFeedback(*v)
	}
	return _u
}

// ClearFeedback clears the value of the "feedback" field.
func (_u *ProductInteractionUpdateOne) ClearFeedback() *ProductInteractionUpdateOne {
	_u.mutation.ClearFeedback()
	return _u
}

// SetImplicitScore sets the "implicit_score" field.
func (_u *ProductInteractionUpdateOne) SetImplicitScore(v float64) *ProductInteractionUpdateOne {
	_u.mutation.ResetImplicitScore()
	_u.mutation.SetImplicitScore(v)
	return _u
}

// SetNillableImplicitScore sets the "implicit_score" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillableImplicitScore(v *float64) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetImplicitScore(*v)
	}
	return _u
}

// AddImplicitScore adds value to the "implicit_score" field.
func (_u *ProductInteractionUpdateOne) AddImplicitScore(v float64) *ProductInteractionUpdateOne {
	_u.mutation.AddImplicitScore(v)
	return _u
}

// SetSearchQuery sets the "search_query" field.
func (_u *ProductInteractionUpdateOne) SetSearchQuery(v string) *ProductInteractionUpdateOne {
	_u.mutation.SetSearchQuery(v)
	return _u
}

// SetNillableSearchQuery sets the "search_query" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillableSearchQuery(v *string) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetSearchQuery(*v)
	}
	return _u
}

// ClearSearchQuery clears the value of the "search_query" field.
func (_u *ProductInteractionUpdateOne) ClearSearchQuery() *ProductInteractionUpdateOne {
	_u.mutation.ClearSearchQuery()
	return _u
}

// SetSearchType sets the "search_type" field.
func (_u *ProductInteractionUpdateOne) SetSearchType(v string) *ProductInteractionUpdateOne {
	_u.mutation.SetSearchType(v)
	return _u
}

// SetNillableSearchType sets the "search_type" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillableSearchType(v *string) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetSearchType(*v)
	}
	return _u
}

// ClearSearchType clears the value of the "search_type" field.
func (_u *ProductInteractionUpdateOne) ClearSearchType() *ProductInteractionUpdateOne {
	_u.mutation.ClearSearchType()
	return _u
}

// SetPositionInResults sets the "position_in_results" field.
func (_u *ProductInteractionUpdateOne) SetPositionInResults(v int) *ProductInteractionUpdateOne {
	_u.mutation.ResetPositionInResults()
	_u.mutation.SetPositionInResults(v)
	return _u
}

// SetNillablePositionInResults sets the "position_in_results" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillablePositionInResults(v *int) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetPositionInResults(*v)
	}
	return _u
}

// AddPositionInResults adds value to the "position_in_results" field.
func (_u *ProductInteractionUpdateOne) AddPositionInResults(v int) *ProductInteractionUpdateOne {
	_u.mutation.AddPositionInResults(v)
	return _u
}

// SetInteractionSequence sets the "interaction_sequence" field.
func (_u *ProductInteractionUpdateOne) SetInteractionSequence(v int) *ProductInteractionUpdateOne {
	_u.mutation.ResetInteractionSequence()
	_u.mutation.SetInteractionSequence(v)
	return _u
}

// SetNillableInteractionSequence sets the "interaction_sequence" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillableInteractionSequence(v *int) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetInteractionSequence(*v)
	}
	return _u
}

// AddInteractionSequence adds value to the "interaction_sequence" field.
func (_u *ProductInteractionUpdateOne) AddInteractionSequence(v int) *ProductInteractionUpdateOne {
	_u.mutation.AddInteractionSequence(v)
	return _u
}

// SetInteractedAt sets the "interacted_at" field.
func (_u *ProductInteractionUpdateOne) SetInteractedAt(v time.Time) *ProductInteractionUpdateOne {
	_u.mutation.SetInteractedAt(v)
	return _u
}

// SetNillableInteractedAt sets the "interacted_at" field if the given value is not nil.
func (_u *ProductInteractionUpdateOne) SetNillableInteractedAt(v *time.Time) *ProductInteractionUpdateOne {
	if v != nil {
		_u.SetInteractedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProductInteractionUpdateOne) SetUpdatedAt(v time.Time) *ProductInteractionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ProductInteractionUpdateOne) SetUser(v *User) *ProductInteractionUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ProductInteractionMutation object of the builder.
func (_u *ProductInteractionUpdateOne) Mutation() *ProductInteractionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ProductInteractionUpdateOne) ClearUser() *ProductInteractionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the ProductInteractionUpdate builder.
func (_u *ProductInteractionUpdateOne) Where(ps ...predicate.ProductInteraction) *ProductInteractionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProductInteractionUpdateOne) Select(field string, fields ...string) *ProductInteractionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProductInteraction entity.
func (_u *ProductInteractionUpdateOne) Save(ctx context.Context) (*ProductInteraction, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductInteractionUpdateOne) SaveX(ctx context.Context) *ProductInteraction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProductInteractionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductInteractionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProductInteractionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := productinteraction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductInteractionUpdateOne) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := productinteraction.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "ProductInteraction.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductID(); ok {
		if err := productinteraction.ProductIDValidator(v); err != nil {
			return &ValidationError{Name: "product_id", err: fmt.Errorf(`ent: validator failed for field "ProductInteraction.product_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductName(); ok {
		if err := productinteraction.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "ProductInteraction.product_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InteractionType(); ok {
		if err := productinteraction.InteractionTypeValidator(v); err != nil {
			return &ValidationError{Name: "interaction_type", err: fmt.Errorf(`ent: validator failed for field "ProductInteraction.interaction_type": %w`, err)}
		}
	}
	return nil
}

func (_u *ProductInteractionUpdateOne) sqlSave(ctx context.Context) (_node *ProductInteraction, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(productinteraction.Table, productinteraction.Columns, sqlgraph.NewFieldSpec(productinteraction.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProductInteraction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productinteraction.FieldID)
		for _, f := range fields {
			if !productinteraction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != productinteraction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(productinteraction.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(productinteraction.FieldProductID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(productinteraction.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductPrice(); ok {
		_spec.SetField(productinteraction.FieldProductPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProductPrice(); ok {
		_spec.AddField(productinteraction.FieldProductPrice, field.TypeFloat64, value)
	}
	if _u.mutation.ProductPriceCleared() {
		_spec.ClearField(productinteraction.FieldProductPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ProductCurrency(); ok {
		_spec.SetField(productinteraction.FieldProductCurrency, field.TypeString, value)
	}
	if _u.mutation.ProductCurrencyCleared() {
		_spec.ClearField(productinteraction.FieldProductCurrency, field.TypeString)
	}
	if value, ok := _u.mutation.ProductCategory(); ok {
		_spec.SetField(productinteraction.FieldProductCategory, field.TypeString, value)
	}
	if _u.mutation.ProductCategoryCleared() {
		_spec.ClearField(productinteraction.FieldProductCategory, field.TypeString)
	}
	if value, ok := _u.mutation.ProductBrand(); ok {
		_spec.SetField(productinteraction.FieldProductBrand, field.TypeString, value)
	}
	if _u.mutation.ProductBrandCleared() {
		_spec.ClearField(productinteraction.FieldProductBrand, field.TypeString)
	}
	if value, ok := _u.mutation.ProductURL(); ok {
		_spec.SetField(productinteraction.FieldProductURL, field.TypeString, value)
	}
	if _u.mutation.ProductURLCleared() {
		_spec.ClearField(productinteraction.FieldProductURL, field.TypeString)
	}
	if value, ok := _u.mutation.ProductData(); ok {
		_spec.SetField(productinteraction.FieldProductData, field.TypeJSON, value)
	}
	if _u.mutation.ProductDataCleared() {
		_spec.ClearField(productinteraction.FieldProductData, field.TypeJSON)
	}
	if value, ok := _u.mutation.InteractionType(); ok {
		_spec.SetField(productinteraction.FieldInteractionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessagePosition(); ok {
		_spec.SetField(productinteraction.FieldMessagePosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessagePosition(); ok {
		_spec.AddField(productinteraction.FieldMessagePosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ViewDurationSeconds(); ok {
		_spec.SetField(productinteraction.FieldViewDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewDurationSeconds(); ok {
		_spec.AddField(productinteraction.FieldViewDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ClickCount(); ok {
		_spec.SetField(productinteraction.FieldClickCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedClickCount(); ok {
		_spec.AddField(productinteraction.FieldClickCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OpenedDetails(); ok {
		_spec.SetField(productinteraction.FieldOpenedDetails, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AddedToComparison(); ok {
		_spec.SetField(productinteraction.FieldAddedToComparison, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Feedback(); ok {
		_spec.SetField(productinteraction.FieldFeedback, field.TypeString, value)
	}
	if _u.mutation.FeedbackCleared() {
		_spec.ClearField(productinteraction.FieldFeedback, field.TypeString)
	}
	if value, ok := _u.mutation.ImplicitScore(); ok {
		_spec.SetField(productinteraction.FieldImplicitScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImplicitScore(); ok {
		_spec.AddField(productinteraction.FieldImplicitScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SearchQuery(); ok {
		_spec.SetField(productinteraction.FieldSearchQuery, field.TypeString, value)
	}
	if _u.mutation.SearchQueryCleared() {
		_spec.ClearField(productinteraction.FieldSearchQuery, field.TypeString)
	}
	if value, ok := _u.mutation.SearchType(); ok {
		_spec.SetField(productinteraction.FieldSearchType, field.TypeString, value)
	}
	if _u.mutation.SearchTypeCleared() {
		_spec.ClearField(productinteraction.FieldSearchType, field.TypeString)
	}
	if value, ok := _u.mutation.PositionInResults(); ok {
		_spec.SetField(productinteraction.FieldPositionInResults, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPositionInResults(); ok {
		_spec.AddField(productinteraction.FieldPositionInResults, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InteractionSequence(); ok {
		_spec.SetField(productinteraction.FieldInteractionSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInteractionSequence(); ok {
		_spec.AddField(productinteraction.FieldInteractionSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InteractedAt(); ok {
		_spec.SetField(productinteraction.FieldInteractedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(productinteraction.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   productinteraction.UserTable,
			Columns: []string{productinteraction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   productinteraction.UserTable,
			Columns: []string{productinteraction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProductInteraction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productinteraction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
