// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"mylittleprice/ent/searchhistory"
	"mylittleprice/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// SearchHistory is the model entity for the SearchHistory schema.
type SearchHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// SearchQuery holds the value of the "search_query" field.
	SearchQuery string `json:"search_query,omitempty"`
	// OptimizedQuery holds the value of the "optimized_query" field.
	OptimizedQuery string `json:"optimized_query,omitempty"`
	// SearchType holds the value of the "search_type" field.
	SearchType string `json:"search_type,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// CountryCode holds the value of the "country_code" field.
	CountryCode string `json:"country_code,omitempty"`
	// LanguageCode holds the value of the "language_code" field.
	LanguageCode string `json:"language_code,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// ResultCount holds the value of the "result_count" field.
	ResultCount int `json:"result_count,omitempty"`
	// ProductsFound holds the value of the "products_found" field.
	ProductsFound []map[string]interface{} `json:"products_found,omitempty"`
	// ClickedProductID holds the value of the "clicked_product_id" field.
	ClickedProductID string `json:"clicked_product_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SearchHistoryQuery when eager-loading is set.
	Edges        SearchHistoryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SearchHistoryEdges holds the relations/edges for other nodes in the graph.
type SearchHistoryEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SearchHistoryEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SearchHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case searchhistory.FieldProductsFound:
			values[i] = new([]byte)
		case searchhistory.FieldResultCount:
			values[i] = new(sql.NullInt64)
		case searchhistory.FieldSessionID, searchhistory.FieldSearchQuery, searchhistory.FieldOptimizedQuery, searchhistory.FieldSearchType, searchhistory.FieldCategory, searchhistory.FieldCountryCode, searchhistory.FieldLanguageCode, searchhistory.FieldCurrency, searchhistory.FieldClickedProductID:
			values[i] = new(sql.NullString)
		case searchhistory.FieldCreatedAt, searchhistory.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		case searchhistory.FieldID, searchhistory.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SearchHistory fields.
func (_m *SearchHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case searchhistory.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case searchhistory.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case searchhistory.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case searchhistory.FieldSearchQuery:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field search_query", values[i])
			} else if value.Valid {
				_m.SearchQuery = value.String
			}
		case searchhistory.FieldOptimizedQuery:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field optimized_query", values[i])
			} else if value.Valid {
				_m.OptimizedQuery = value.String
			}
		case searchhistory.FieldSearchType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field search_type", values[i])
			} else if value.Valid {
				_m.SearchType = value.String
			}
		case searchhistory.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case searchhistory.FieldCountryCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country_code", values[i])
			} else if value.Valid {
				_m.CountryCode = value.String
			}
		case searchhistory.FieldLanguageCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language_code", values[i])
			} else if value.Valid {
				_m.LanguageCode = value.String
			}
		case searchhistory.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case searchhistory.FieldResultCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field result_count", values[i])
			} else if value.Valid {
				_m.ResultCount = int(value.Int64)
			}
		case searchhistory.FieldProductsFound:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field products_found", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ProductsFound); err != nil {
					return fmt.Errorf("unmarshal field products_found: %w", err)
				}
			}
		case searchhistory.FieldClickedProductID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field clicked_product_id", values[i])
			} else if value.Valid {
				_m.ClickedProductID = value.String
			}
		case searchhistory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case searchhistory.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SearchHistory.
// This includes values selected through modifiers, order, etc.
func (_m *SearchHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the SearchHistory entity.
func (_m *SearchHistory) QueryUser() *UserQuery {
	return NewSearchHistoryClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this SearchHistory.
// Note that you need to call SearchHistory.Unwrap() before calling this method if this SearchHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SearchHistory) Update() *SearchHistoryUpdateOne {
	return NewSearchHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SearchHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SearchHistory) Unwrap() *SearchHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SearchHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SearchHistory) String() string {
	var builder strings.Builder
	builder.WriteString("SearchHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("search_query=")
	builder.WriteString(_m.SearchQuery)
	builder.WriteString(", ")
	builder.WriteString("optimized_query=")
	builder.WriteString(_m.OptimizedQuery)
	builder.WriteString(", ")
	builder.WriteString("search_type=")
	builder.WriteString(_m.SearchType)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("country_code=")
	builder.WriteString(_m.CountryCode)
	builder.WriteString(", ")
	builder.WriteString("language_code=")
	builder.WriteString(_m.LanguageCode)
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("result_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResultCount))
	builder.WriteString(", ")
	builder.WriteString("products_found=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProductsFound))
	builder.WriteString(", ")
	builder.WriteString("clicked_product_id=")
	builder.WriteString(_m.ClickedProductID)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SearchHistories is a parsable slice of SearchHistory.
type SearchHistories []*SearchHistory
