// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"mylittleprice/ent/predicate"
	"mylittleprice/ent/searchhistory"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SearchHistoryDelete is the builder for deleting a SearchHistory entity.
type SearchHistoryDelete struct {
	config
	hooks    []Hook
	mutation *SearchHistoryMutation
}

// Where appends a list predicates to the SearchHistoryDelete builder.
func (_d *SearchHistoryDelete) Where(ps ...predicate.SearchHistory) *SearchHistoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SearchHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SearchHistoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SearchHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(searchhistory.Table, sqlgraph.NewFieldSpec(searchhistory.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SearchHistoryDeleteOne is the builder for deleting a single SearchHistory entity.
type SearchHistoryDeleteOne struct {
	_d *SearchHistoryDelete
}

// Where appends a list predicates to the SearchHistoryDelete builder.
func (_d *SearchHistoryDeleteOne) Where(ps ...predicate.SearchHistory) *SearchHistoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SearchHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{searchhistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SearchHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
