// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"mylittleprice/ent/user"
	"mylittleprice/ent/userbehaviorprofile"
	"mylittleprice/ent/userpreference"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash string `json:"-"`
	// GoogleID holds the value of the "google_id" field.
	GoogleID string `json:"google_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// AvatarURL holds the value of the "avatar_url" field.
	AvatarURL string `json:"avatar_url,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// LastLogin holds the value of the "last_login" field.
	LastLogin time.Time `json:"last_login,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Sessions holds the value of the sessions edge.
	Sessions []*ChatSession `json:"sessions,omitempty"`
	// SearchHistory holds the value of the search_history edge.
	SearchHistory []*SearchHistory `json:"search_history,omitempty"`
	// Preferences holds the value of the preferences edge.
	Preferences *UserPreference `json:"preferences,omitempty"`
	// BehaviorProfile holds the value of the behavior_profile edge.
	BehaviorProfile *UserBehaviorProfile `json:"behavior_profile,omitempty"`
	// ConversationAnalytics holds the value of the conversation_analytics edge.
	ConversationAnalytics []*ConversationAnalytics `json:"conversation_analytics,omitempty"`
	// ProductInteractions holds the value of the product_interactions edge.
	ProductInteractions []*ProductInteraction `json:"product_interactions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// SessionsOrErr returns the Sessions value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) SessionsOrErr() ([]*ChatSession, error) {
	if e.loadedTypes[0] {
		return e.Sessions, nil
	}
	return nil, &NotLoadedError{edge: "sessions"}
}

// SearchHistoryOrErr returns the SearchHistory value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) SearchHistoryOrErr() ([]*SearchHistory, error) {
	if e.loadedTypes[1] {
		return e.SearchHistory, nil
	}
	return nil, &NotLoadedError{edge: "search_history"}
}

// PreferencesOrErr returns the Preferences value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) PreferencesOrErr() (*UserPreference, error) {
	if e.Preferences != nil {
		return e.Preferences, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: userpreference.Label}
	}
	return nil, &NotLoadedError{edge: "preferences"}
}

// BehaviorProfileOrErr returns the BehaviorProfile value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) BehaviorProfileOrErr() (*UserBehaviorProfile, error) {
	if e.BehaviorProfile != nil {
		return e.BehaviorProfile, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: userbehaviorprofile.Label}
	}
	return nil, &NotLoadedError{edge: "behavior_profile"}
}

// ConversationAnalyticsOrErr returns the ConversationAnalytics value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ConversationAnalyticsOrErr() ([]*ConversationAnalytics, error) {
	if e.loadedTypes[4] {
		return e.ConversationAnalytics, nil
	}
	return nil, &NotLoadedError{edge: "conversation_analytics"}
}

// ProductInteractionsOrErr returns the ProductInteractions value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ProductInteractionsOrErr() ([]*ProductInteraction, error) {
	if e.loadedTypes[5] {
		return e.ProductInteractions, nil
	}
	return nil, &NotLoadedError{edge: "product_interactions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldEmail, user.FieldPasswordHash, user.FieldGoogleID, user.FieldName, user.FieldAvatarURL, user.FieldProvider:
			values[i] = new(sql.NullString)
		case user.FieldCreatedAt, user.FieldUpdatedAt, user.FieldLastLogin:
			values[i] = new(sql.NullTime)
		case user.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = value.String
			}
		case user.FieldGoogleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field google_id", values[i])
			} else if value.Valid {
				_m.GoogleID = value.String
			}
		case user.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case user.FieldAvatarURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar_url", values[i])
			} else if value.Valid {
				_m.AvatarURL = value.String
			}
		case user.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case user.FieldLastLogin:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_login", values[i])
			} else if value.Valid {
				_m.LastLogin = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySessions queries the "sessions" edge of the User entity.
func (_m *User) QuerySessions() *ChatSessionQuery {
	return NewUserClient(_m.config).QuerySessions(_m)
}

// QuerySearchHistory queries the "search_history" edge of the User entity.
func (_m *User) QuerySearchHistory() *SearchHistoryQuery {
	return NewUserClient(_m.config).QuerySearchHistory(_m)
}

// QueryPreferences queries the "preferences" edge of the User entity.
func (_m *User) QueryPreferences() *UserPreferenceQuery {
	return NewUserClient(_m.config).QueryPreferences(_m)
}

// QueryBehaviorProfile queries the "behavior_profile" edge of the User entity.
func (_m *User) QueryBehaviorProfile() *UserBehaviorProfileQuery {
	return NewUserClient(_m.config).QueryBehaviorProfile(_m)
}

// QueryConversationAnalytics queries the "conversation_analytics" edge of the User entity.
func (_m *User) QueryConversationAnalytics() *ConversationAnalyticsQuery {
	return NewUserClient(_m.config).QueryConversationAnalytics(_m)
}

// QueryProductInteractions queries the "product_interactions" edge of the User entity.
func (_m *User) QueryProductInteractions() *ProductInteractionQuery {
	return NewUserClient(_m.config).QueryProductInteractions(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("password_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("google_id=")
	builder.WriteString(_m.GoogleID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("avatar_url=")
	builder.WriteString(_m.AvatarURL)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_login=")
	builder.WriteString(_m.LastLogin.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
