// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChatSessionsColumns holds the columns for the "chat_sessions" table.
	ChatSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "session_id", Type: field.TypeString, Unique: true},
		{Name: "country_code", Type: field.TypeString, Default: "US"},
		{Name: "language_code", Type: field.TypeString, Default: "en"},
		{Name: "currency", Type: field.TypeString, Default: "USD"},
		{Name: "message_count", Type: field.TypeInt, Default: 0},
		{Name: "search_state", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "cycle_state", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "conversation_context", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUUID, Nullable: true},
	}
	// ChatSessionsTable holds the schema information for the "chat_sessions" table.
	ChatSessionsTable = &schema.Table{
		Name:       "chat_sessions",
		Columns:    ChatSessionsColumns,
		PrimaryKey: []*schema.Column{ChatSessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "chat_sessions_users_sessions",
				Columns:    []*schema.Column{ChatSessionsColumns[12]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// MessagesColumns holds the columns for the "messages" table.
	MessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "role", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "response_type", Type: field.TypeString, Nullable: true},
		{Name: "quick_replies", Type: field.TypeJSON, Nullable: true},
		{Name: "products", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "search_info", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "session_id", Type: field.TypeUUID},
	}
	// MessagesTable holds the schema information for the "messages" table.
	MessagesTable = &schema.Table{
		Name:       "messages",
		Columns:    MessagesColumns,
		PrimaryKey: []*schema.Column{MessagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "messages_chat_sessions_messages",
				Columns:    []*schema.Column{MessagesColumns[8]},
				RefColumns: []*schema.Column{ChatSessionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SearchHistoriesColumns holds the columns for the "search_histories" table.
	SearchHistoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "session_id", Type: field.TypeString, Nullable: true},
		{Name: "search_query", Type: field.TypeString},
		{Name: "optimized_query", Type: field.TypeString, Nullable: true},
		{Name: "search_type", Type: field.TypeString},
		{Name: "category", Type: field.TypeString, Nullable: true},
		{Name: "country_code", Type: field.TypeString, Default: "US"},
		{Name: "language_code", Type: field.TypeString, Default: "en"},
		{Name: "currency", Type: field.TypeString, Default: "USD"},
		{Name: "result_count", Type: field.TypeInt, Default: 0},
		{Name: "products_found", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "clicked_product_id", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeUUID, Nullable: true},
	}
	// SearchHistoriesTable holds the schema information for the "search_histories" table.
	SearchHistoriesTable = &schema.Table{
		Name:       "search_histories",
		Columns:    SearchHistoriesColumns,
		PrimaryKey: []*schema.Column{SearchHistoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "search_histories_users_search_history",
				Columns:    []*schema.Column{SearchHistoriesColumns[14]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString, Nullable: true},
		{Name: "google_id", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "avatar_url", Type: field.TypeString, Nullable: true},
		{Name: "provider", Type: field.TypeString, Default: "email"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "last_login", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserPreferencesColumns holds the columns for the "user_preferences" table.
	UserPreferencesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "country", Type: field.TypeString, Nullable: true},
		{Name: "currency", Type: field.TypeString, Nullable: true},
		{Name: "language", Type: field.TypeString, Nullable: true},
		{Name: "theme", Type: field.TypeString, Nullable: true},
		{Name: "sidebar_open", Type: field.TypeBool, Nullable: true},
		{Name: "last_active_session_id", Type: field.TypeString, Nullable: true},
		{Name: "saved_search", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUUID, Unique: true},
	}
	// UserPreferencesTable holds the schema information for the "user_preferences" table.
	UserPreferencesTable = &schema.Table{
		Name:       "user_preferences",
		Columns:    UserPreferencesColumns,
		PrimaryKey: []*schema.Column{UserPreferencesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_preferences_users_preferences",
				Columns:    []*schema.Column{UserPreferencesColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChatSessionsTable,
		MessagesTable,
		SearchHistoriesTable,
		UsersTable,
		UserPreferencesTable,
	}
)

func init() {
	ChatSessionsTable.ForeignKeys[0].RefTable = UsersTable
	MessagesTable.ForeignKeys[0].RefTable = ChatSessionsTable
	SearchHistoriesTable.ForeignKeys[0].RefTable = UsersTable
	UserPreferencesTable.ForeignKeys[0].RefTable = UsersTable
}
