// Code generated by ent, DO NOT EDIT.

package productinteraction

import (
	"mylittleprice/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldUserID, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldSessionID, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldProductID, v))
}

// ProductName applies equality check predicate on the "product_name" field. It's identical to ProductNameEQ.
func ProductName(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldProductName, v))
}

// ProductPrice applies equality check predicate on the "product_price" field. It's identical to ProductPriceEQ.
func ProductPrice(v float64) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldProductPrice, v))
}

// ProductCurrency applies equality check predicate on the "product_currency" field. It's identical to ProductCurrencyEQ.
func ProductCurrency(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldProductCurrency, v))
}

// ProductCategory applies equality check predicate on the "product_category" field. It's identical to ProductCategoryEQ.
func ProductCategory(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldProductCategory, v))
}

// ProductBrand applies equality check predicate on the "product_brand" field. It's identical to ProductBrandEQ.
func ProductBrand(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldProductBrand, v))
}

// ProductURL applies equality check predicate on the "product_url" field. It's identical to ProductURLEQ.
func ProductURL(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldProductURL, v))
}

// InteractionType applies equality check predicate on the "interaction_type" field. It's identical to InteractionTypeEQ.
func InteractionType(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldInteractionType, v))
}

// MessagePosition applies equality check predicate on the "message_position" field. It's identical to MessagePositionEQ.
func MessagePosition(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldMessagePosition, v))
}

// ViewDurationSeconds applies equality check predicate on the "view_duration_seconds" field. It's identical to ViewDurationSecondsEQ.
func ViewDurationSeconds(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldViewDurationSeconds, v))
}

// ClickCount applies equality check predicate on the "click_count" field. It's identical to ClickCountEQ.
func ClickCount(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldClickCount, v))
}

// OpenedDetails applies equality check predicate on the "opened_details" field. It's identical to OpenedDetailsEQ.
func OpenedDetails(v bool) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldOpenedDetails, v))
}

// AddedToComparison applies equality check predicate on the "added_to_comparison" field. It's identical to AddedToComparisonEQ.
func AddedToComparison(v bool) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldAddedToComparison, v))
}

// Feedback applies equality check predicate on the "feedback" field. It's identical to FeedbackEQ.
func Feedback(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldFeedback, v))
}

// ImplicitScore applies equality check predicate on the "implicit_score" field. It's identical to ImplicitScoreEQ.
func ImplicitScore(v float64) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldImplicitScore, v))
}

// SearchQuery applies equality check predicate on the "search_query" field. It's identical to SearchQueryEQ.
func SearchQuery(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldSearchQuery, v))
}

// SearchType applies equality check predicate on the "search_type" field. It's identical to SearchTypeEQ.
func SearchType(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldSearchType, v))
}

// PositionInResults applies equality check predicate on the "position_in_results" field. It's identical to PositionInResultsEQ.
func PositionInResults(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldPositionInResults, v))
}

// InteractionSequence applies equality check predicate on the "interaction_sequence" field. It's identical to InteractionSequenceEQ.
func InteractionSequence(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldInteractionSequence, v))
}

// InteractedAt applies equality check predicate on the "interacted_at" field. It's identical to InteractedAtEQ.
func InteractedAt(v time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldInteractedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotNull(FieldUserID))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContainsFold(FieldSessionID, v))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldProductID, vs...))
}

// ProductIDGT applies the GT predicate on the "product_id" field.
func ProductIDGT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldProductID, v))
}

// ProductIDGTE applies the GTE predicate on the "product_id" field.
func ProductIDGTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldProductID, v))
}

// ProductIDLT applies the LT predicate on the "product_id" field.
func ProductIDLT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldProductID, v))
}

// ProductIDLTE applies the LTE predicate on the "product_id" field.
func ProductIDLTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldProductID, v))
}

// ProductIDContains applies the Contains predicate on the "product_id" field.
func ProductIDContains(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContains(FieldProductID, v))
}

// ProductIDHasPrefix applies the HasPrefix predicate on the "product_id" field.
func ProductIDHasPrefix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasPrefix(FieldProductID, v))
}

// ProductIDHasSuffix applies the HasSuffix predicate on the "product_id" field.
func ProductIDHasSuffix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasSuffix(FieldProductID, v))
}

// ProductIDEqualFold applies the EqualFold predicate on the "product_id" field.
func ProductIDEqualFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEqualFold(FieldProductID, v))
}

// ProductIDContainsFold applies the ContainsFold predicate on the "product_id" field.
func ProductIDContainsFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContainsFold(FieldProductID, v))
}

// ProductNameEQ applies the EQ predicate on the "product_name" field.
func ProductNameEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldProductName, v))
}

// ProductNameNEQ applies the NEQ predicate on the "product_name" field.
func ProductNameNEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldProductName, v))
}

// ProductNameIn applies the In predicate on the "product_name" field.
func ProductNameIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldProductName, vs...))
}

// ProductNameNotIn applies the NotIn predicate on the "product_name" field.
func ProductNameNotIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldProductName, vs...))
}

// ProductNameGT applies the GT predicate on the "product_name" field.
func ProductNameGT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldProductName, v))
}

// ProductNameGTE applies the GTE predicate on the "product_name" field.
func ProductNameGTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldProductName, v))
}

// ProductNameLT applies the LT predicate on the "product_name" field.
func ProductNameLT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldProductName, v))
}

// ProductNameLTE applies the LTE predicate on the "product_name" field.
func ProductNameLTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldProductName, v))
}

// ProductNameContains applies the Contains predicate on the "product_name" field.
func ProductNameContains(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContains(FieldProductName, v))
}

// ProductNameHasPrefix applies the HasPrefix predicate on the "product_name" field.
func ProductNameHasPrefix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasPrefix(FieldProductName, v))
}

// ProductNameHasSuffix applies the HasSuffix predicate on the "product_name" field.
func ProductNameHasSuffix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasSuffix(FieldProductName, v))
}

// ProductNameEqualFold applies the EqualFold predicate on the "product_name" field.
func ProductNameEqualFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEqualFold(FieldProductName, v))
}

// ProductNameContainsFold applies the ContainsFold predicate on the "product_name" field.
func ProductNameContainsFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContainsFold(FieldProductName, v))
}

// ProductPriceEQ applies the EQ predicate on the "product_price" field.
func ProductPriceEQ(v float64) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldProductPrice, v))
}

// ProductPriceNEQ applies the NEQ predicate on the "product_price" field.
func ProductPriceNEQ(v float64) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldProductPrice, v))
}

// ProductPriceIn applies the In predicate on the "product_price" field.
func ProductPriceIn(vs ...float64) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldProductPrice, vs...))
}

// ProductPriceNotIn applies the NotIn predicate on the "product_price" field.
func ProductPriceNotIn(vs ...float64) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldProductPrice, vs...))
}

// ProductPriceGT applies the GT predicate on the "product_price" field.
func ProductPriceGT(v float64) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldProductPrice, v))
}

// ProductPriceGTE applies the GTE predicate on the "product_price" field.
func ProductPriceGTE(v float64) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldProductPrice, v))
}

// ProductPriceLT applies the LT predicate on the "product_price" field.
func ProductPriceLT(v float64) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldProductPrice, v))
}

// ProductPriceLTE applies the LTE predicate on the "product_price" field.
func ProductPriceLTE(v float64) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldProductPrice, v))
}

// ProductPriceIsNil applies the IsNil predicate on the "product_price" field.
func ProductPriceIsNil() predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIsNull(FieldProductPrice))
}

// ProductPriceNotNil applies the NotNil predicate on the "product_price" field.
func ProductPriceNotNil() predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotNull(FieldProductPrice))
}

// ProductCurrencyEQ applies the EQ predicate on the "product_currency" field.
func ProductCurrencyEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldProductCurrency, v))
}

// ProductCurrencyNEQ applies the NEQ predicate on the "product_currency" field.
func ProductCurrencyNEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldProductCurrency, v))
}

// ProductCurrencyIn applies the In predicate on the "product_currency" field.
func ProductCurrencyIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldProductCurrency, vs...))
}

// ProductCurrencyNotIn applies the NotIn predicate on the "product_currency" field.
func ProductCurrencyNotIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldProductCurrency, vs...))
}

// ProductCurrencyGT applies the GT predicate on the "product_currency" field.
func ProductCurrencyGT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldProductCurrency, v))
}

// ProductCurrencyGTE applies the GTE predicate on the "product_currency" field.
func ProductCurrencyGTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldProductCurrency, v))
}

// ProductCurrencyLT applies the LT predicate on the "product_currency" field.
func ProductCurrencyLT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldProductCurrency, v))
}

// ProductCurrencyLTE applies the LTE predicate on the "product_currency" field.
func ProductCurrencyLTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldProductCurrency, v))
}

// ProductCurrencyContains applies the Contains predicate on the "product_currency" field.
func ProductCurrencyContains(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContains(FieldProductCurrency, v))
}

// ProductCurrencyHasPrefix applies the HasPrefix predicate on the "product_currency" field.
func ProductCurrencyHasPrefix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasPrefix(FieldProductCurrency, v))
}

// ProductCurrencyHasSuffix applies the HasSuffix predicate on the "product_currency" field.
func ProductCurrencyHasSuffix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasSuffix(FieldProductCurrency, v))
}

// ProductCurrencyIsNil applies the IsNil predicate on the "product_currency" field.
func ProductCurrencyIsNil() predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIsNull(FieldProductCurrency))
}

// ProductCurrencyNotNil applies the NotNil predicate on the "product_currency" field.
func ProductCurrencyNotNil() predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotNull(FieldProductCurrency))
}

// ProductCurrencyEqualFold applies the EqualFold predicate on the "product_currency" field.
func ProductCurrencyEqualFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEqualFold(FieldProductCurrency, v))
}

// ProductCurrencyContainsFold applies the ContainsFold predicate on the "product_currency" field.
func ProductCurrencyContainsFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContainsFold(FieldProductCurrency, v))
}

// ProductCategoryEQ applies the EQ predicate on the "product_category" field.
func ProductCategoryEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldProductCategory, v))
}

// ProductCategoryNEQ applies the NEQ predicate on the "product_category" field.
func ProductCategoryNEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldProductCategory, v))
}

// ProductCategoryIn applies the In predicate on the "product_category" field.
func ProductCategoryIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldProductCategory, vs...))
}

// ProductCategoryNotIn applies the NotIn predicate on the "product_category" field.
func ProductCategoryNotIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldProductCategory, vs...))
}

// ProductCategoryGT applies the GT predicate on the "product_category" field.
func ProductCategoryGT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldProductCategory, v))
}

// ProductCategoryGTE applies the GTE predicate on the "product_category" field.
func ProductCategoryGTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldProductCategory, v))
}

// ProductCategoryLT applies the LT predicate on the "product_category" field.
func ProductCategoryLT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldProductCategory, v))
}

// ProductCategoryLTE applies the LTE predicate on the "product_category" field.
func ProductCategoryLTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldProductCategory, v))
}

// ProductCategoryContains applies the Contains predicate on the "product_category" field.
func ProductCategoryContains(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContains(FieldProductCategory, v))
}

// ProductCategoryHasPrefix applies the HasPrefix predicate on the "product_category" field.
func ProductCategoryHasPrefix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasPrefix(FieldProductCategory, v))
}

// ProductCategoryHasSuffix applies the HasSuffix predicate on the "product_category" field.
func ProductCategoryHasSuffix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasSuffix(FieldProductCategory, v))
}

// ProductCategoryIsNil applies the IsNil predicate on the "product_category" field.
func ProductCategoryIsNil() predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIsNull(FieldProductCategory))
}

// ProductCategoryNotNil applies the NotNil predicate on the "product_category" field.
func ProductCategoryNotNil() predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotNull(FieldProductCategory))
}

// ProductCategoryEqualFold applies the EqualFold predicate on the "product_category" field.
func ProductCategoryEqualFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEqualFold(FieldProductCategory, v))
}

// ProductCategoryContainsFold applies the ContainsFold predicate on the "product_category" field.
func ProductCategoryContainsFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContainsFold(FieldProductCategory, v))
}

// ProductBrandEQ applies the EQ predicate on the "product_brand" field.
func ProductBrandEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldProductBrand, v))
}

// ProductBrandNEQ applies the NEQ predicate on the "product_brand" field.
func ProductBrandNEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldProductBrand, v))
}

// ProductBrandIn applies the In predicate on the "product_brand" field.
func ProductBrandIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldProductBrand, vs...))
}

// ProductBrandNotIn applies the NotIn predicate on the "product_brand" field.
func ProductBrandNotIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldProductBrand, vs...))
}

// ProductBrandGT applies the GT predicate on the "product_brand" field.
func ProductBrandGT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldProductBrand, v))
}

// ProductBrandGTE applies the GTE predicate on the "product_brand" field.
func ProductBrandGTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldProductBrand, v))
}

// ProductBrandLT applies the LT predicate on the "product_brand" field.
func ProductBrandLT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldProductBrand, v))
}

// ProductBrandLTE applies the LTE predicate on the "product_brand" field.
func ProductBrandLTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldProductBrand, v))
}

// ProductBrandContains applies the Contains predicate on the "product_brand" field.
func ProductBrandContains(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContains(FieldProductBrand, v))
}

// ProductBrandHasPrefix applies the HasPrefix predicate on the "product_brand" field.
func ProductBrandHasPrefix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasPrefix(FieldProductBrand, v))
}

// ProductBrandHasSuffix applies the HasSuffix predicate on the "product_brand" field.
func ProductBrandHasSuffix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasSuffix(FieldProductBrand, v))
}

// ProductBrandIsNil applies the IsNil predicate on the "product_brand" field.
func ProductBrandIsNil() predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIsNull(FieldProductBrand))
}

// ProductBrandNotNil applies the NotNil predicate on the "product_brand" field.
func ProductBrandNotNil() predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotNull(FieldProductBrand))
}

// ProductBrandEqualFold applies the EqualFold predicate on the "product_brand" field.
func ProductBrandEqualFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEqualFold(FieldProductBrand, v))
}

// ProductBrandContainsFold applies the ContainsFold predicate on the "product_brand" field.
func ProductBrandContainsFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContainsFold(FieldProductBrand, v))
}

// ProductURLEQ applies the EQ predicate on the "product_url" field.
func ProductURLEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldProductURL, v))
}

// ProductURLNEQ applies the NEQ predicate on the "product_url" field.
func ProductURLNEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldProductURL, v))
}

// ProductURLIn applies the In predicate on the "product_url" field.
func ProductURLIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldProductURL, vs...))
}

// ProductURLNotIn applies the NotIn predicate on the "product_url" field.
func ProductURLNotIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldProductURL, vs...))
}

// ProductURLGT applies the GT predicate on the "product_url" field.
func ProductURLGT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldProductURL, v))
}

// ProductURLGTE applies the GTE predicate on the "product_url" field.
func ProductURLGTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldProductURL, v))
}

// ProductURLLT applies the LT predicate on the "product_url" field.
func ProductURLLT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldProductURL, v))
}

// ProductURLLTE applies the LTE predicate on the "product_url" field.
func ProductURLLTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldProductURL, v))
}

// ProductURLContains applies the Contains predicate on the "product_url" field.
func ProductURLContains(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContains(FieldProductURL, v))
}

// ProductURLHasPrefix applies the HasPrefix predicate on the "product_url" field.
func ProductURLHasPrefix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasPrefix(FieldProductURL, v))
}

// ProductURLHasSuffix applies the HasSuffix predicate on the "product_url" field.
func ProductURLHasSuffix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasSuffix(FieldProductURL, v))
}

// ProductURLIsNil applies the IsNil predicate on the "product_url" field.
func ProductURLIsNil() predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIsNull(FieldProductURL))
}

// ProductURLNotNil applies the NotNil predicate on the "product_url" field.
func ProductURLNotNil() predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotNull(FieldProductURL))
}

// ProductURLEqualFold applies the EqualFold predicate on the "product_url" field.
func ProductURLEqualFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEqualFold(FieldProductURL, v))
}

// ProductURLContainsFold applies the ContainsFold predicate on the "product_url" field.
func ProductURLContainsFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContainsFold(FieldProductURL, v))
}

// ProductDataIsNil applies the IsNil predicate on the "product_data" field.
func ProductDataIsNil() predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIsNull(FieldProductData))
}

// ProductDataNotNil applies the NotNil predicate on the "product_data" field.
func ProductDataNotNil() predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotNull(FieldProductData))
}

// InteractionTypeEQ applies the EQ predicate on the "interaction_type" field.
func InteractionTypeEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldInteractionType, v))
}

// InteractionTypeNEQ applies the NEQ predicate on the "interaction_type" field.
func InteractionTypeNEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldInteractionType, v))
}

// InteractionTypeIn applies the In predicate on the "interaction_type" field.
func InteractionTypeIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldInteractionType, vs...))
}

// InteractionTypeNotIn applies the NotIn predicate on the "interaction_type" field.
func InteractionTypeNotIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldInteractionType, vs...))
}

// InteractionTypeGT applies the GT predicate on the "interaction_type" field.
func InteractionTypeGT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldInteractionType, v))
}

// InteractionTypeGTE applies the GTE predicate on the "interaction_type" field.
func InteractionTypeGTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldInteractionType, v))
}

// InteractionTypeLT applies the LT predicate on the "interaction_type" field.
func InteractionTypeLT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldInteractionType, v))
}

// InteractionTypeLTE applies the LTE predicate on the "interaction_type" field.
func InteractionTypeLTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldInteractionType, v))
}

// InteractionTypeContains applies the Contains predicate on the "interaction_type" field.
func InteractionTypeContains(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContains(FieldInteractionType, v))
}

// InteractionTypeHasPrefix applies the HasPrefix predicate on the "interaction_type" field.
func InteractionTypeHasPrefix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasPrefix(FieldInteractionType, v))
}

// InteractionTypeHasSuffix applies the HasSuffix predicate on the "interaction_type" field.
func InteractionTypeHasSuffix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasSuffix(FieldInteractionType, v))
}

// InteractionTypeEqualFold applies the EqualFold predicate on the "interaction_type" field.
func InteractionTypeEqualFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEqualFold(FieldInteractionType, v))
}

// InteractionTypeContainsFold applies the ContainsFold predicate on the "interaction_type" field.
func InteractionTypeContainsFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContainsFold(FieldInteractionType, v))
}

// MessagePositionEQ applies the EQ predicate on the "message_position" field.
func MessagePositionEQ(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldMessagePosition, v))
}

// MessagePositionNEQ applies the NEQ predicate on the "message_position" field.
func MessagePositionNEQ(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldMessagePosition, v))
}

// MessagePositionIn applies the In predicate on the "message_position" field.
func MessagePositionIn(vs ...int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldMessagePosition, vs...))
}

// MessagePositionNotIn applies the NotIn predicate on the "message_position" field.
func MessagePositionNotIn(vs ...int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldMessagePosition, vs...))
}

// MessagePositionGT applies the GT predicate on the "message_position" field.
func MessagePositionGT(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldMessagePosition, v))
}

// MessagePositionGTE applies the GTE predicate on the "message_position" field.
func MessagePositionGTE(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldMessagePosition, v))
}

// MessagePositionLT applies the LT predicate on the "message_position" field.
func MessagePositionLT(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldMessagePosition, v))
}

// MessagePositionLTE applies the LTE predicate on the "message_position" field.
func MessagePositionLTE(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldMessagePosition, v))
}

// ViewDurationSecondsEQ applies the EQ predicate on the "view_duration_seconds" field.
func ViewDurationSecondsEQ(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldViewDurationSeconds, v))
}

// ViewDurationSecondsNEQ applies the NEQ predicate on the "view_duration_seconds" field.
func ViewDurationSecondsNEQ(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldViewDurationSeconds, v))
}

// ViewDurationSecondsIn applies the In predicate on the "view_duration_seconds" field.
func ViewDurationSecondsIn(vs ...int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldViewDurationSeconds, vs...))
}

// ViewDurationSecondsNotIn applies the NotIn predicate on the "view_duration_seconds" field.
func ViewDurationSecondsNotIn(vs ...int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldViewDurationSeconds, vs...))
}

// ViewDurationSecondsGT applies the GT predicate on the "view_duration_seconds" field.
func ViewDurationSecondsGT(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldViewDurationSeconds, v))
}

// ViewDurationSecondsGTE applies the GTE predicate on the "view_duration_seconds" field.
func ViewDurationSecondsGTE(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldViewDurationSeconds, v))
}

// ViewDurationSecondsLT applies the LT predicate on the "view_duration_seconds" field.
func ViewDurationSecondsLT(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldViewDurationSeconds, v))
}

// ViewDurationSecondsLTE applies the LTE predicate on the "view_duration_seconds" field.
func ViewDurationSecondsLTE(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldViewDurationSeconds, v))
}

// ClickCountEQ applies the EQ predicate on the "click_count" field.
func ClickCountEQ(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldClickCount, v))
}

// ClickCountNEQ applies the NEQ predicate on the "click_count" field.
func ClickCountNEQ(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldClickCount, v))
}

// ClickCountIn applies the In predicate on the "click_count" field.
func ClickCountIn(vs ...int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldClickCount, vs...))
}

// ClickCountNotIn applies the NotIn predicate on the "click_count" field.
func ClickCountNotIn(vs ...int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldClickCount, vs...))
}

// ClickCountGT applies the GT predicate on the "click_count" field.
func ClickCountGT(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldClickCount, v))
}

// ClickCountGTE applies the GTE predicate on the "click_count" field.
func ClickCountGTE(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldClickCount, v))
}

// ClickCountLT applies the LT predicate on the "click_count" field.
func ClickCountLT(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldClickCount, v))
}

// ClickCountLTE applies the LTE predicate on the "click_count" field.
func ClickCountLTE(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldClickCount, v))
}

// OpenedDetailsEQ applies the EQ predicate on the "opened_details" field.
func OpenedDetailsEQ(v bool) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldOpenedDetails, v))
}

// OpenedDetailsNEQ applies the NEQ predicate on the "opened_details" field.
func OpenedDetailsNEQ(v bool) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldOpenedDetails, v))
}

// AddedToComparisonEQ applies the EQ predicate on the "added_to_comparison" field.
func AddedToComparisonEQ(v bool) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldAddedToComparison, v))
}

// AddedToComparisonNEQ applies the NEQ predicate on the "added_to_comparison" field.
func AddedToComparisonNEQ(v bool) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldAddedToComparison, v))
}

// FeedbackEQ applies the EQ predicate on the "feedback" field.
func FeedbackEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldFeedback, v))
}

// FeedbackNEQ applies the NEQ predicate on the "feedback" field.
func FeedbackNEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldFeedback, v))
}

// FeedbackIn applies the In predicate on the "feedback" field.
func FeedbackIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldFeedback, vs...))
}

// FeedbackNotIn applies the NotIn predicate on the "feedback" field.
func FeedbackNotIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldFeedback, vs...))
}

// FeedbackGT applies the GT predicate on the "feedback" field.
func FeedbackGT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldFeedback, v))
}

// FeedbackGTE applies the GTE predicate on the "feedback" field.
func FeedbackGTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldFeedback, v))
}

// FeedbackLT applies the LT predicate on the "feedback" field.
func FeedbackLT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldFeedback, v))
}

// FeedbackLTE applies the LTE predicate on the "feedback" field.
func FeedbackLTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldFeedback, v))
}

// FeedbackContains applies the Contains predicate on the "feedback" field.
func FeedbackContains(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContains(FieldFeedback, v))
}

// FeedbackHasPrefix applies the HasPrefix predicate on the "feedback" field.
func FeedbackHasPrefix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasPrefix(FieldFeedback, v))
}

// FeedbackHasSuffix applies the HasSuffix predicate on the "feedback" field.
func FeedbackHasSuffix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasSuffix(FieldFeedback, v))
}

// FeedbackIsNil applies the IsNil predicate on the "feedback" field.
func FeedbackIsNil() predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIsNull(FieldFeedback))
}

// FeedbackNotNil applies the NotNil predicate on the "feedback" field.
func FeedbackNotNil() predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotNull(FieldFeedback))
}

// FeedbackEqualFold applies the EqualFold predicate on the "feedback" field.
func FeedbackEqualFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEqualFold(FieldFeedback, v))
}

// FeedbackContainsFold applies the ContainsFold predicate on the "feedback" field.
func FeedbackContainsFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContainsFold(FieldFeedback, v))
}

// ImplicitScoreEQ applies the EQ predicate on the "implicit_score" field.
func ImplicitScoreEQ(v float64) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldImplicitScore, v))
}

// ImplicitScoreNEQ applies the NEQ predicate on the "implicit_score" field.
func ImplicitScoreNEQ(v float64) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldImplicitScore, v))
}

// ImplicitScoreIn applies the In predicate on the "implicit_score" field.
func ImplicitScoreIn(vs ...float64) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldImplicitScore, vs...))
}

// ImplicitScoreNotIn applies the NotIn predicate on the "implicit_score" field.
func ImplicitScoreNotIn(vs ...float64) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldImplicitScore, vs...))
}

// ImplicitScoreGT applies the GT predicate on the "implicit_score" field.
func ImplicitScoreGT(v float64) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldImplicitScore, v))
}

// ImplicitScoreGTE applies the GTE predicate on the "implicit_score" field.
func ImplicitScoreGTE(v float64) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldImplicitScore, v))
}

// ImplicitScoreLT applies the LT predicate on the "implicit_score" field.
func ImplicitScoreLT(v float64) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldImplicitScore, v))
}

// ImplicitScoreLTE applies the LTE predicate on the "implicit_score" field.
func ImplicitScoreLTE(v float64) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldImplicitScore, v))
}

// SearchQueryEQ applies the EQ predicate on the "search_query" field.
func SearchQueryEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldSearchQuery, v))
}

// SearchQueryNEQ applies the NEQ predicate on the "search_query" field.
func SearchQueryNEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldSearchQuery, v))
}

// SearchQueryIn applies the In predicate on the "search_query" field.
func SearchQueryIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldSearchQuery, vs...))
}

// SearchQueryNotIn applies the NotIn predicate on the "search_query" field.
func SearchQueryNotIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldSearchQuery, vs...))
}

// SearchQueryGT applies the GT predicate on the "search_query" field.
func SearchQueryGT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldSearchQuery, v))
}

// SearchQueryGTE applies the GTE predicate on the "search_query" field.
func SearchQueryGTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldSearchQuery, v))
}

// SearchQueryLT applies the LT predicate on the "search_query" field.
func SearchQueryLT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldSearchQuery, v))
}

// SearchQueryLTE applies the LTE predicate on the "search_query" field.
func SearchQueryLTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldSearchQuery, v))
}

// SearchQueryContains applies the Contains predicate on the "search_query" field.
func SearchQueryContains(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContains(FieldSearchQuery, v))
}

// SearchQueryHasPrefix applies the HasPrefix predicate on the "search_query" field.
func SearchQueryHasPrefix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasPrefix(FieldSearchQuery, v))
}

// SearchQueryHasSuffix applies the HasSuffix predicate on the "search_query" field.
func SearchQueryHasSuffix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasSuffix(FieldSearchQuery, v))
}

// SearchQueryIsNil applies the IsNil predicate on the "search_query" field.
func SearchQueryIsNil() predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIsNull(FieldSearchQuery))
}

// SearchQueryNotNil applies the NotNil predicate on the "search_query" field.
func SearchQueryNotNil() predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotNull(FieldSearchQuery))
}

// SearchQueryEqualFold applies the EqualFold predicate on the "search_query" field.
func SearchQueryEqualFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEqualFold(FieldSearchQuery, v))
}

// SearchQueryContainsFold applies the ContainsFold predicate on the "search_query" field.
func SearchQueryContainsFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContainsFold(FieldSearchQuery, v))
}

// SearchTypeEQ applies the EQ predicate on the "search_type" field.
func SearchTypeEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldSearchType, v))
}

// SearchTypeNEQ applies the NEQ predicate on the "search_type" field.
func SearchTypeNEQ(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldSearchType, v))
}

// SearchTypeIn applies the In predicate on the "search_type" field.
func SearchTypeIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldSearchType, vs...))
}

// SearchTypeNotIn applies the NotIn predicate on the "search_type" field.
func SearchTypeNotIn(vs ...string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldSearchType, vs...))
}

// SearchTypeGT applies the GT predicate on the "search_type" field.
func SearchTypeGT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldSearchType, v))
}

// SearchTypeGTE applies the GTE predicate on the "search_type" field.
func SearchTypeGTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldSearchType, v))
}

// SearchTypeLT applies the LT predicate on the "search_type" field.
func SearchTypeLT(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldSearchType, v))
}

// SearchTypeLTE applies the LTE predicate on the "search_type" field.
func SearchTypeLTE(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldSearchType, v))
}

// SearchTypeContains applies the Contains predicate on the "search_type" field.
func SearchTypeContains(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContains(FieldSearchType, v))
}

// SearchTypeHasPrefix applies the HasPrefix predicate on the "search_type" field.
func SearchTypeHasPrefix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasPrefix(FieldSearchType, v))
}

// SearchTypeHasSuffix applies the HasSuffix predicate on the "search_type" field.
func SearchTypeHasSuffix(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldHasSuffix(FieldSearchType, v))
}

// SearchTypeIsNil applies the IsNil predicate on the "search_type" field.
func SearchTypeIsNil() predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIsNull(FieldSearchType))
}

// SearchTypeNotNil applies the NotNil predicate on the "search_type" field.
func SearchTypeNotNil() predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotNull(FieldSearchType))
}

// SearchTypeEqualFold applies the EqualFold predicate on the "search_type" field.
func SearchTypeEqualFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEqualFold(FieldSearchType, v))
}

// SearchTypeContainsFold applies the ContainsFold predicate on the "search_type" field.
func SearchTypeContainsFold(v string) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldContainsFold(FieldSearchType, v))
}

// PositionInResultsEQ applies the EQ predicate on the "position_in_results" field.
func PositionInResultsEQ(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldPositionInResults, v))
}

// PositionInResultsNEQ applies the NEQ predicate on the "position_in_results" field.
func PositionInResultsNEQ(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldPositionInResults, v))
}

// PositionInResultsIn applies the In predicate on the "position_in_results" field.
func PositionInResultsIn(vs ...int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldPositionInResults, vs...))
}

// PositionInResultsNotIn applies the NotIn predicate on the "position_in_results" field.
func PositionInResultsNotIn(vs ...int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldPositionInResults, vs...))
}

// PositionInResultsGT applies the GT predicate on the "position_in_results" field.
func PositionInResultsGT(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldPositionInResults, v))
}

// PositionInResultsGTE applies the GTE predicate on the "position_in_results" field.
func PositionInResultsGTE(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldPositionInResults, v))
}

// PositionInResultsLT applies the LT predicate on the "position_in_results" field.
func PositionInResultsLT(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldPositionInResults, v))
}

// PositionInResultsLTE applies the LTE predicate on the "position_in_results" field.
func PositionInResultsLTE(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldPositionInResults, v))
}

// InteractionSequenceEQ applies the EQ predicate on the "interaction_sequence" field.
func InteractionSequenceEQ(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldInteractionSequence, v))
}

// InteractionSequenceNEQ applies the NEQ predicate on the "interaction_sequence" field.
func InteractionSequenceNEQ(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldInteractionSequence, v))
}

// InteractionSequenceIn applies the In predicate on the "interaction_sequence" field.
func InteractionSequenceIn(vs ...int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldInteractionSequence, vs...))
}

// InteractionSequenceNotIn applies the NotIn predicate on the "interaction_sequence" field.
func InteractionSequenceNotIn(vs ...int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldInteractionSequence, vs...))
}

// InteractionSequenceGT applies the GT predicate on the "interaction_sequence" field.
func InteractionSequenceGT(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldInteractionSequence, v))
}

// InteractionSequenceGTE applies the GTE predicate on the "interaction_sequence" field.
func InteractionSequenceGTE(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldInteractionSequence, v))
}

// InteractionSequenceLT applies the LT predicate on the "interaction_sequence" field.
func InteractionSequenceLT(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldInteractionSequence, v))
}

// InteractionSequenceLTE applies the LTE predicate on the "interaction_sequence" field.
func InteractionSequenceLTE(v int) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldInteractionSequence, v))
}

// InteractedAtEQ applies the EQ predicate on the "interacted_at" field.
func InteractedAtEQ(v time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldInteractedAt, v))
}

// InteractedAtNEQ applies the NEQ predicate on the "interacted_at" field.
func InteractedAtNEQ(v time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldInteractedAt, v))
}

// InteractedAtIn applies the In predicate on the "interacted_at" field.
func InteractedAtIn(vs ...time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldInteractedAt, vs...))
}

// InteractedAtNotIn applies the NotIn predicate on the "interacted_at" field.
func InteractedAtNotIn(vs ...time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldInteractedAt, vs...))
}

// InteractedAtGT applies the GT predicate on the "interacted_at" field.
func InteractedAtGT(v time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldInteractedAt, v))
}

// InteractedAtGTE applies the GTE predicate on the "interacted_at" field.
func InteractedAtGTE(v time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldInteractedAt, v))
}

// InteractedAtLT applies the LT predicate on the "interacted_at" field.
func InteractedAtLT(v time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldInteractedAt, v))
}

// InteractedAtLTE applies the LTE predicate on the "interacted_at" field.
func InteractedAtLTE(v time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldInteractedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ProductInteraction {
	return predicate.ProductInteraction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ProductInteraction {
	return predicate.ProductInteraction(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProductInteraction) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProductInteraction) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProductInteraction) predicate.ProductInteraction {
	return predicate.ProductInteraction(sql.NotPredicates(p))
}
